### ISSUE TITLE
Can't align "result" to center

### ISSUE THREAD

**Issue by Chi7777** [Foliotek/Croppie#102]
I delete the"sweetalert" and change to a ordinary "modal",
however it cannot align to center,
I also found that the web's width was very wide!(window size:1366643 x .......) 
Can you help me to let "modal" align to center?

This is my web: http://whale.mine.csie.ncu.edu.tw/p2015/Croppie-master/

P.S.I'm a high school student from Chinese,I hope you can understand what I said >_<

**Comment by thedustinsmith** [comment]
I'm sure there are several ways you can accomplish what you're trying to do - one way would be to add the following styles to your `.modal-content{}` selector:

```    
left: 50%;
transform: translateX(-50%);
```

That aligns the left side of your modal to the center of the screen, then the transform moves it 50% of it's own width back to the left.

Hope that helps.

**Comment by Chi7777** [comment]
Without your help,I couldn't have done it.
Thank you very much!!!
