### ISSUE TITLE
Start without zoom / Disable initial zoom

### ISSUE THREAD

**Issue by luansemensatoribeiro** [Foliotek/Croppie#103]
On start, set the slider minimum (no zoom).

OK:
![no-zoom](https://cloud.githubusercontent.com/assets/2083823/13884103/3655088c-ed0b-11e5-9549-221523daacf5.png)

Bad :(
![zoom](https://cloud.githubusercontent.com/assets/2083823/13884130/6475ebb4-ed0b-11e5-9f30-d35136e68f22.png)

**Comment by geraldarcega** [comment]
Hi! Any updates on this?

**Comment by thedustinsmith** [comment]
I'm a little unclear on what's desired here.  You'd like croppie to start with the image not scaled at all?  Or you'd like to be able to set the zoom programatically on start?

**Comment by geraldarcega** [comment]
In my case, I would like to set the zoom on start after binding the image. Anyway, I already change my approach so there's no need for me. Btw, @thedustinsmith I would like to report a possible bug in chrome mobile, please see #121

**Comment by vctung** [comment]
Hey, Anyone resolved this issue ????? hmmmm I can not find any solutions for it !
Let share anythings.... :(

**Comment by vctung** [comment]
OMG ! Just commet this line ** // points: [77,469,280,739]**

```
   basic.croppie('bind', {
                url: img,
                // points: [77,469,280,739]
            });
```

**Comment by hrlwfres** [comment]
I think it is the same problem as me : when you upload an image, the boundary area is filled : 
![before](https://cloud.githubusercontent.com/assets/3857484/14778544/dd11d0c0-0ad3-11e6-81fc-daaa30623fba.png)
I would like (and I think it the same for OP) that it is not or only one side if the image does not respect the ratio: 

![after](https://cloud.githubusercontent.com/assets/3857484/14778553/e89eb11a-0ad3-11e6-835a-a5521fe2c956.png)

Is it possible to have the image at the maximum zoom out on upload.?

**Comment by thedustinsmith** [comment]
@hrlwfres - croppie has a `setZoom` method, so to get the behavior you'd like you can actually call `setZoom(0)` (after the upload).  

In your case you don't need an exact value, because you just want it to be as zoomed out as possible.  Croppie does a `Math.min(Math.max(minZoom, [setZoomValue]), maxZoom)`, which will prevent it from being smaller than your viewport.  

Unfortunately, there's no way to set the zoom to less than the dimensions of the viewport, currently.

**Comment by ormir** [comment]
Hello everybody,
to initialise croppie without zoom i changed the line:

function _updatePropertiesFromImage() {
...
initialZoom = Math.max((boundaryData.width / imgData.width), (boundaryData.height / imgData.height));
...
}

to 

`initialZoom = zoomer.min;`

**Comment by edagenais** [comment]
Any resolution or alternative options to get initialZoom to be set to the minimum zoom possible on initialization? I've tried several things, including trying to leverage the promise from the bind, but nothing has worked so far except for the solution @ormir brought to the table. Although it does work, messing about the source of an external lib is not an ideal solution imo.

**Comment by thedustinsmith** [comment]
Minimum possible zoom with `enforceBoundary=true`?

Is there a problem with doing it this way? 
 `croppieInst.setZoom(0)` or for jquery: `$c.croppie('setZoom', 0)`

**Comment by edagenais** [comment]
Is `enforceBoundary=true` supposed to be added as part of the initialization options? If so, that didn't work. Else, could you please elaborate?

As for `croppieInst.setZoom(0)`, that works, but only if I apply it manually via the console once everything "appears" to have completed. When I place it in a seemingly logical place in code, it doesn't work. I'm guessing it's because the image handler isn't finished processing yet and my `setZoom()` call is premature - hence the reason for trying to leverage the promise from the bind.

**Comment by thedustinsmith** [comment]
I think I understand.

So rather than doing:
```
myCrop.bind('whatever.png').then(function(){
    myCrop.setZoom(0);
});
```
You'd rather something like this:
```
myCrop.bind({
  src: 'whatever.png',
  zoom: 0
});
```

Is that right?

**Comment by edagenais** [comment]
@thedustinsmith, either one of those would be great - but I can't even get your first example to work. I think I may be doing something wrong in my croppie initialization. In my code, `myCrop` is actually jQuery object. When I want to do any interaction with it, I always have to form everything like:

$('#myCroppieElement').croppie('commandName', object);

I'm getting the impression that jQuery may be conflicting with the promise from the `bind` somehow. I'm going to try flipping to the non-jQuery route of initialization and see if that aligns things better.

**Comment by thedustinsmith** [comment]
Oh wow - you're right.  Croppie's bind isn't returning anything with the jquery integration.  That's a bug!

While you're messing with your code, can you try adding this to line 1144 https://github.com/Foliotek/Croppie/blob/master/croppie.js#L1144

```
else if (opts === 'bind') {
    return singleInst.bind.apply(singleInst, args);
}
```

and see if that fixes your jquery problems?

**Comment by edagenais** [comment]
@thedustinsmith - beautiful! That did it. The promise coming from the `bind` is now working with the jQuery variant.

**Comment by GaganTiwari** [comment]
I am also facing too much problem in setting zoom level at begining. It ll be great help if any one tell me exact solution to set no zoom when assign a image to cropper as default.

Thanks in advance.

**Comment by KrakenTyP-co** [comment]
Work for me (es6 version)

```
        this.croppie = new Croppie(document.getElementById('crop-img-container'), opts);
        this.croppie.bind(imgToCrop)
            .then(() => {
                this.croppie.setZoom(0);
            });
```

**Comment by YehuditGrinwald** [comment]
Start without zoom you need to **set zoom tho min**.
 let zoom = document.getElementsByClassName('cr-slider');
this.croppie.setZoom(parseFloat(zoom[0].getAttribute('min')));

**Comment by fukashigi1** [comment]
I have solved the problem by doing what YehuditGrinwald wrote, but leaving the line 

`croppieInstance.setZoom(parseFloat(zoom[0].getAttribute('min')));`

inside a setTimeout. This way:

```
setTimeout(() => {
    croppieInstance.setZoom(parseFloat(zoom[0].getAttribute('min')));
}, 100);
```
