### ISSUE TITLE
error zoom

### ISSUE THREAD

**Issue by andynhoo** [Foliotek/Croppie#106]
http://andlima.com.br/rotpark/
I use MessiJS (Modal) and Croppie
user: any
pass: any

after uploading the error in the zoom
![captura de tela 186](https://cloud.githubusercontent.com/assets/7599346/13960189/1487329c-f036-11e5-988b-a3f458b25e56.png)
![captura de tela 185](https://cloud.githubusercontent.com/assets/7599346/13960190/14ace442-f036-11e5-823c-3aa4990cacc0.png)
![captura de tela 184](https://cloud.githubusercontent.com/assets/7599346/13960191/14e08266-f036-11e5-8a53-5c3b56a32561.png)

Code:
`								//Modal para cortar imagem
								var dialog = new Messi('<div id="vw"></div>', {
									viewport:{ top: '3%',
									left: '30%' },
									width:'450px',
									title: 'Cortar Imagem',
									modal: true,
									zIndex:999999,
									closeButton:false,
									center: false, 
									buttons: [{id: 0, label: 'Cortar', val: 'C'},{id: 1, label: 'Cancelar', val: 'F', },],
									callback: function(val) {
										if(val == 'C'){
											CortarImagem(); 
										} else {
											dialog.close;
										}
									}
								}); 
								//Seleçao para corte da imagem
								var basic = $('#vw').croppie({
									viewport: {
										width: 100,
										height: 100,
									}
								});
								basic.croppie('bind', {
									url: caminho,
									point: [0, 0, 0, 0]
								});

								}	`

**Comment by thedustinsmith** [comment]
I'm not familiar with MessiJS, and your code sample is very hard to read.  If I had to guess, what's happening is your croppie logic is being ran when the messi modal isn't visible. 

If Messi has an event or a callback that fires after the modal is shown, then that's where you want to either initialize your croppie, or call `croppieObject.bind()` without any paramters, which refereshes its position.

**Comment by thedustinsmith** [comment]
Closing due to lack of contact.
