### ISSUE TITLE
[SOLVED] Export image certain width and height

### ISSUE THREAD

**Issue by byinff** [Foliotek/Croppie#107]
Hello,

I have a query, I am wanting to export to a resolution of 1500x500 an image of 2000x2000. The problem is that the viewport of that size would not go into some resolutions.

Any ideas ?

thank you very much

regards

**Comment by thedustinsmith** [comment]
Hey, it's not documented yet, but just last week someone submitted a PR to add this functionality.

#101 Added this functionality.  I would follow the sample code in that case and it should help.

We'll try to add this to the documentation soon.

**Comment by byinff** [comment]
Hi thedustinsmith,

I just tried what you said but without any result. my initialization is as follows

var uploadCropProfile = cropperPortada.croppie({
	viewport: {
		width: 128,
		height: 128
	},
	boundary: {
	        width: 400,
		height: 150
	}
});

And the function bind result is the next : 

cropperPortada.croppie('result', {
	type   : 'canvas',
	format : 'jpeg',
	quality: '0.9',
	size: {
		width: 1500,
		height: 500
	}
});

I'm uploading an image of a resolution of 1280x720 and 1500x500 want to export it

Thanks

**Comment by thedustinsmith** [comment]
What do you mean by "without any result"?

If you can throw together a jsbin/jsfiddle I might be able to help you out a little more.

**Comment by byinff** [comment]
i can't export image with custom size. I upload an image of 2000x200 and the viewport is 400x200 and i like export the image of 1500x500

**Comment by thedustinsmith** [comment]
What happens when you call `result()` with those parameters?  Can you log out the response of `result` and send it this way?  

Or better yet, throw together an example that we can see.

**Comment by byinff** [comment]
When I get the results of the exported image rather than of 1500x500 it is 100x100

cropperPortada.croppie('result', {
  type : 'canvas',
  format : 'jpeg',
  quality: '0.9',
  size: {
    width: 1500,
    height: 500
  }
});

**Comment by thedustinsmith** [comment]
What version of croppie are you using?

**Comment by byinff** [comment]
i use version 2.0.2. Sorry for my english

**Comment by thedustinsmith** [comment]
Is there anyway you can grab the latest from master and test using that code? https://github.com/Foliotek/Croppie/blob/master/croppie.js

I made a few changes last night that might affect this.

**Comment by byinff** [comment]
Wooooooooooooooooooooooooooooooooooooooo, amazing.

Very very thankssssss :D

**Comment by thedustinsmith** [comment]
Glad it worked!
