### ISSUE TITLE
Croppie crop Tool not working on Iphone 6 plus 

### ISSUE THREAD

**Issue by pratikbendale50** [Foliotek/Croppie#108]
Hi ,

I am using croppie for Image crop in my hybrid app development But It is showing Memory Warning Issue and then crash for Iphone 6 plus only, working fine on all other IOS devices .

In Iphone 6 plus  when I Do choose from gallery  It will work fine But when I select Capture photo from camera ,after capturing Image i get set to image area but after some time it crashes.

# My code for take picture is as follows

 Camera.getPicture().then($scope.onPhotoFileSuccess, $scope.onFail, 
            {
                quality: 50,                        
                targetWidth: 100,
                targetHeight: 100,                
                saveToPhotoAlbum: false,                            
            });

# My code for cropping is 

 var mc = $('#cropper-1');
        mc.croppie({
            viewport: {
                width: 150,
                height: 150,
                type: 'square'
            },
            showZoomer: false
            // mouseWheelZoom: false
        });
        mc.croppie('bind',capturedImg);
        $('.okbutton').on('click', function (ev) {
            mc.croppie('result', {
                type: 'canvas',
                format: 'jpeg'
            }).then(function (resp) {
                // console.log("resp",resp)
                $scope.upload(resp);  
                 // cropedImg=resp;              
            });
        });

I am using Ionic for hybrid app development 

Please suggest any solution

**Comment by thedustinsmith** [comment]
I don't have an iphone 6, and don't know much about hybrid app development.  Doesn't iPhone 6 take Live Photos?  Where they're actually gifs or a series of photos?  That's not part of your problem, is it?

**Comment by pratikbendale50** [comment]
No that is not my problem,
MY problem is when I click photo from Iphone 6 plus and  use that image In croppie then the app shows Memory warning and crashes

**Comment by thedustinsmith** [comment]
Yeah - I understood that from your first comment.  

Maybe if you share the image from which you're getting the error on this thread - we can figure out what's going on.

**Comment by thedustinsmith** [comment]
Closing due to lack of contact

**Comment by van-hung-mulodo** [comment]
@pratikbendale50 I got same your problem. 
Could you please tell me if you found the solution to fix the problem?
