### ISSUE TITLE
croppie('result', 'canvas') returning blank(black) image

### ISSUE THREAD

**Issue by Jabinc** [Foliotek/Croppie#112]
I am opening a local html file with css and javascript inside the html file on Safari v9.0.3.
The croppie window is displaying as expected.  The image is being uploaded through a form with
`<input type="file" accept="image/*" multiple name="img[]" id="image" />`
The bind method works to display the image and cycles to the next image without a problem.  It then cycles on to the appropriate 'AddTitle' data-role page.  In 'AddTitle' the croppie('result', 'canvas') is displayed as a blank (black) image in the correct cropped dimensions.  
`alert(imgString[imageCounter]);`
shows the same base64 data for the stored image in the array each time it is called (this is the blank black image stored each time).  Code is below.  Thank you for any suggestions or comments on the code.

I have been looking at problems with the draw buffer, but to my understanding they don't apply since this is occurring inside the same 'Cropped' function?

``` javascript
var imageCounter = 0;
var imgString = [];
var imageArray = [];

function Cropped(){
  var h = $( window ).height();
  var w = $( window ).width();
  var cropWindow = $(".crop");
  cropWindow.croppie({
    viewport: {
          width: 270,
          height: 960,
          type: 'square' //default 'square'
      },
      boundary: {
          width: w,
          height: h
      },
      enableZoom: true, //default true // previously showZoom
      showZoomer: false, //default true
      mouseWheelZoom: true //default true
  });
  imageArray = document.getElementById("image");
  $("#imageUpload").hide();
  var URLString = window.URL.createObjectURL(imageArray.files[imageCounter]);
  cropWindow.croppie('bind', {url: URLString});
  $(document).on('click', '#addPhoto', function cropAction(e){
    e.preventDefault();
    if(imageArray.files.length>0){
      cropWindow.croppie('get');
      cropWindow.croppie("result", {type: "canvas", format: "jpeg"}).then(function(img){
        imgString[imageCounter] = img;
        alert(imgString[imageCounter]);
        imageCounter++;
        cropWindow.croppie("destroy");
        if(imageCounter<imageArray.files.length){
          Cropped();
        }
        else{
          var imgSRC;
          imgSRC = '<img src="' + imgString[0] + '" />';
          $('#imageTest').html(imgSRC);
          $("#redirectToAddTitle").click();
        }
      });
    }
  });
}
```

**Comment by thedustinsmith** [comment]
I'm guessing you're getting the black image when you're setting `$('#imageTest').html(imgSRC)` - is that right?

I'm guessing your black image comes from using the jpeg extension.  Jpeg doesn't support transparency, and somehow I'm guessing that your croppie is incorrect on the positioning.  If you change your format to `png` - do you get a white image?

If you can throw a demo in jsfiddle or jsbin, it would be easier to help.

**Comment by Jabinc** [comment]
Thank you for the quick response.
That is correct about when I am getting the black image.

Changing the extension to png does yield different results though not white.  from the scroll bar it is adding to the page I am guessing that it is adding a transparent image, which seems to speak to the transparency issue you mentioned.

The base64 being produced now is

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARIAAAPECAYAAABiz7Q4AAAAAXNSR0IArs4c6QAAEhpJREFUeAHt0AENAAAAwqD3T20PBxEoDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQ

I will take a look at using jsfiddle tonight  to provide something more useful for trouble shooting.  Thanks for the input and the plugin.

**Comment by Jabinc** [comment]
Your response guided me to investigate other parts of the code and the problem was in the css class of the wrapping div. Thank you very much for taking the time to respond.  How does one implement the customClass or otherwise use css to shift the croppie to a specific position without affecting the results?  I can affect the style using the customClass, but this still effects the result.  I am using 

`.photoFrame{
  position: fixed;
  top:5%;
}`

**Comment by thedustinsmith** [comment]
Hmm - you shouldn't have to perform an action for croppie to get an accurate result.  Although the position fixed might have something to do with it, I'll have to look into that.

Again, if you can throw together an example, I'd be more likely to track it down.

**Comment by Rajesh112** [comment]
I have created a simple html page with a image control and a button. button will be opening the croppie in a popup window. I need to get the cropped image back to the parent window's image control and I need to add a cancel button too. could anyone help me?

**Comment by Rajesh112** [comment]
I have used the same demo version for test purpose. I was not able to get the parent window object to fill the image.

**Comment by thedustinsmith** [comment]
I don't know the size limitations of `window.postMessage` - but you can try doing something like this:

```
$myCroppie.croppie('result', { type: 'canvas'}).then(function(resp){
window.opener.postMessage(resp, '*')
});
```

**Comment by Rajesh112** [comment]
Thanks for the reply. Can you please elaborate that? 
function popupResult(result) {
		debugger;
		var html;
		if (result.html) {
			html = result.html;
		}
		if (result.src) {
			html = '<img src="' + result.src + '" />';
		    
		}
		swal({
			title: '',
			html: true,
			text: html,
			allowOutsideClick: true
		});
		setTimeout(function(){
			$('.sweet-alert').css('margin', function() {
				var top = -1 * ($(this).height() / 2),
					left = -1 * ($(this).width() / 2);

				return top + 'px 0 0 ' + left + 'px';
			});
		}, 1);
	}
I will get the base64 image from result.src in demo.js. I have one html file which contains a image control. 
main.html
<img id ="Test1" height="100" width="100">
<a href="Test.html" onclick="return popupCrop('Test.html')" >Click</a>
here I am using one another html file just for popout the cropping part. I was trying to get a image as img control's image in the main.html

could you please help me on this?

**Comment by atgillette** [comment]
@Jabinc and @Rajesh112,

I've started noticing the same issue with the output being black if no image adjusts were made.

**Comment by atgillette** [comment]
submitted a pull request, #170 for this issue.

**Comment by tterrag1098** [comment]
I'm having a similar issue, using the 'result' function asking for base64, I only get a black image. Here's a code snippet:

```js
update: function(data) {
                            var $data = $("#image_upload_data");
                            $basic.croppie('result', {
                                type: 'base64',
                                size: 'original'
                            }).then(function(data) {
                                $data.val(data);
                            });
                        }
```

When I manually attempt to decode the result of this code, I only get a black image. Whether the croppie has been manipulated or not doesn't seem to affect anything.

**Comment by brij-mohan** [comment]
I am using below code in my project but crop image results does not correct. Please let me know if i have to install any dependency for that :

<div id="imageuploadModal" class="modal" role="dialog">
  <div class="modal-dialog">
	<div class="modal-content">
	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Please Select the image and crop for resize</h4>
      </div>
	 <img src="" id="check_image_status" style="display:none;" />
	    	
		 <form id= "filetoupload" action="<?php echo esc_url( $action ); ?>" method="post"  enctype="multipart/form-data">
			<div class="modal-body" style="padding-top:0px; ">
			<div class="modal-body-inner-wrapper">
				<div class="content-block">
				<div class="form-group">
				<input type="hidden" id="x" name="x" />
					<input type="hidden" id="y" name="y" />
					<input type="hidden" id="w" name="w" />
					<input type="hidden" id="h" name="h" /> 
				</div>
				</div>
				<div class="heading-block">
				
				
				
				 <input type="hidden" id="image_url" name="image_url" value="" />
			 
<div id="upload-demo" style="width:350px"></div>

<strong>Select Image:</strong>
<input type="file" id="upload" accept="image/jpeg" name="image">

				 
				  <div id="messageerrorfile">
				</div>
				
				</div>
			</div>
			 
			<div class="modal-footer for-rating pd-lr-30" style="padding-top:0px; padding-bottom:0px; ">
				<input type="submit"  class="round-btn upload_sucesss upload-result" value="Upload">
			</div> 
			</div>			
		  </form>
	 </div>
</div>
</div>


<script>


$uploadCrop = $('#upload-demo').croppie({ 

enableExif: true,

viewport: {

width: 200,

height: 200,

type: 'circle'

},

boundary: {

width: 300,

height: 300

}

});

$('#upload').on('change', function () {
var p = $(".col-sm-2.col-xs-12 .edit-profile.avatar-block .profile-image-box .upload-profile-image img");
url = p.attr('src');
var reader = new FileReader();

reader.onload = function (e) {

$uploadCrop.croppie('bind', {

url: e.target.result

}).then(function(){
var res = url.split("/"); 
var res_length =  res.length -1;			  
var image_name = res[res_length];
<?php
if($_SERVER["SERVER_NAME"] == '112.196.20.243')
{
$url =  "http://".$_SERVER["SERVER_NAME"].":".$_SERVER['SERVER_PORT']."/wp-content/uploads/job-manager-uploads/avatar/2016/10/"; 
}
else
{
$url =  "http://".$_SERVER["SERVER_NAME"]."/wp-content/uploads/job-manager-uploads/avatar/2016/10/";  				  
}
$subdir =   '/job-manager-uploads/avatar/2016/10';		
$path = $_SERVER["DOCUMENT_ROOT"]."/wp-content/uploads". $subdir;
?>
var original_image_url = '<?php echo $url; ?>'+image_name;
$("#image_url").val(original_image_url);
console.log('jQuery bind complete');

});

}

reader.readAsDataURL(this.files[0]);

});


$('.upload-result').on('click', function (ev) {

$uploadCrop.croppie('result', {

type: 'canvas',

size: 'viewport'

}).then(function (resp) {
	console.log(resp);
	$.event.trigger({
	type: "imageResized",
	blob: resp
	});


});

}); 

</script>

**Comment by Ty123** [comment]
I have similar problem to Jabinc, except it is only work when I create square or circle. When I tried to create rectangle image, I got rectangle image with black bottom.  if i choose png format it got blank image.

**Comment by SanketChaudhary01** [comment]
When I upload a new file then this happens. Even though, it becomes normal when I slide the zoom bar.

![screenshot from 2017-05-31 11-14-15](https://cloud.githubusercontent.com/assets/18378020/26617343/54b80c02-45f2-11e7-8db9-d65b7b0b0482.png)

The main problem is that on getting the result only the top left section is cropped, no matter where my viewport is.
Below is a screenshot of the same problem. The image behind is the cropped version even though the portion to be cropped is not on his face
![screenshot from 2017-05-31 11-18-29](https://cloud.githubusercontent.com/assets/18378020/26617456/ec52208e-45f2-11e7-94f5-a35b0200d6b2.png)


below is a link to some portion of code:
https://jsfiddle.net/godara01/k1m73bwu/#&togetherjs=1AM0PlGP5k

**Comment by thedustinsmith** [comment]
@SanketChaudhary01 You need to call bind on your croppie instance after your modal has completed opening.  Search through the issues in this repo and you'll find a half a dozen or so with the same issue.

**Comment by thedustinsmith** [comment]
@SanketChaudhary01 You need to call bind on your croppie instance after your modal has completed opening.  Search through the issues in this repo and you'll find a half a dozen or so with the same issue.

**Comment by SanketChaudhary01** [comment]
I've already written that in the code:
$('.demo').addClass('ready');
            $uploadCrop.croppie('bind', {
                url: e.target.result,

            }).then(function(){
                    console.log('jQuery bind complete');
            });

I was working on it the whole day but I am getting only the top left corner of the image.
You see even when my whole image is within the viewport area. my result is only the top left portion of the image.

![screenshot from 2017-06-01 03-07-57](https://cloud.githubusercontent.com/assets/18378020/26655276/d058c4c0-4677-11e7-824a-acfc820c9804.png)


![screenshot from 2017-06-01 03-08-09](https://cloud.githubusercontent.com/assets/18378020/26655283/d4bc5a4a-4677-11e7-8a4d-81b04f9061aa.png)

**Comment by thedustinsmith** [comment]
Are you transitioning the `ready` class?

**Comment by SanketChaudhary01** [comment]
$('.demo').addClass('ready');

are you talking about this?

**Comment by thedustinsmith** [comment]
What does your css for the `ready` class look like?

**Comment by SanketChaudhary01** [comment]
NO. I haven't written any CSS for ready class.

**Comment by thedustinsmith** [comment]
This screenshot that you posted is very clearly in a modal: https://cloud.githubusercontent.com/assets/18378020/26617456/ec52208e-45f2-11e7-94f5-a35b0200d6b2.png.

Maybe a link to your site or a more complete jsfiddle would help.

In the mean time if you want some additional resources: 
https://github.com/Foliotek/Croppie/issues/61
https://github.com/Foliotek/Croppie/issues/21

**Comment by SanketChaudhary01** [comment]
Yes, I am using [mdl](https://getmdl.io/components/index.html) dialogs for the modal box.
I have updated the link. You can have a look at it.
https://jsfiddle.net/godara01/k1m73bwu/#&togetherjs=1AM0PlGP5k

**Comment by SanketChaudhary01** [comment]
@thedustinsmith Thank you, sir, for all your help and time. I finally figured it out. I just needed to add the EXIF js to my script and enable it.
All is working fine now.
Thank you. :)

**Comment by AJ-TechSoul** [comment]
@thedustinsmith 
I was having the same issue of blank image in safari. I tried finding out where is the fault and found in mobile IOS and safari the exif doesnt work perfectly which they didnt fix yet. there was no problem with croppie.js 
I made false the exif and guess what!!! it worked !!! :1st_place_medal:  
So this small tweak fixed it.
  
 `  enforceBoundary: true,
  enableExif: false,`

**Comment by ddonuts** [comment]
I'm having the same problem as @Jabinc :
On safari (mobile), when the user does not apply any zoom to the image, `croppie.result({ type: 'base64', size: 'original' }).then(function(url) {` receives a black image.
If the users changes the zoom, the received image is correct...

Any news / solution on this issue ?

**Comment by thedustinsmith** [comment]
I'm closing this issue as it's gathering too many different bugs.  If this issue persists for anyone, feel free to open it up in a new issue with a jsbin/codepen of your specific issue.

**Comment by tpneumat** [comment]
I fixed my issue with this.   

`self.__cheer_croppieObj.croppie('result', {
                        type: 'base64',
                        format: 'jpeg',
                        size: {width:600},
                        quality: .9,
                        **backgroundColor:'#fff'**
                    }).then(function (base64) {`

**Comment by Panksi** [comment]
@thedustinsmith 
You can see the crop here, and I get the same result when used in our app.
So basically what happens is, when you upload too wide image, and rotate it, than somehow calculation of position of the cropped area is not doing its job well.

to reproduce the problem you can go to this codepen:
https://codepen.io/cromartie/pen/mWoovd

and then just include any wide image you have (lets say ratio 2:1 or even more).

![image](https://user-images.githubusercontent.com/16855132/64544023-8c71d880-d326-11e9-8a72-79ce9daaf1bf.png)


Hope this helps
