### ISSUE TITLE
IndexSizeError: Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by coyarzun2013** [Foliotek/Croppie#114]
trying to implement croppie to my site and suddenly start to crash.

first: uncaught exception: out of memory
and then IndexSizeError: Index or size is negative or greater than the allowed amount

this is my code to initialize croppie

`var $uploadCrop;

    function readFile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();          
            reader.onload = function (e) {
                result = e.target.result;
                arrTarget = result.split(';');
                tipo = arrTarget[0];
                if (tipo == 'data:image/jpeg' || tipo == 'data:image/png') {
                    $uploadCrop.croppie('bind', {
                        url: e.target.result
                    });
                    $('.upload-demo').addClass('ready');
                } else {
                    alert('jpg or png only');
                }
            }           
            reader.readAsDataURL(input.files[0]);
        }
    }

    $uploadCrop = $('#upload-demo').croppie({

        viewport: {
            width: 200,
            height: 200,
            type: 'circle'
        },
        boundary: {
            width: 220,
            height: 220
        }
    });

    $uploadCrop.croppie('bind',{
        url: $('#imgurl').val()
    });

    $('#upload').on('change', function () { readFile(this); });`

and when i try to submit the form 

`function sendForm(){
        $uploadCrop.croppie('result', {
            type: 'canvas',
            size: 'viewport',
            quality: 0.8
        }).then(function (resp) {
            $('#imagebase64').val(resp);
            $('#adminpers').submit();
        });
    }`

appreciate any help.

**Comment by thedustinsmith** [comment]
I know it's been a while and I haven't responded.  If you'e still having this issue can you throw together a jsbin/jsfiddle to demonstrate your issue?

**Comment by PratibhaP** [comment]
I am having same issue... is there any solution for it.

**Comment by thedustinsmith** [comment]
@PratibhaP If you throw an example on jsbin/jsfiddle, we can definitely come up with a solution.  As it is, I can't replicate the error with the above code.

**Comment by Konsultea** [comment]
Hi, 

I have same error, when trying to call result...
at line 618 all variables h,p,d,ù,f,v,g,w are set to zero for info.
Any solution was found on this?
Thanks
