### ISSUE TITLE
Bug on 2.1.0 update

### ISSUE THREAD

**Issue by geraldarcega** [Foliotek/Croppie#117]
There's a bug on uploading image. You cannot see the image that you've chosen. 

See screenshot from your demo page.

![screenshot 16](https://cloud.githubusercontent.com/assets/2818958/14413324/2d6aa47e-ffa9-11e5-874e-cb6ef477b2db.png)

**Comment by erperejildo** [comment]
I'm not sure if this issue is related with mine or not but I see a empty image the first time, I mean:
- Reload
- Add image
- Empty
- Add the same image or a different one
- Perfect
