### ISSUE TITLE
Unable to move image when zooming in and the 'crop area' goes outside of the image

### ISSUE THREAD

**Issue by Haydzyo** [Foliotek/Croppie#120]
Hi, I'm having issues when a user zooms into a smallish image. If when you zoom & the image lands outside of the crop area you will be unable to move the image left so it's stuck on the side of the crop area (see below for video).

http://thepilotslife.com/videos/croppie-issues.mp4

Have you come across this before? My temp fix was to remove the boundaries and allow the user to scroll anywhere but this has lead to users cropping none of their image and returning a blank image :)!

Cheers

**Comment by thedustinsmith** [comment]
Something weird is definitely happening at the 2 second mark in your video where your image just suddenly shifts left.  

It kind of looks like you're cropping inside of a modal, just double checking, are you calling bind after your modal is shown?

Any way you can share a code sample of how you're using croppie?

**Comment by Haydzyo** [comment]
Hi Dustin, thanks for the response.

I've put my code snippet on pastebin -> http://pastebin.com/1kCgzC8V

The croppie is NOT placed inside of a modal, it's simply displayed on the first page load. You can also see this page on our dev server (futureblossomapp.devdp.com, follow the sign up process to just after you upload an image).

Cheers!

**Comment by thedustinsmith** [comment]
It seems like you've modified some of the `croppie.css` - your `.cr-boundary` for example has a `width: 100% !important`.

I see you've made some padding and margin changes in there, those should be fine, but that width might be what's causing your problem.  Can you try removing that and seeing if it fixes your problem?

**Comment by Haydzyo** [comment]
Hi Dustin,

Ahh yes! it looks like that's what was causing the issue. I have removed the 100% width and it is now working as it should :).

Cheers,
Hayden

**Comment by smartit01** [comment]
Try setting css transition: unset!important; for  .croppie-container .cr-image. this solved the issue for me.
transition was applied to image by
 *, *:before, *:after {
     transition: all 0.3s ease-in-out 0s; 
}
which was the main issue.
