### ISSUE TITLE
White or No image on mobile chrome upload

### ISSUE THREAD

**Issue by geraldarcega** [Foliotek/Croppie#121]
Hi! I'm trying to upload an image to the demo site using Chrome in my Android phone but I'm getting white or no image after uploading the image

**Comment by thedustinsmith** [comment]
Duplicate of #117.

I commited the code into master, but then got sidetracked as I was merging it to the gh-pages branch. 

Sorry about that.  It's fixed on the demo site now.

**Comment by geraldarcega** [comment]
Great! thanks!
