### ISSUE TITLE
Save to server

### ISSUE THREAD

**Issue by jspurck** [Foliotek/Croppie#126]
I finally have a fully working script, but was wondering how to save the results to the server as a file. I have spent all day working on this and getting nowhere. I was on one that was close but then it came down to it was saving an actual CANVAS element. But here we are using a DIV as a Canvas or it seems. Is there anyway you can share a simple way to save results as a file to a directory on the server? I noticed in a blog-like post someone said your next post would be regarding saving to server.

**Comment by thedustinsmith** [comment]
It really depends on what server language you're using, but all languages should have the ability to save that base64 encoded image as a file on your server.

For example, if you're using PHP, you just send the response from `croppie.result({type: 'canvas'})` to your server.  Then you can save it using the following help:
http://stackoverflow.com/questions/11511511/how-to-save-a-png-image-server-side-from-a-base64-data-string

I've been meaning to write a blog post about saving base64 images, since a lot of requests have to deal with that, but I haven't gotten around to it yet.

**Comment by jspurck** [comment]
Thanks for the quick response! I will look into this. I was planning on using PHP.

**Comment by jspurck** [comment]
I am trying to manipulate the following code from Upload demo ...

 $('.upload-result').on('click', function (ev) {
        $vanilla.croppie('result', {
            type: 'canvas',
            size: 'original'
        }).then(function (resp) {
            $('#imagebase64').val(resp);
            $('#form').submit();
        });
    });

using the following form inputs ...

<form action="test-image.php" id="form" method="post">
<input type="hidden" id="imagebase64" name="imagebase64">
<a href="#" class="upload-result">Send</a>
</form>

test-image.php is ...

<?php
    if(isset($_POST['imagebase64'])){
        $data = $_POST['imagebase64'];

        list($type, $data) = explode(';', $data);
        list(, $data)      = explode(',', $data);
        $data = base64_decode($data);

        file_put_contents('image64.png', $data);
    }
?>

I borrowed this from http://stackoverflow.com/a/34623950/1618085. I am trying to strip out the upload feature which I do not need and it just will not work without the upload feature. I just don't know enough of Javascript yet to be successful.

**Comment by thedustinsmith** [comment]
If I understand you correctly, I think you'll just want to call 
```
croppie.bind({url: 'your/static/img/path.png'})
```
Then keep that button click event `$('.upload-result').on('click', function (ev) {});` and you should be good.

**Comment by jspurck** [comment]
GOT IT! 
```
$( document ).ready(function() {
    vanillaRotate = document.querySelector('.vanilla-rotate');
    var $uploadCrop = $('#upload-demo');
        $uploadCrop.croppie({
            viewport: {
                width: 250,
                height: 250,
                type: 'square'
            },
            boundary: {
                width: 300,
                height: 300
            }
        });
        $uploadCrop.croppie('bind', 'imgs/cat.jpg', '', 4);
        vanillaRotate.addEventListener('click', function() {
        vanilla.rotate(parseInt($(this).data('deg')));
        });
    $('.upload-result').on('click', function (ev) {
        $uploadCrop.croppie('result', {
            type: 'canvas',
            size: 'original'
        }).then(function (resp) {
            $('#imagebase64').val(resp);
            $('#form').submit();
        });
    });
});
```
HTML body ...
```
<form action="test-image.php" id="form" method="post">
<div id="upload-demo"></div>
<input type="hidden" id="imagebase64" name="imagebase64">
<a href="#" class="upload-result">Send</a>
</form>
<button class="vanilla-rotate" data-deg="-90">Rotate</button>
```
test-image.php ...
```
<?php
    if(isset($_POST['imagebase64'])){
        $data = $_POST['imagebase64'];

        list($type, $data) = explode(';', $data);
        list(, $data)      = explode(',', $data);
        $data = base64_decode($data);

        file_put_contents('image64.png', $data);
    }
?>

Now the rotate function is not working and I am trying to fix it. Seem to not know how to include the orientation configs in this setting which is different than the demoUpload where it is illustrated. But at least the saving to the server works great.
```

**Comment by pray4snow2** [comment]
jspurck,

What does your js and html final code look like? I have the same issue as you and I have tried the answers here but it still doesn't seem to work. I just need a clean sample of what the end code was? Can you help?
