### ISSUE TITLE
Request a feature: need new "reset" method for croppie.

### ISSUE THREAD

**Issue by yamilovs** [Foliotek/Croppie#127]
Hello! 
First i want to say thanks for your work! It's realy great!

In one of our projects we build a module (with croppie) that handle a user picture upload function. And we would be very useful if we has a "reset" method out from a box.

Its must revert croppie to its default state. Its useful when user want to upload new picture or delete a current. Now we do it like this - $('.cr-image, .cr-overlay').removeAttr('style src');

But i think it would be better if this opportunity was in the croppie itself. 

I'm not so good in JS (and in english i think) as i want to be, but i can buy you a beer if you want =)

**Comment by thedustinsmith** [comment]
Hmm - I haven't seen too many people showing a croppie instance without an image inside of it.

Out of curiosity, how would the feature you're requesting perform differently than `croppie.bind({url: ''})`? (passing an empty string as the url)

**Comment by yamilovs** [comment]
Thanks for so fast reply! Yes, your solution is better then our removing attributes.
I just checked it, and it is work correctly.
Thanks for this solution and this project! Yay!
