### ISSUE TITLE
How to add rotation to "demoUpload" version

### ISSUE THREAD

**Issue by jspurck** [Foliotek/Croppie#128]
I am having difficulty adding the rotation from Vanilla Demo to the Upload Demo. There seems to be another JavaScript syntax being used which "appears" to require a slightly different rotate written script?

**Comment by thedustinsmith** [comment]
Did you set `enableOrientation: true` when initializing the croppie?

**Comment by jspurck** [comment]
I didn't know how to add it to this syntax, so I enabled it by default in croppie.js.

**Comment by thedustinsmith** [comment]
Can you explain the troubles that you're having?  Provide some code?  I'm not sure what the problem is.

**Comment by jspurck** [comment]
Sure ... I am pretty much using UploadCrop demo's script as you see below.

```
$( document ).ready(function() {

    var $uploadCrop = $('#upload-demo');

        $uploadCrop.croppie({
            viewport: {
                width: 450,
                height: 450,
                type: 'square'
            },
            boundary: {
                width: 500,
                height: 500
            }
        });
        $uploadCrop.croppie('bind', 'demo/cat.jpg');

        $('.vanilla-rotate').on('click', function(ev) {
            vanilla.rotate(parseInt($(this).data('deg')));
        });

    $('.upload-result').on('click', function (ev) {
        $uploadCrop.croppie('result', {
            type: 'canvas',
            size: 'original'
        }).then(function (resp) {
            $('#imagebase64').val(resp);
            $('#form').submit();
        });
    });

});
```
The button is ...
`<button class="vanilla-rotate" data-deg="-90">Rotate</button>`

**Comment by jspurck** [comment]
Didn't know if you were able to look into this. I have provided the source above.

**Comment by thedustinsmith** [comment]
Oh sorry, overlooked this one.

The difference is you're initializing croppie with jquery.  So you'll want to execute the rotate method with jquery, like so:

`$uploadCrop.croppie('rotate', parseInt($(this).data('deg')));`

**Comment by jspurck** [comment]
That did it! I knew it was that line. Just didn't know enough but tried everything. Thanks again!!

**Comment by thedustinsmith** [comment]
No problem!

**Comment by Naren-hybreeder** [comment]
Where did you add that code? Please help me I am also getting the same issue.

**Comment by lminhphuongtma** [comment]
That work for me ! try it
//html
`<button type="button" id="rotateLeft" data-rotate="-90"></button>`
//javascript
'$( "#rotateLeft" ).click(function() {
                $uploadCrop.croppie('rotate', parseInt($(this).data('rotate')));
  });'

**Comment by Naren-hybreeder** [comment]
I got a reply after six months.hahahaha

Thanks lminhphuongtma,

**Comment by Ahmed-Mechrir** [comment]
it's work, thanks @lminhphuongtma
