### ISSUE TITLE
Bad Speed Processing Images

### ISSUE THREAD

**Issue by mgarciag** [Foliotek/Croppie#129]
Hi,

Thanks by your API, it is excelent but i have a problem, when load an image, is very slow to move and scrolling into the image, the image size is 650 KB aproximately, i want know if this bug is by the image weight. Validating console by the browser, say me: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/", it is by an bad implementation of the API?.

Excuse me for my english, i do not speak  english :P

Regards from Bogotá, Colombia,

Mauricio

**Comment by thedustinsmith** [comment]
Are you getting these speed problems on your own site?  Can you try uploading that same image [here](http://foliotek.github.io/Croppie/) and see if you get the slowness?
