### ISSUE TITLE
Bind doesn't work

### ISSUE THREAD

**Issue by victorluckwu1** [Foliotek/Croppie#130]
Hi, i'm trying to use cropping in my project but i'm getting some problems.

When loading croppie in a <img> with predefined URL, like: "test/test.png" it works fine and i can take the dataURL of the cropped image, to save in my database.

But when i try to put the dataURL of an image taken from an input file to crop, I can't load croppie to crop the image. I've tried to load in a modal and out of it, and both failed.

when i call $("#img").croppie("bind",{options}) it does nothing.

if someone can help me i'll be very thankful!

thanx..

**Comment by thedustinsmith** [comment]
Binding to dataUrl's should work just the same as a any other image source.  What happens when you try to do `$('<img />').appendTo('body').attr('src', dataUrl)`?

If you can provide some code, it would give us a better idea of where your problem is originating.

**Comment by victorluckwu1** [comment]
When i do this, the `<img>` is appended to the body.. It works fine.
The problem is when i try `crop.croppie('bind',{url: dataURL});`

Here goes my code:

- HTML

```html
<input type="file" class="input_file" id="input_file1" name="input_file1" onchange="getDataURL(event,'foto1'); muda_texto('1');">

<div class="input_area">

    <div class="input_new" onclick='$("#input_file1").click();'>
        <img src="" class="" id="preview_foto1">
    </div>

    <div class="file_name" onclick='$("#input_file1").click();'>
        <p align="center" id="nome_foto1"></p>
    </div>

    <a href="#" onclick="limpar_imagem(1);"><img src="design/icones/close.png" height="15px" width="15px" class="imagem" /></a>

</div>
```

- JavaScript

```javascript
var crop = $('#modalCrop1');

    function initCrop()
    {
        crop.croppie({
            boundary: {
                width: 800,
                height: 800
            },
            viewport: {
                width: 500,
                height: 500,
                type: 'square'
            },
            customClass: ''
        });
    }

    function getDataURL(event, id_input)
    {
        var id_preview = "#preview_"+id_input;
        var input = event.target;
        var reader = new FileReader();

        reader.readAsDataURL(input.files[0]);
        reader.onload = function(){
            var dataURL = reader.result;
            document.getElementById(id_input).value = dataURL;
            $(id_preview).css({
                "padding-top": "2px",
                "padding-left": "2px",
                "width": "185px",
                "height": "126px",
                "border-radius": "10px"
            });
            $(id_preview).attr("src", dataURL);

            $("#modalCrop1").attr("src", dataURL);

            $(".modal").toggle();

            crop.croppie('bind',{url: dataURL});
        };
    }

    $(".basic-result").on("click", function(){
        crop.croppie('result', {
            type: 'canvas',
            size: 'viewport'
        }).then(function(resp){
            $("#preview_foto1").attr("src", resp);
            $("#foto1").attr("value", resp);
            alert(resp);
        });
    });

    $(document).ready(function(){
        initCrop();
    });
```
The image i want to crop should open in a modal.
I've been tried to do many things to fix this, like set the `src` of the image i want to crop `$("#modalCrop1").attr("src", dataURL)` after toggling the modal, or call bind `crop.croppie('bind',dataURL);` instead of `crop.croppie('bind',{url: dataURL});`, but nothing made this work.

**Comment by thedustinsmith** [comment]
Sorry for the long delay in response.  Your code seems like should work.  Were you ever able to get it working?

If not, what browser are you using?  Where's your `#modalCrop1` element?  Does it work when you don't have it in a modal?  I would start eliminating things that you're doing differently than the upload demo in https://github.com/Foliotek/Croppie/blob/master/demo/demo.js and that should help you track down where your problem is coming from.

**Comment by Ariestattoo** [comment]
if #modalCrop1 is an img...it won't bind based on my experience. After changing it to a DIV, I was successful.

**Comment by thedustinsmith** [comment]
Good point @Ariestattoo .  I've contemplated making croppie allow an image in it's constructor, and then get the data from that image to create the croppie instance.

Just haven't gotten around to it yet.

**Comment by Ariestattoo** [comment]
Great plugin either way...thanks for the effort :)

**Comment by thedustinsmith** [comment]
#210

Closing this one
