### ISSUE TITLE
Crop image based on defined svg or png mask?

### ISSUE THREAD

**Issue by power7714** [Foliotek/Croppie#131]
Is it possible to crop an image using a predefined image shape from an svg or png file? So rather than crop the image as a circle or square, I would like to crop the image to look like a cup or a car. How would I go about doing this?

**Comment by thedustinsmith** [comment]
In short, not with croppie.  I believe you can do css clipping with svg paths, but I haven't done so myself, and the browser support is limited (http://caniuse.com/#feat=css-clip-path).
