### ISSUE TITLE
Resize according to container when image is loaded already?

### ISSUE THREAD

**Issue by JimmyMultani** [Foliotek/Croppie#137]
I'm having a really hard time figuring out how to make this plugin fit its container element when I'm resizing the browser. I have it setting the viewport and boundary on load, but that's pretty much it.

``` js
$('.croppie__tool').croppie({
    viewport: {
        width: cropWidth,
        height: cropHeight,
        type: 'square'
    },
    boundary: {
        width: columnWidth,
        height: 230
    },
    exif: true,
    showZoomer: false
});
```

Any assistance would be greatly appreciated. Thanks!

**Comment by thedustinsmith** [comment]
I think we're missing a feature that you need.  A while ago, we decided it wasn't worth the effort to make options configurable after initialization.  For example, with typical jquery plugins, you would say `$('.my-el').croppie('option', 'viewport.width', 300)` or something along those lines.

Instead, we decided to just destroy croppie instances, and reinitialize them.  So you should be able to call `$('.croppie__tool').croppie('destroy')` and then initialize again with your new dimensions (and bind data).

I'm guessing this isn't going to be very efficient for you, but it will at least give you something to get started.

**Comment by vivekRudiment** [comment]
I am able to crop images from 50K to 10 mb with no problem. When I transfer the trigram to the VPS server at Hostgater, The cropping process never finishes. The “ bubbles” never stop. 
I configer the following setting on my VPS Server 
max_execution_time => 300,
memory_limit => 1000,
post_max_size => 1000,
max_input_time=>60 
any thing else i missed please help. 
check the problem on following link https://www.boats4sale.com/b4sell/individual/dashbaord/editListing/684
 username => Ajay@1234567890 ,password => Ajay@1234567890 what kind of setting require for big images crop on server please help
