### ISSUE TITLE
Upload doesn't work if filename contain "+"

### ISSUE THREAD

**Issue by YokiToki** [Foliotek/Croppie#138]

**Comment by thedustinsmith** [comment]
Works for me.  Do you have any more information?  What browser?  What OS?  What's the file name you're using?

**Comment by YokiToki** [comment]
Chromium 49.0.2623.108 Built on 8.3, running on Debian 8.4
Filename: CTRL+W Please.jpg
I use this http://foliotek.github.io/Croppie/ example

**Comment by thedustinsmith** [comment]
I would guess that this is something wrong with your image, not the file name.  Can you upload this image elsewhere?  This comment thread, perhaps?
