### ISSUE TITLE
Black border after uploading and moving a photo all to the left bottom

### ISSUE THREAD

**Issue by basvandertogt** [Foliotek/Croppie#145]
When uploading and moving a photo all to the left bottom it's showing a black border on the right side after cropping the image. Does anybody know how to fix this?

Demo: http://bcme.hyperconnected.nl

Using
iPhone 6 iOS 9.3.2
Croppie 2.1.1

**Comment by thedustinsmith** [comment]
When I remove the rotation from your wrapping element, and then drag the image to the bottom left the black border goes away.

**Comment by basvandertogt** [comment]
Oh wow you're right!
