### ISSUE TITLE
Warning 'unreachable code after return statement'

### ISSUE THREAD

**Issue by doormalena** [Foliotek/Croppie#147]
See following code snippit

```
function _initRotationControls () {
        // TODO - Not a fan of these controls
        return; // <-- issue starts here
        var self = this,
            wrap, btnLeft, btnRight, iLeft, iRight;
        ...
```

**Comment by thedustinsmith** [comment]
Yep - I'm aware of that code.  I started to include rotation buttons in the default interface for croppie, but didn't like how they were turning out.  If that warning is bugging you, you can remove that code.
