### ISSUE TITLE
Crop transparent on iOS when moving photo

### ISSUE THREAD

**Issue by basvandertogt** [Foliotek/Croppie#149]
Hello,

I'm facing a serious problem where the crop is not working on Safari (iOS & desktop) when dragging a uploaded photo inside the canvas. When leaving the photo as it is (don't move it). The crop is successful. I don't have this problem in other browsers. Has anyone else had this problem before?

Regards,
Bas

**Comment by f1982** [comment]
I got this issue also. can this bug be fix?

**Comment by thedustinsmith** [comment]
I can try to replicate it next time I'm on my mac, but what exactly is the problem?  The original description isn't very helpful.  "Not working" can mean several different things.
