### ISSUE TITLE
Image stuck after zooming into corner and zooming out

### ISSUE THREAD

**Issue by VADS** [Foliotek/Croppie#152]
Reproduction:

I used the image on the [official croppie site](http://foliotek.github.io/Croppie/) but was also able to reproduce the bug locally (using Chrome, Version 51.0.2704.84 m, also reproducable on Firefox 46.0.1)

Zoom into lower right-hand corner
![image](https://cloud.githubusercontent.com/assets/1810902/15965621/4e0ac65a-2f1f-11e6-84f6-35f71f0ae413.png)

Zoom out
![image](https://cloud.githubusercontent.com/assets/1810902/15965630/6327d50a-2f1f-11e6-960f-760a83e9c1b9.png)

Image is now stuck and cannot be moved around (Zooming around will unstick it)
![image](https://cloud.githubusercontent.com/assets/1810902/15965645/8c34473a-2f1f-11e6-8627-cb418b9e471b.png)

**Comment by thedustinsmith** [comment]
Thanks for the submission - good catch on this.  I'll try to look into this asap.

**Comment by bionetmarco** [comment]
Hey Dustin, any updates on this?

**Comment by thedustinsmith** [comment]
I've tracked it down to the block of code that's causing the issue.  Unfortunately, the logic is a little tough to debug, and I didn't get a lot of time last week.  This week looks better as far as time for me.  I'll post updates on here as soon as I have them.  Sorry about the delay.

**Comment by VADS** [comment]
Great, that fixed it for me! Thank you :)

**Comment by thedustinsmith** [comment]
Thanks for confirming for me!
