### ISSUE TITLE
Landscape version

### ISSUE THREAD

**Issue by erperejildo** [Foliotek/Croppie#153]
I'm working with landscape images, could I crop them up like this?
https://jsfiddle.net/Xiwi/c4ku3551/

Extra: could I fill the empty gaps with some colours to generate the landscape version in a square?

**Comment by thedustinsmith** [comment]
If you use the `enforceBoundary` parameter when initializing your croppie, that'll get you close, but I don't think it'll be exactly what you want.  

For the functionality you desire, seems like we need a `enforceXBoundary` `enforceYBoundary` or something along those lines.

**Comment by erperejildo** [comment]
Well, I've been dealing with this until now. So far, these are the results:
Landscape:
https://dl2.pushbulletusercontent.com/s0n6qd2ZJhpux3lLRTPJT7NNi4bw0yaN/Screenshot_2016-06-17-00-18-00.png
https://dl2.pushbulletusercontent.com/7jnNIKaiPQJRoI8FebJ9TlhCpW1G3dpL/Screenshot_2016-06-17-00-18-33.png

Portrait:
https://dl2.pushbulletusercontent.com/YXvo18K0s86cRJ4zj5qOUqLh7ettrOZe/Screenshot_2016-06-17-00-18-10.png

As you can see, depending of the image size, we can still zooming the picture.

To ability this I've created another option called `largeMode` (default as false). Obviously, if we've got `enforceBoundary` as false in our croppie element as well won't work because is less important.

Yo don't have to specify if the picture is landscape or portrait.

This is the code:
https://codeshare.io/4LXCI

I need to do more test but so far I've have good results.

**Comment by erperejildo** [comment]
I'm fixing right now the black gap after cropped it. The picture is not centered

**Comment by erperejildo** [comment]
Done!
Updated code (same url always):
https://codeshare.io/4LXCI

How to use it:
```
var opts = {
      largeMode: true,
      gapsColor: 'green' // you could use #XXX (#fff by default)
      viewport: {
        width: 200,
        height: 200
      }
    };
```

**Comment by erperejildo** [comment]
I just realized when I crop the large image with zoom 100% (small picture) the gap size in the image converted is smaller.

**Comment by erperejildo** [comment]
Fixing right now the cropped image, should be a square but it's not

**Comment by thedustinsmith** [comment]
Glad you got something working.  Seems like a lot of people are requesting something like this.  I'm going to close this case in favor of #207, but I might reference your code for some help on that one.

Thanks.

**Comment by erperejildo** [comment]
Great.
Glad to help.
