### ISSUE TITLE
Why doesn't get() method return information about rotation

### ISSUE THREAD

**Issue by k-lusine** [Foliotek/Croppie#154]
Hi thanks for the great update to support rotation. 

I really need to get information about rotation?

And one more question. Can I set rotation in degrees when "binding"?

Thanks, Lusine

**Comment by mgiulio** [comment]
Hi @k-lusine , maybe this quick patch could help:


[patch.txt](https://github.com/Foliotek/Croppie/files/329562/patch.txt)

**Comment by thedustinsmith** [comment]
@k-lusine - no you can't set rotation in degrees when binding.  You can set the `bind({orientation: x})` to the following values to achieve a rotation:

```
orientation: 6 //90 degrees clockwise rotation
orientation: 3 //180 degree rotation
orientation: 8 //270 degree clockwise rotation
```

The reason for this seemingly odd way to do rotation is that is how `exif` represents those rotations.  So we're piggy-backing off exif to achieve our rotation logic.

It's also the same reason we're not including orientation data in the `get()` method.  While I like @mgiulio's patch, I think there's a few other edge cases that might go under the radar.

**Comment by k-lusine** [comment]
Thanks a lot for the answers, 
As I had just two buttons for rotating left or right, some custom code similar to @mgiulio 's patch worked for me, but I'm not sure it will work for all use cases

**Comment by mgiulio** [comment]
@k-lusine @thedustinsmith Yes, it was just a quick patch that worked in my own use case.
