### ISSUE TITLE
What file formats are supported by croppie.js?

### ISSUE THREAD

**Issue by MalgorzataKonarzewska** [Foliotek/Croppie#157]
I have to define what file-formats can I use with croppie.js.
Where can I find that information?
Please help, thank you!

**Comment by thedustinsmith** [comment]
It depends on how you're using Croppie.  If you're only doing the most basic of operations, and using the `result({type:'html'})`, technically any image that the browser supports is supported by Croppie.

If you're using rotation, exif, or `result({type:'canvas'})` you're going to be limited to what images can be drawn onto a canvas, which is going to depend on your browser.  Here a chart showing browsers' image formats supported: https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

To the best of my knowledge, the only result you can get if you're using `result({type: 'canvas'})` is a `jpg` or a `png`.  So even if you bind an animated `.gif` to your croppie, the canvas result will only be a  single frame of it, and converted to `jpg` or `png` (whichever you specify).

Hope that helps.

**Comment by giviz** [comment]
That's correct that croppie is not working with animated gif as it use only the first frame of the image.

Do you think there is any way that that limitation can be solved to provide the same functionalities but with an animated gif, having the gif running in the viewport and a cropped animated gif at the end result ?

If not, what are the main limitations that would prevent to do it ?

Thank you

**Comment by thedustinsmith** [comment]
Here at Foliotek we use [image resizer](https://imageresizing.net/), and we use the crop points generated from croppie.  As opposed to how I assume a bulk of croppie users are using it: getting the blob or the base64 image.

With ImageResizer, we pass the prop points via a query string parameter, and it allows us to crop animated gifs: https://imageresizing.net/docs/basics#cropping

**Comment by giviz** [comment]
Yeah, I was looking into that option, using the prop points and resizing with imagemagick.
I assume you also have to pass the zoom used too.

But even that way, the image displayed in croppie is static (only the first frame of the animated gif).
Do you think there is a way to have an animated gif displayed, in order to zoom properly on all frames as some of them may require a different zoom/crop to fit than the first frame would.

**Comment by thedustinsmith** [comment]
If your croppie instance matches these circumstances, croppie will draw the image to a canvas to crop it.  https://github.com/Foliotek/Croppie/blob/master/croppie.js#L325 ... which is why you're seeing only one frame.  Try disabling rotation and exif.

And no, the zoom does not need to be passed.  The points are calculated using zoom.

**Comment by giviz** [comment]
With the 2 options disabled, the gif is now animated in the canvas !

Thank you so much, you saved my day !

**Comment by giviz** [comment]
Using ImageMagick I have to process with the zoom first and then use the points to crop the image.
If I don't resize the original first and only apply a crop on the selection, it doesn't work at all.

Sadly, using the values croppie gives me, I do not get the proper selection.

As an example, I have an image where the results for an output of 150x150 are : 

0 : "104"
1 : "0"
2 : "524"
3 : "420"
zoom : 0.35714285714285715

So I process with a zoom of 35.714285714285715% of the original image and the result is an image that really looks like the one in croppie in term of dimensions.

# convert dlrktj.gif -resize 35.714285714285715% test.gif

That resized image is 224x150

Then I crop that image using the points 0 and 1 for an output of 150x150 : 

# convert test.gif -crop 150x150+104+0 +repage test.gif

But the thing is, the first point is 104 on the 224 of the resized image, so there is only 120 pixels left.
And I should perform a selection of 150 pixels there.

I've tried with various images (both gif and jpg) and various output size, but each time I have non working results where I have to adapt some points manually to get the valid selection (like here using 74 and not 104 for the first point).

Any idea what may cause that problem and how to solve it ?

Thanks a lot.

**Comment by thedustinsmith** [comment]
The crop points are points on the original image.  Try reversing your order of operations.  Crop, then resize.

**Comment by giviz** [comment]
If I crop first a 150x150 on the original image using the 104+0 points and then resize, I get a completely wrong result with pixels in the top left corner of the original image.

If I resize first and then crop at 150x150 on the resized image, I get a "closed to right" results with pixels in the right part of the image, but off by 10 to 30 pixels on the right for example.

Maybe it's an issue with the value of the zoom provide by croppie and the result I get when I resize with that value in percentage in imagemagick.

**Comment by giviz** [comment]
Ok I find what it is.

The points are based on the original image (ex : 100, 50, a, b)
The scale is based on the original image (ex : 1.5)

1) Resize the original image by 150%
2) Resize all points by 150%, so now (150, 75, a, b)
3) Crop the resized image using the resized points

And now it's working properly.

Again, thank you a lot for your help !

**Comment by rmiqbalramadhan** [comment]
in the documentation, there is this information
format Indicating the image format.
Default:'png'
Valid values:'jpeg'|'png'|'webp'

is webp format still available? I'm trying to try that format. I already search issue with keyword webp and none result. Am I missing something? Thanks you for your attention.

**Comment by fennellgb23** [comment]
> in the documentation, there is this information
> format Indicating the image format.
> Default:'png'
> Valid values:'jpeg'|'png'|'webp'
> 
> is webp format still available? I need that format for experimental purpose. I already search issue with keyword webp and none result. Am I missing something? Thanks you for your attention.
> 
> Here is my code :
> $('#upberita').on('click', function (ev) {
> $uploadCrop.croppie('result', {
> type: 'canvas',
> size: 'viewport',
> format: 'webp',
> quality: 1
> }).then(function (resp) {
> $('#hide').val(resp);
> $('#form').submit();
> });
> return false;
> });
> but it result in .jpeg instead of .webp

Did you ever find an answer?  I'm having the same problem, but only with Firefox, it works fine in Chrome.  I've searched for about a day and a half trying to find why it's doing this and have come up empty.  Do the Devs have an answer to this?

**Comment by thedustinsmith** [comment]
Sorry - I often miss updates on closed issues.

Croppie uses `<canvas />`'s `toDataURL()` method.  According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL, only chrome supports the webp format in this method.  I didn't realize that when the documentation was written.  

So to answer your question, yes it appears that webp only supported in Chrome.

**Comment by fennellgb23** [comment]
Well that stinks, but allows me to work on a workaround for this. Thanks for the quick response.

**Comment by gulbrillo** [comment]
I just tested Croppie successfully with AVIF ()AV1 Image File Format) on multiple browsers - while no HDR information is retained, it uses correct color grading information and the uploaded jpeg looks good.
