### ISSUE TITLE
Crash on Chrome mobile in _getCanvasResult

### ISSUE THREAD

**Issue by Hypher** [Foliotek/Croppie#161]
INDEX_SIZE_ERR: DOM Exception 1 on line 950:
`ctx.drawImage(img, left, top, width, height, 0, 0, outWidth, outHeight);`
Because it's out of bounds.
Seems like points can be naturally (i.e. before any user interaction) out of the image on large ones; note that I use `setZoom(0)` initially.

Adding the following before this line fixed the issue:

```
        // fix bounds
        if(left+width > img.width) {
            width = img.width - left;
        }
        if(top+height > img.height) {
            height = img.height - top;
        }
```

I suppose should also avoid negative `top` and `height`...

**Comment by thedustinsmith** [comment]
Thanks for the code.  I'm going to try to replicate this before I put the code in.

**Comment by cevantes** [comment]
have this problem too when zooming out to the max
