### ISSUE TITLE
Increasing the size of the zoom slider on mobile

### ISSUE THREAD

**Issue by tobeee** [Foliotek/Croppie#164]
Anyone had any luck increasing the size of the handle on the slider? It's a bit fiddly on mobile so any help would be great!

**Comment by someidiot** [comment]
Override the cr-slider class styles. There are several copies to handle different browsers but eg for webkit I use this:

.cr-slider::-webkit-slider-runnable-track {
    width: 100%;
    height: 10px;
    background: rgba(0, 0, 0, 0.5);
    border: 0;
    border-radius: 10px;
}
.cr-slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    border: none;
    height: 24px;
    width: 24px;
    border-radius: 50%;
    background: #8ab933;
    margin-top: -7px;
}
