### ISSUE TITLE
How to crop image and upload cropped image to a service?

### ISSUE THREAD

**Issue by raysefo** [Foliotek/Croppie#165]
Hello,
I am trying to take picture from IOS mobile device and use cropping feature then send cropped image to a web service. Is there any tutorial for this particular issue? Hope you can help me.

Best Regards.

**Comment by thedustinsmith** [comment]
It really depends on the webservice that you're working with.  Do you control this service?  If not, do they accept base64 images or just files?

Here's a pretty good example of someone placing a base64 image inside of a form, and submitting the form to a php server:
http://stackoverflow.com/a/34623950/1875969

If you're writing your own server, the code's going to change depending on the language that you're using.  There's several different ways to do the JS, but this one should get you going easily.

I've been meaning to write more blog posts on croppie and how to use it.  I just haven't gotten around to it yet.

**Comment by raysefo** [comment]
Hi,

Thanks for your reply. Actually I imğlemented a WCF service. Here is the service interface.
`[ServiceContract]
    public interface IOCRService
    {

        [OperationContract]
        [WebInvoke(Method = "POST", ResponseFormat = WebMessageFormat.Json, BodyStyle = WebMessageBodyStyle.Wrapped, UriTemplate = "/FileUpload")]
        string OCRImage(Stream fileStream);

and here is service portion:
` [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    public class LoTToOCR : IOCRService
    {
        Image<Gray, Byte> gray_image;
        Bitmap bmpImage;
        String ocrresult;
        String service_Result;

        public string OCRImage(Stream fileStream)
        {
            try
            {
                var FilePath = @"C:\upload\test.bmp";

                var length = 0;
                using (FileStream writer = new FileStream(FilePath, FileMode.Create))
                {
                    int readCount;
                    var buffer = new byte[8192];
                    while ((readCount = fileStream.Read(buffer, 0, buffer.Length)) != 0)
                    {
                        writer.Write(buffer, 0, readCount);
                        length += readCount;
                    }
                    bmpImage = (System.Drawing.Bitmap)Image.FromStream(writer);
                }

By the way I am implementin via VS 2015. I tested the service with console app, it is working but I am not sure how to make it work with js. Here is my index.html for mobile client:
`<body ng-app="starter">
    <ion-header-bar class="bar bar-header bar-light">
        <h1 class="title">LoTTo</h1>
    </ion-header-bar>
    <ion-content ng-controller="ExampleController" padding="true">
        <button class="button button-full button-balanced icon-right ion-ios-camera" ng-click="takePhoto()">
            Resim Çek
        </button>

        <button class="button button-full button-balanced icon-right ion-images" ng-click="choosePhoto()">
            Resim Seç
        </button>
        <center>
            <div class="cropArea">

                <img-crop image="myImage" result-image="myCroppedImage" chargement="'Loading'"
                          area-type="rectangle"
                          area-min-size="50"
                          result-image-format="image/jpeg"
                          result-image-quality="1"
                          result-image-size="{w:300, h:50}"></img-crop>

            </div>
            <div ng-show="myImage !== undefined">Gönderilecek Resim:</div>
            <div class="croppedArea"><img ng-src="{{myCroppedImage}}" ng-show="myImage !== undefined" id="image" /></div>


        </center>

        <button class="button button-full button-balanced icon-right ion-images" ng-click="upload(myCroppedImage)" ng-if="myImage !== undefined">
            Resim Yükle
        </button>


    </ion-content>

</body>

and here is app.js with ng-img-crop for cropping the image:
`angular.module('starter', ['ionic', 'ngCordova', 'ngImgCrop','ngFileUpload'])

.controller("ExampleController", ['$scope', '$cordovaCamera', 'Upload', '$timeout', function ($scope, $cordovaCamera, Upload, $timeout, $cordovaFileTransfer) {

    $scope.takePhoto = function () {
        var options = {
            quality: 100,
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: Camera.PictureSourceType.CAMERA,
            allowEdit: true,
            encodingType: Camera.EncodingType.JPEG,
            targetWidth: 300,
            targetHeight: 300,
            popoverOptions: CameraPopoverOptions,
            saveToPhotoAlbum: true
        };

        $cordovaCamera.getPicture(options).then(function (imageData) {
            $scope.imgURI = "data:image/jpeg;base64," + imageData;
        }, function (err) {
            console.log(err);
            alert(err);
        });
    }

    $scope.choosePhoto = function () {
        var options = {
            quality: 100,
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
            allowEdit: true,
            encodingType: Camera.EncodingType.JPEG,
            targetWidth: 300,
            targetHeight: 300,
            popoverOptions: CameraPopoverOptions,
            saveToPhotoAlbum: false
        };

        $cordovaCamera.getPicture(options).then(function (imageData) {
            $scope.imgURI = "data:image/jpeg;base64," + imageData;
            $scope.myImage = $scope.imgURI;

        }, function (err) {
            console.log(err);
            alert(err);
        });
    }


    $scope.myCroppedImage = '';

    //$scope.uploadFile = function () {

    //    var win = function (r) {
    //        console.log("Code = " + r.responseCode);
    //        console.log("Response = " + r.response);
    //        console.log("Sent = " + r.bytesSent);
    //    }

    //    var fail = function (error) {
    //        alert("An error has occurred: Code = " + error.code);
    //        console.log("upload error source " + error.source);
    //        console.log("upload error target " + error.target);
    //    }


    //    var url = encodeURI("http://192.168.1.23/wcf/upload/");
    //    //target path may be local or url
    //    var targetPath = $scope.myCroppedImage;

    //    var options = new FileUploadOptions();

    //    options.fileKey = "Lotto";
    //    options.fileName= "Lotto.jpg";
    //    options.chunkedMode = false;
    //    options.mimeType = "image/jpeg";
    //    var headers = { Connection: "close" };
    //    options.headers = headers;


    //    var ft = new FileTransfer();
    //    ft.upload(targetPath, url, win, fail, options);



    //}

    $scope.upload = function (dataUrl) {

        Upload.upload({

            //url: 'http://10.126.110.90/wcf/upload',
            url: 'http://192.168.1.20/wcf_test/OCRService.svc/FileUpload',
            data: {
                file: Upload.dataUrltoBlob(dataUrl)
            },

        }).then(function (response) {
            $timeout(function () {
                $scope.result = response.data;
                console.log(response.data);
                alert(response.data);
            });
            console.log(response.data);
        }, function (response) {
            if (response.status > 0) $scope.errorMsg = response.status
				+ ': ' + response.data;
            alert(response.status);
        });

    }


}]);

But somehow I couldn't upload image to the WCF.

`

**Comment by thedustinsmith** [comment]
Maybe I'm mistaken, but I don't see you using croppie anywhere in this code.  Maybe you're looking for this github repo instead? https://github.com/alexk111/ngImgCrop

**Comment by raysefo** [comment]
sorry I couldn't express it clearly. I tried the ng-img-crop repo in my example. I was wondering if I could use your crop repo, how can I implement my solution?

**Comment by thedustinsmith** [comment]
I hope you found some answers for this.  Sorry I couldn't be more help.  I don't have that much time to support this project.

If you're still looking for help, maybe stackoverflow would be a better place to ask for help.
