### ISSUE TITLE
Set viewport type to circle, but get square output

### ISSUE THREAD

**Issue by edagenais** [Foliotek/Croppie#166]
Is there a way to set the initial viewport to display as a circle but when getting the result, have it produce a square version of the image?

**Comment by thedustinsmith** [comment]
Yep - but I don't think it's documented.  https://github.com/Foliotek/Croppie/blob/master/croppie.js#L1050

`$('#my-crop').croppie('result', { circle: false, type: 'canvas' });`

**Comment by edagenais** [comment]
Amazing! You just made my day @thedustinsmith.

**Comment by zaratedev** [comment]
Perfect just what I needed. Thank you @thedustinsmith

**Comment by justicemilitia** [comment]
Thanks

**Comment by bokac91** [comment]
Thank you Dustin, this helped me a lot!

**Comment by fcorbeil** [comment]
Hi,
I have tried using the following :
`$('#my-crop').croppie('result', { circle: false, type: 'blob' });`
Seems like circle false is ignored when using type blob.  Am I missing something?
Thanks!

**Comment by devndhjs** [comment]
> Yep - but I don't think it's documented. https://github.com/Foliotek/Croppie/blob/master/croppie.js#L1050
> 
> `$('#my-crop').croppie('result', { circle: false, type: 'canvas' });`

thanks alot, you save my day
