### ISSUE TITLE
Mask around the visible part of the image doesn't work on iPhone 

### ISSUE THREAD

**Issue by VetrivelKS** [Foliotek/Croppie#167]
.croppie-container .cr-viewport {
	position: absolute;
	border: 2px solid #fff;
	margin: auto;
	top: 0;
	bottom: 0;
	right: 0;
	left: 0;
	box-shadow:0 0 0 899px rgba(0, 0, 0, 0.5);  
//here the shadow spread 889px doesn't work on iPhone device.. It worked when I reduced it to 550px
	z-index: 0;
}

![img_0802](https://cloud.githubusercontent.com/assets/9497377/16830166/d9d21764-49ba-11e6-93d5-16f520512b23.PNG)

**Comment by thedustinsmith** [comment]
Thanks for the submission.  If I change that box shadow to be 550px - it's going to break any croppie's that have boundaries > 550px.  I'm thinking we may have to come up with another solution for the overlay.  I don't know why safari doesn't like box shadows, but it's a tad frustrating (see #32)

**Comment by ice8lue** [comment]
I would suggest two fixes here (which we use in production now):

`

/* to fix the mask */
.croppie-container .cr-viewport {
  box-shadow: 0 0 2000px 2000px rgba(0, 0, 0, 0.5);
}

/* for general performance improvements, specially on mobile devices*/
.croppie-container .cr-image,
.croppie-container .cr-overlay, 
.croppie-container .cr-viewport {
  -webkit-transform: translateZ(0);
  -moz-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
}

`

**Comment by thedustinsmith** [comment]
@ice8lue Thanks for the details.  I'm curious how you landed on `2000px 2000px` for the box shadow.  Does that work in safari? 

I like the idea to `translateZ(0)` for performance improvements.  Thanks for the comment.

**Comment by ice8lue** [comment]
@thedustinsmith It works, yes. The 2000px value was to be prepared for very high resolution screens, you'd probably only need 1000px for now. To fix the Safari bug, it's important to set both values, blur and spread to the desired value as there seems to be a rendering glitch with calculating blur for such a large distance.

**Comment by thedustinsmith** [comment]
Good to know.  Thanks for the info!
