### ISSUE TITLE
Opacity set to 0

### ISSUE THREAD

**Issue by cannond13** [Foliotek/Croppie#175]
In croppie.js, in the loadImage method, why is `img.style.opacity` set to 0 on line 147?  I manually updated it to 100, and now my images appear.

**Comment by thedustinsmith** [comment]
I couldn't tell you why exactly.  I'm guessing we were going for the fade in effect looking https://github.com/Foliotek/Croppie/blob/master/croppie.js#L796.

I'd be surprised if everything else works as expected if `updatePropertiesFromImage` isn't working for you.

**Comment by cannond13** [comment]
Ha, you're right, it's not working as expected, I just posted another issue.  Thanks for the response, the manual change to 100 opacity seems to resolve this issue.
