### ISSUE TITLE
QUESTION - Should we allow scroll zoom if we don't "showZoom"

### ISSUE THREAD

**Issue by thedustinsmith** [Foliotek/Croppie#18]
We only initialize the zoom logic if `showZoom` is true.  Should we initialize the zoom logic if `showzoom || mousewheelzoom`

**Comment by russ-ab** [comment]
Sure, and probably change the `showZoom` to `enableZoom`.

Add another option `showZoomSlider` to show/hide the slider if `enableZoom` is `true` but the user don't want to use the slider.

**Comment by thedustinsmith** [comment]
Yeah - I like these suggestions.  I can see the need to set the zoom programmatically in the future.
