### ISSUE TITLE
Can i maake it work in my Angular2 and Typescript project

### ISSUE THREAD

**Issue by waqarmahar** [Foliotek/Croppie#180]
When I install and try and import it in my typescript project
import { Croppie } from 'croppie';
it says cant find the module

**Comment by thedustinsmith** [comment]
I know next to nothing about typescript.  I also don't use angular.  If you can diagnose the problems and submit a PR for a fix, I'd be happy to merge it in, but I won't be of any help.

**Comment by thedustinsmith** [comment]
Closing this one in favor of #181's title
