### ISSUE TITLE
Croppie is not initializing the image on semantic ui popup

### ISSUE THREAD

**Issue by matavele** [Foliotek/Croppie#183]
I'm trying to crop images on popup, but  it's not initializing the image.

**Comment by thedustinsmith** [comment]
Can you share some code?  Are you intiializing the croppie instance after the popup is shown?

**Comment by matavele** [comment]
Yes, I Initialize the popup first here is the code.

`<!--View-->`
`<div class="demo " id="img_0101" ></div><!--On popup-->`
`<input type="file" accept="image/*"  onchange="angular.element(this).scope().init_photo(this)" ><!--On popup-->`

`<!--Controller-->`

`$scope.init_photo = function (input) {`
 `      if (input.files && input.files[0]) {`
`           var reader = new FileReader();`
           `reader.onload = function (e) {`
                 `$('#img_0101').croppie({`
                        `url: e.target.result,`
                        `boundary: {width: 250, height: 250},`
                        `viewport: {width: 150, height: 150}`
                  `  });`
            `};`
` reader.readAsDataURL(input.files[0]);`
` }`
` };`

**Comment by thedustinsmith** [comment]
I don't see where you're binding the croppie or where you're opening the dialog.  Those would be the important bits.

**Comment by matavele** [comment]
Here is all my code.
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/semantic.min.css">
        <script src="js/api/jquery-1.11.1.js"></script>
        <script src="js/api/semantic.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
        <script src="js/api/croppie.js"></script>
    </head>
    <body  ng-app="app"  ng-controller="basic">
        
        <div style="display: none" >
            <div id="div_0" style="width: 400px;height: 400px">
                <div class="demo " id="img_0101" ></div>
                <input type="file" accept="image/*"  onchange="angular.element(this).scope().init_photo(this)" >
            </div>
        </div>
        
        <button class="ui basic button small" style="margin-left: 300px;margin-top: 200px" id="btm">Show</button>
        
    </body>
    <script>
        var app = angular.module('app', []);
        app.controller('basic', function ($scope, $compile) {

            var html = $compile($("#div_0").clone())($scope);

            $("#btm").popup({
                on: 'click',
                closable: false,
                html: html,
                distanceAway: -50,
                variation: "basic"
            });

            $scope.init_photo = function (input) {
               
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        console.log("oo");
                        $('#img_0101').croppie({
                            url: e.target.result,
                            boundary: {width: 250, height: 250},
                            viewport: {width: 150, height: 150}
                        });
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            };
        });
    </script>
</html>

**Comment by matavele** [comment]
Here is all my code.

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/semantic.min.css">
        <script src="js/api/jquery-1.11.1.js"></script>
        <script src="js/api/semantic.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
        <script src="js/api/croppie.js"></script>
    </head>
    <body  >
        <div ng-app="app"  ng-controller="basic"> 
            <div style="display: none" >
                <div id="div_0" style="width: 400px;height: 400px">
                    <div class="demo " id="img_0101" ></div>
                    <input type="file" accept="image/*"  onchange="angular.element(this).scope().init_photo(this)" >
                </div>
            </div>

            <button class="ui basic button small" style="margin-left: 300px;margin-top: 200px" id="btm">Show</button>
        </div>   
    </body>
    <script>
        var app = angular.module('app', []);
        app.controller('basic', function ($scope, $compile) {

            var html = $compile($("#div_0").clone())($scope);

            $("#btm").popup({
                on: 'click',
                closable: false,
                html: html,
                distanceAway: -50,
                variation: "basic"
            });

            $scope.init_photo = function (input) {

                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#img_0101').croppie({
                            url: e.target.result,
                            boundary: {width: 250, height: 250},
                            viewport: {width: 150, height: 150}
                        });
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            };
        });
    </script>
</html>

**Comment by matavele** [comment]
Here is all my code.
https://gist.github.com/matavele/c9ca304b6ad392e0bdf6bb90e5ee9203

**Comment by thedustinsmith** [comment]
That seems like it should work.  Maybe there's some odd styling in the semantic popup that is messing with croppie.  Does your code work without the semantic ui popup?

**Comment by matavele** [comment]
Yes.

**Comment by thedustinsmith** [comment]
Try doing `$('.demo').croppie({})` instead of `$('#img_0101').croppie({})` - you might be grabbing the div that you're cloning instead of the popup.

**Comment by matavele** [comment]
It works, thank you. this gave me a lot of work, i do not understand the difference between $('.demo'). and $('#img_0101').
