### ISSUE TITLE
Zooming into large images issue

### ISSUE THREAD

**Issue by kbeat** [Foliotek/Croppie#187]
I have the problem with zoomer. First of all, here's my code. It's the common function to read an image and show a preview before uploading it to server:

Setting the image:
`   function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#avatar').addClass('hide');

                $('.croppie-image-here').croppie('destroy');
                croppie = $('.croppie-image-here').croppie({
                    viewport: {
                        width: 230,
                        height: 300,
                        type: 'rectangle'
                    },
                    boundary: {
                        width: 230,
                        height: 300
                    }
                });

                croppie.croppie('bind', {
                    url: e.target.result
                });

                $('.upload-image').text('Upload');
                $('.save-croppie').removeClass('hide');
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
`

Here's the preview right after i upload an image:
![image](https://cloud.githubusercontent.com/assets/893223/17644700/8ac3d218-61af-11e6-99cb-872a049ee59c.png)

Here's the same preview on the maximum zoom level. As you may notice, the initial preview was not changed significantly:

![image](https://cloud.githubusercontent.com/assets/893223/17644701/b1ce2ba6-61af-11e6-9a85-021525a5a80e.png)

And here's what i get, when I save the image:

![image](https://cloud.githubusercontent.com/assets/893223/17644706/e2c547b2-61af-11e6-9fef-d501fa608f8c.png)

The problem is: although the zoom slider were changed from minimum to maximum, the preview zoomed not more than 10-15%, but the image is saved correctly.

**Comment by thedustinsmith** [comment]
Sorry for the delayed response.  I threw together a jsbin to see what kind of issues you were having: https://output.jsbin.com/govopap

Could you modify this to reproduce your problem, because I'm not seeing it.

I really like the UI that you've put togther.  I might use this for an example on the demo page if that's alright with you.

**Comment by kbeat** [comment]
Hi, Dustin.

I've added the "enableOrientation: true" option to the croppie initialization and this solved the problem. Sorry, it happened just today and I completely forgot about this open issue.

Sure, you can use the UI.
