### ISSUE TITLE
Issue using div and CSS to control position of croppie

### ISSUE THREAD

**Issue by philliplevin** [Foliotek/Croppie#188]
We are having an issue using a surrounding div element and CSS to position where on the page croppie appears. 

Without any div element, I am noticing that croppie is centered completely in the middle of the page, which is fine. But upon placing it in a div and attempting to use any kind of CSS, it just floats off to the right of the page and doesn't seem to respond to trying to control the positioning. 

Is there any good documentation or suggested ways to do this that perhaps we are missing?

Phillip

**Comment by thedustinsmith** [comment]
Sorry for the delayed response.  I'm having a hard time understanding your problem.  Could you throw together a jsbin or a jsfiddle to demonstrate the issue?
