### ISSUE TITLE
Not working with Chrome

### ISSUE THREAD

**Issue by teadawg** [Foliotek/Croppie#189]
Chroppie (v2.2.3) ist not working with Google Chrome (v52.0.2743.116). No image is displayed. For example view the demo page with Chrome.

**Comment by alsmpd** [comment]
@teadawg, the demo page is working properly for me in Google Chrome (v52.0.2743.116). Could you provide more information? Perhaps an extension is causing the issue?

**Comment by teadawg** [comment]
Sorry, my fault. After a restart it works!
