### ISSUE TITLE
Issue when cropping first image

### ISSUE THREAD

**Issue by mcbuckets** [Foliotek/Croppie#192]
I'm experiencing very weird issue when uploading and cropping picture at once.

This is my code:

```
            function readFile(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $cropArea.croppie('bind', {
                            url: e.target.result
                        });
                    };

                    reader.readAsDataURL(input.files[0]);
                }else {
                    swal("Sorry - you're browser doesn't support the FileReader API");
                }
            }

            var $cropArea = $("#pic-bg");

            $cropArea.croppie({
                enableExif: true,
                showZoomer: false,
                enforceBoundary: true,
                viewport: {
                    width: 200,
                    height: 200,
                    type: 'rectangle'
                },
                boundary: {
                    width: 300,
                    height: 300
                }
            });

            $("#lprofilePicture_file").on('change', function () {

                readFile(this);

                $cropArea.croppie('result', {
                    type: 'canvas',
                    size: 'viewport'
                }).then(function (resp) {
                    console.log(resp);
                    $(".cropped-hidden").val(resp);
                });


            });
```

First time i upload an image after page refresh i get shortened base64 encoded string(white image when decoded) as croppie response but if i change the image once more i get the normal results(and every time after that). I don't quite understand why is it happening. Any help is much appreciated!

**Comment by thedustinsmith** [comment]
The problem is the file reader and croppie are both asynchronous.  See `onload` in `readFile`.  If you do a `console.log('after read file');` after `readFile(this);` and also a `console.log('inside readfile load')` you'll find out that `after read file` is logged before `inside read file load`.  Not to mention that croppie's bind is asynchronous as well.

If you really want the result as soon as the file is uploaded maybe something like this is more suitable for you:

```
function readFile(input) {
    var def = $.Deferred();
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $cropArea.croppie('bind', {
                  url: e.target.result
             });
          };
         reader.readAsDataURL(input.files[0]);
     } else {
           swal("Sorry - you're browser doesn't support the FileReader API");
     }
    return def.promise();
}
```
```
$("#lprofilePicture_file").on('change', function () {
  readFile(this).then(function(){
    $cropArea.croppie('result', {
      type: 'canvas',
      size: 'viewport'
    }).then(function (resp) {
      console.log(resp);
      $(".cropped-hidden").val(resp);
    });
   });
});
```

**Comment by mcbuckets** [comment]
Just one small problem:

```
           $("#locastic_dj_registration_profilePicture_file").on('change', function () {

                readFile(this).then(function(){
                    console.log('read'); <----- never gets executed
                    $cropArea.croppie('result', {
                        type: 'canvas',
                        size: 'viewport'
                    }).then(function (resp) {
                        console.log(resp);
                        $(".cropped-hidden").val(resp);
                    });
                });

            });
```

Promise then function never gets executed. I'm no javascript expert and have no idea why. Treid to remove it but same thing happens (stated in issue)

**Comment by mcbuckets** [comment]
Thank you for the help..unfortunately still no luck

**Comment by mcbuckets** [comment]
I managed to make it work. I just needed to put `def.resolve(event.target.result);` after binding in reader.

Like this:

           function readFile(input) {
                var def = $.Deferred();
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $cropArea.croppie('bind', {
                            url: e.target.result
                        });
                        def.resolve(event.target.result); <--------
                    };
                    reader.readAsDataURL(input.files[0]);
                } else {
                    swal("Sorry - you're browser doesn't support the FileReader API");
                }

                return def.promise();
            }

            var $cropArea = $("#pic-bg");

            $cropArea.croppie({
                enableExif: true,
                showZoomer: false,
                enforceBoundary: true,
                viewport: {
                    width: 200,
                    height: 200,
                    type: 'rectangle'
                },
                boundary: {
                    width: 300,
                    height: 300
                }
            });

            $("#lprofilePicture_file").on('change', function () {

                readFile(this).then(function() {
                    $cropArea.croppie('result', {
                        type: 'canvas',
                        size: 'viewport'
                    }).then(function (resp) {
                        console.log(resp);
                        $(".cropped-hidden").val(resp);
                    });
                });
            });
