### ISSUE TITLE
Not IE9 compatible

### ISSUE THREAD

**Issue by beatgeb** [Foliotek/Croppie#196]
IE9 does not show Images at all

**Comment by alsmpd** [comment]
Thank you for the information. 

Croppie has not been tested in IE 9 so we don't officially support anything below 10. 

We are looking for people to test in IE 9. If you are willing to test and provide more information it would be appreciated.

**Comment by jvyyuie** [comment]
It not works on IE9, because IE9 not support the "range" type in <input> element.

I have no idea to fix it, but I replace range to text in the croppie.js, it's not a good method, but it works at least.

**Comment by thedustinsmith** [comment]
I've removed the note about IE9 from the documentation.  If ie9 support is desired feel free to try @jvyyuie 's solution, or a different image cropping plugin.
