### ISSUE TITLE
Multiple croppie elements with canvas inefficient

### ISSUE THREAD

**Issue by oliverx0** [Foliotek/Croppie#197]
I wanted to load a slider that lets users scroll through each slide and crop elements. When using EnableExif: true, this becomes very slow, because each slide is a different canvas. I need my images to display in the correct orientation. What I did was use the loadImage library to first detect the right orientation and generate a new base64 encoded image, and then generate a croppie with the correct orientation without enableExif (which does not use a canvas). Would you like me to share my code?

**Comment by thedustinsmith** [comment]
Hey, sorry for the delayed response.  If you could share your code on this issue/a gist/jsfiddle/codepen/wahtever, that'd be great.  

I was never a big fan of putting the exif stuff in croppie.  And while I encourage using loadImage to correctly orient the images, I don't think it should be bundled with croppie.  Some people disagree.

Having your code to show them how to use it together would be awesome.  Thanks!
