### ISSUE TITLE
Zoom speed

### ISSUE THREAD

**Issue by igoradamenko** [Foliotek/Croppie#201]
Hi!

I use OS X 10.11.6, Chrome 51. And I have some troubles with different zooming gestures. When I zoom image using swipe with two fingers (like mousewheel event) it works fine, but when I zoom using pinch gesture it zooms very fast and it's inconvenient. Check out the gif below. First I use swipe and then pinch.

![aug-29-2016 11-24-06](https://cloud.githubusercontent.com/assets/6537798/18045352/26c26c1a-6ddb-11e6-8b45-3bab0f540b72.gif)

**Comment by thedustinsmith** [comment]
I'll try to dig into the pinch zooming logic when I get time, feel free to look into it and submit a PR.

**Comment by thedustinsmith** [comment]
Closing due to no response.
