### ISSUE TITLE
Image is always super zoomed

### ISSUE THREAD

**Issue by jbigorra** [Foliotek/Croppie#202]
Hi there, 

Im having an issue with the zoom, whenever i initialize the croppie and load the image, the size of the image is super big and it does not egt restricted to the container width and height. 

Plus the zoom only goes down and not UP with the mouse wheel and is super sensitive.

This is the code im using to initialize: 

`$('#patient-img-container').croppie({
            boundary: { width: 300, height: 300 },
            viewport: { width: 159, height: 159, type: 'square' },
            customClass: 'editable-patient-img',
            mouseWheelZoom: true,
            enableZoom: true,
        });

        $('#patient-img-container').croppie('bind', {
            url: '/images/avatar.png',
            points: [300,300,300,300]
        });`

and this are the css classes im applying:

`.patient-img, .editable-patient-img {
    width: 159px;
    height: 159px;
    border: 2px solid $blue-primary;
    border-radius: 4px;
    margin: 15px auto 5px;
}

.editable-patient-img {
    width: 305px;
    height: 305px;
    img {
        height: 300px;
        width: 300px;
    }
}

.croppie-container {
    padding: 0;
}`

Im doing all of this inside a modal: 

`    <div class="modal fade" id="img-modal" tabindex="-1" role="dialog" aria-labelledby="img-modal-Label">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="img-modal-Label">{{ ucwords(trans('labels.img-edit')) }}</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                            <div class="" id="patient-img-container">
                               
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 text-center">
                        	<input type="file" name="img" id="img" class="hidden" value="{{ trans('labels.upload-photo') }}">
                            <label for="img" class="btn btn-form">
                                <i class="fa fa-upload" aria-hidden="true"></i>
                                {{ trans('labels.upload-photo') }}
                            </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" id="close-img-edit"
                            data-dismiss="modal">{{ ucfirst(trans('labels.close')) }}</button>
                    <button type="button" class="btn btn-form"
                            id="set-image">{{ ucfirst(trans('labels.save')) }}</button>
                </div>
            </div>
        </div>
    </div>`

Any help or direction would be appreciated!

**Comment by thedustinsmith** [comment]
Your `points` are incorrect.  Points is an array [x1, y1, x2, y2].  If your x1 and x2 are equal and your y1 and y2 are equal, you're zooming in on a single pixel (not even that).  If you want to zoom into the image at the 300,300 point, and you want the image to be 300px wide and tall, then your points should be [300, 300, 600, 600].
