### ISSUE TITLE
Event for when croppie AND the image is fully loaded?

### ISSUE THREAD

**Issue by winternet-studio** [Foliotek/Croppie#203]
Is it possible to attach to an event indiciating that croppie AND the image is fully loaded? I would have like to espacially be able to attach an onload handler to the image tag...

**Comment by thedustinsmith** [comment]
Are you using the `bind()` method?  If so it returns a promise that indicates when the image has loaded.  If you're passing in the src through the initialize, I'm not sure, but I don't think we trigger an event on that.  

I can see triggering an event being useful.

**Comment by winternet-studio** [comment]
Awesome, I do use the bind method, so I can do this:

	var bindPromise = basic.croppie('bind', {
		url: 'https://...'
	});
	bindPromise.then(function(p) {
		console.log('Croppie completed loading image!');
	});

**Comment by thedustinsmith** [comment]
Closing since it seems the `bind` method provides the needed events.
