### ISSUE TITLE
Feature: add the possibility to get a canvas element rather than only dataURL as a result

### ISSUE THREAD

**Issue by abuisine** [Foliotek/Croppie#204]
this would allow to use an external resize library (like [pica](https://github.com/nodeca/pica)) without an unecessary step of encoding/decoding

**Comment by thedustinsmith** [comment]
Good idea - this would solve quite a few problems.  I'll have to do a bit of research into this one, but I like this idea.

**Comment by thedustinsmith** [comment]
will be in `2.4.0` by passing `type: 'rawcanvas'` into result method.  Sorry `canvas` was already taken.  I've started the process of migrating the `base64` result to be `type: 'base64'`

**Comment by darcy95** [comment]
Do you have any examples that show the usage of 'rawcanvas' type? 

I'd like to merge the resulted image of Croppie with a photo frame image (e.g., a polaroid-look frame around the original image) in my project. I don't know if 'rawcanvas' can be a solution for the purpose.

Thanks
