### ISSUE TITLE
Is it possible to update viewport dynamically?

### ISSUE THREAD

**Issue by iamakimmer** [Foliotek/Croppie#205]
Is it possible to upload the viewport with an existing croppie instance? I would like to use one croppie element and be able to change images, but also change the viewport at the same time. The boundary would stay the same.

**Comment by thedustinsmith** [comment]
Short answer: no.

Long answer: you can destroy the croppie and reinitialize it, but that loses your crop points.  There have been quite a few requests for viewport resizing or dynamically changing opts on a croppie instance. I just haven't gotten to them.

**Comment by thedustinsmith** [comment]
Closing in favor of #22.  If you'd like to submit a PR, I'd love to merge it in.
