### ISSUE TITLE
Points returning [ 0, 0, 0, 0]

### ISSUE THREAD

**Issue by esganzerla** [Foliotek/Croppie#212]
Hi,

I was testing the script and I got the problem, that no matter where I would select the image to crop the ```get``` function would return the correct zoom, but the points would return only an array with zeros.

I tested on chrome, firefox both jQuery plugin and Vanilla.

Got it from the npm.

**Comment by thedustinsmith** [comment]
If I run this:
```
$('.demo-cropper').croppie('get')
```
on https://foliotek.github.io/Croppie, I get a correct list of points.  

Can you be more detailed with your submission?  Have some code you can share?

**Comment by esganzerla** [comment]
I set the croppie on one function like this
```javascript
croppie = $('#croppie_img').croppie({
                        url: image,
                        viewport: {
                            width: 150,
                            height: 150,
                            type: 'circle'
                        }
                    });
```

And I try to get the info on other function like this:
```javascript
console.log($('#croppie_img').croppie('get').points)
```

croppie is a global variable, I tried using from this variable and setting it with a different name also.

**Comment by esganzerla** [comment]
By the way, I'm using an image that comes from the FileReader().

I guess this shouldn't be a problem, since I tried to console positions on the ```_get()``` function and it works just fine until I call por the ```$...croppie('get')```.

**Comment by thedustinsmith** [comment]
Not quite sure what you mean - is there anyway you can share a codepen/jsfiddle/jsbin that demonstrates the issue?

**Comment by esganzerla** [comment]
I'd don't think I'd be able to reproduce everything on the codepen, I sent the page to a server though.
The function that I use goes through some other functions...

You can check it happening on (http://ec2-52-67-147-248.sa-east-1.compute.amazonaws.com/testing/sd). You will need to login, just click on "Entrar" on the right top corner: username: sd@sprinta.com
pasword: 123456
Then click on the profile picture to change it.

**Comment by thedustinsmith** [comment]
When I upload an and do `$('#croppie_img').croppie('get')` - I get points that aren't 0's.

Maybe it's something weird with the image you're using?

**Comment by esganzerla** [comment]
Ohhh, I just realized what is happening.

Seems that I was closing the modal window before collecting these informations...

Thanks for you help @thedustinsmith !

**Comment by Dacesilian** [comment]
I was getting this on form submit and I didn't realize, that I hide all first and then get zero coordinations... So get info first and do not hide canvas before :D
