### ISSUE TITLE
Some images (particular iPhone images) don't return imgData

### ISSUE THREAD

**Issue by andreikainer** [Foliotek/Croppie#218]
Can someone please tell me what I am doing wrong. Some Images in particular photos taken with iOS devices do not return any width or height data on the preview element. Therefore the `_updatePropertiesFromImage()` function can not calculate the zoomer.min, zoomer.max and so on... values correctly. Well first it would return in the `isVisibile.` check anyway but for debugging purpose I have commented it out.

The image is coming in via Filereader() Upload. I have Exif enabled. I'm using v2.0.2 at this stage.

In the `_updatePropertiesFromImage()` function I'm console logging this:
![screen shot 2016-10-06 at 5 12 16 pm](https://cloud.githubusercontent.com/assets/10714161/19140282/1e75c158-8be8-11e6-8200-32e83190f506.png)

I get an output of:

0

<img width="282" alt="screen shot 2016-10-06 at 4 51 40 pm" src="https://cloud.githubusercontent.com/assets/10714161/19140303/5e2fbfc4-8be8-11e6-8b43-d4b447c4fe95.png">

0

Any idea why I can not access the `<offsetHeight>` property eventhough that value is set in the Croppie Object? Any help i would highly appreciate. Thanks!!

This is my object instantiation:

``` javascript
 vehicle_pic = $('#image').croppie({
        enableExif: true,
        enableOrientation: true,
        showZoomer: false,
        boundary: {width: 630, height: 363},
        viewport: {width: 610, height: 343, type: 'square'}
    });
```

Filereader:

``` javascript
function readFile(input) {

    if (input.files && input.files[0]) {
        // make sure the image is big enough (100 kb)
        if(input.files[0].size < 100000){
            return alert('Image must be larger then 100kb');
        }

        var reader = new FileReader();

        reader.onload = function (e) {
            $('#rotation').val('0');
            vehicle_pic.croppie('bind', {
                url: e.target.result
            });
        };
        reader.readAsDataURL(input.files[0]);
    }
}
```

BTW.. Awsome tool! Thank you so much for that!

**Comment by andreikainer** [comment]
This is one of the images that cause the mentioned error:
![402-3](https://cloud.githubusercontent.com/assets/10714161/19173449/e459db48-8c83-11e6-938b-1e4a67d6bb6c.jpg)

**Comment by thedustinsmith** [comment]
I'm sorry - I don't see anything in your code that should cause empty imgData.

Could you possibly throw together an example and maybe I'll be of more help?

**Comment by andreikainer** [comment]
Hi Dustin. And thanks for your reply. I found the issue: Since the preview image is loaded into a BS Modal i had to wait for the modal to be finished and call `bind` again. I know you mentioned this in your documentation but I totally overlooked it. here is the full fix:
```javascript
$('#modal').on('shown.bs.modal', function (e) {
    vehicle_pic.croppie('bind');
});
```
Thank you again for the great tool!

**Comment by thedustinsmith** [comment]
Glad to hear it ... thanks for following up!
