### ISSUE TITLE
SCRIPT5022: IndexSizeError in ie11 when enforceBoundary set to false

### ISSUE THREAD

**Issue by tzubair** [Foliotek/Croppie#219]
I am using enforceBoundary:false and its working fine in chrome but in internet explorer 11 its giving IndexSizeError when boundary is bigger than the origional image.

Here is my code:

$uploadCrop = $('#image_upload_container').croppie({
                        enforceBoundary:false,
                         enableExif: true,
                        viewport: {
                            width: width,
                            height: height,
                            type: 'square'
                        },
                        boundary: {
                            width: width + 50,
                            height: height + 50
                        },
                        showZoomer: true,
                        mouseWheelZoom: false,  
                    });

![screenshot 2](https://cloud.githubusercontent.com/assets/2232045/19143246/07bd5a56-8bbc-11e6-9a1f-6aa8ab89ab9f.png)

**Comment by thedustinsmith** [comment]
Thanks for the submission - I'm seeing that too.  That makes safari and IE that don't support cropping an image outside of it's boundaries.

Let me see what I can do.

**Comment by thedustinsmith** [comment]
will be fixed in `2.4.0`

**Comment by tzubair** [comment]
👍

**Comment by ACXgit** [comment]
Hello, I'm getting the same error with `2.6.2` on IE11:
```
const size = el.clientHeight
const cropper = new Croppie(el, {
  url: imgUrl,
  enforceBoundary: false
  viewport: {
    width: size,
    height: size,
    type: 'square'
  }
})

cropper.result('blob') // <- 'Unhandled promise rejection IndexSizeError'
  .then((blob) => { ... })
```

**Comment by Chaya56** [comment]
Error seems to be back in 2.6.2 with IE11
