### ISSUE TITLE
Dynamical boundary 

### ISSUE THREAD

**Issue by buiminhtri318** [Foliotek/Croppie#221]
HI Croppie team, the plugin is awesome and thank you so much for creating it. For the current project, we are having a problem. When initialising, we set boundary to be width 700px, height 400px to match the desktop design. But for the mobile screen we have to include this css 
```
    .cr-boundary {
      width: 300px !important;
      height: 300px !important;
    }
```
in order to match mobile design. This is causing image cannot be draged around when transform from desktop screen to mobile screen. Is there any way we can set dynamic boundary when change from desktop size to mobile size?

**Comment by thedustinsmith** [comment]
No - not really.  You can initiate the croppie on page load, and detect if the browser's window size is less than a certain size.  If so you could set the boundary to the width/height of the browser window. 

Regardless, setting the width of the boundary via css will never work.  Those dimensions have to be set via the api.

There are several "responsive" issues for croppie.  Other people might have solutions, but currently the plugin doesn't support it...

See: #168
