### ISSUE TITLE
How can I crop a cover image on Mobile View

### ISSUE THREAD

**Issue by anshul321** [Foliotek/Croppie#224]
I want to save the cover image in 1200px, its fine while working with web. On browser I am able to show 1220px viewport to user but can I use the same thing on mobile view or tablet view as I can not show him a 1200px viewport there.

Please help its very urgent for me.

**Comment by thedustinsmith** [comment]
The result (http://foliotek.github.io/Croppie/#result) takes in a size parameter.  Try that out.

**Comment by anshul321** [comment]
@thedustinsmith Thanks for the reply, my issue is that on the mobile I can show 340px as boundary and I need viewport of 1200px.

So how can I manage this ?

**Comment by thedustinsmith** [comment]
Why do you need a viewport of 1200px?  Short answer is you can't.  Not unless you want people to scroll on their mobile device.

If you're just trying to get an image result of 1200px, then pass the size into the result method.

**Comment by anshul321** [comment]
Thanks a lot, I got the way. I was just missing the result method 👍
