### ISSUE TITLE
Slider too many digits after comma

### ISSUE THREAD

**Issue by chrys1110** [Foliotek/Croppie#23]
The min-value of the slider is often up to 16 digits after the comma like
0.3125077572614787.

In Firefox this will cause a error like shown in the screenshot. Could you cap it to a specific amount of digits after the comma?

Chrome seems to work with it though.
![slider](https://cloud.githubusercontent.com/assets/5054524/11566692/cf790d0e-99e3-11e5-87f3-02cec04576db.jpg)

**Comment by thedustinsmith** [comment]
This seems like an easy enough fix.  We're a little busy at the moment, but we'll get to it as soon as possible.  `1.0.3` definitely!

**Comment by thedustinsmith** [comment]
This is fixed in `1.0.3` .. thanks for the catch.
