### ISSUE TITLE
Custom slider

### ISSUE THREAD

**Issue by verdond2** [Foliotek/Croppie#230]
Just wondering has anyone ever used a custom slider  instead of the one that comes as part of the plugin ? The reason I ask is, I have a stacked view setup and I would like to have a panel positioned over part of the cropped area. Be great if I could have a separate slider that I could place anywhere I choose. Any info would be great!

**Comment by thedustinsmith** [comment]
I can't say I've tried it, but it should work fine.  Croppie has a `setZoom` method: http://foliotek.github.io/Croppie/#setZoom

You'll have to use that in combination with your custom slider.

For the record, you can adjust croppie's slider css to your heart's desire.  That might be easier, but that's up to you.
