### ISSUE TITLE
Circle to JPG with certain background color.

### ISSUE THREAD

**Issue by ixodides** [Foliotek/Croppie#233]
Hi, 

I was wondering is it possible to crop image using Circle but the picture should then be outputed as jpg instead of png with certain background color?

**Comment by ixodides** [comment]
I used 
croppie({ viewport: {width: 200,
				height: 200,
				type: 'circle'}

croppie('result', {
				type: 'canvas',
				size: 'viewport',
				format: 'jpeg',
				backgroundColor: '#FF0000'}

I can see in that color is sent to the library but never outputs to an actual jpg.

**Comment by thedustinsmith** [comment]
Are you uploading an image with transparency in it?  And expecting the transparency to be `#ff0000`?

Or are you wanting the resulting image to be a square with the background of `#ff0000` and the cropped circle image inside of it?

I think that `backgroundColor` property was only build for transparency in image.  Not filling a square for a circle image.

Sorry, I know that message was really poorly worded, but I don't really know how else to put it.

**Comment by ixodides** [comment]
Hi, 

Yes indeed, I was hoping that when I use the option backgroundColor I would be able to crop the picture and receive in result a JPG file with circle image and background of my choice around it (instead of default black). 

In the meantime I workaround it with 

```
function popupResult(result) {
	
document.getElementById("results").innerHTML ='<canvas id="myCanvas" width="200" height="200" style="border:1px solid #d3d3d3;"><imd id="scream" src="' + result.src +  '" />';

var gh = result.src
	var s = document.getElementById("myCanvas");
	var cts = s.getContext("2d");
	var img = document.getElementById("scream");
		cts.drawImage(img, 0, 0, 200, 200);
		cts.fillStyle = '#02D2C2';
		cts.globalCompositeOperation = 'destination-over';
		cts.beginPath();
		cts.fillRect(0, 0, 200, 200);
		cts.closePath();
		cts.fill();
	var a  = document.createElement('a');
		a.href = document.getElementById('myCanvas').toDataURL();
		a.download = filename + ".png";
		a.click()
}
```

Basically I put the generated PNG into another canvas and then downloaded that canvas. I still need to figure out how to convert this to JPG rather than PNG.

**Comment by ixodides** [comment]
ok it looks I only needed 
`a.href = document.getElementById('myCanvas').toDataURL("image/jpeg");`

and change 

`a.download = filename + ".jpg";`
