### ISSUE TITLE
security in save image

### ISSUE THREAD

**Issue by hmkhafan** [Foliotek/Croppie#235]
hello
how i can prevent malisious code in file_put_contents?

or how i save cropped image with GD libraries?

or how i can access to x1,y1,x2,y2,width,height of cropped image?

**Comment by thedustinsmith** [comment]
I can answer the last one.  The get method (http://foliotek.github.io/Croppie/#get) returns x1,y1,x2,y2, and some zoom properties.  The width and height can be calculated from those.

```
croppieInstance.get();
//or
$('.crop-el').croppie('get');
```
