### ISSUE TITLE
Bigger touch-zone for controller below image preview?

### ISSUE THREAD

**Issue by AlexioVay** [Foliotek/Croppie#236]
Hello,

how could I enlarge the "hitbox" / touch-zone of the controller below the image-preview? I need this because mostly it's kinda difficult to zoom in or out of an image on mobile versions when not using a mouse.

**Comment by thedustinsmith** [comment]
I'm going to assume you mean the slider handle?  

You can edit croppie's css to make it however large you'd like: 
https://github.com/Foliotek/Croppie/blob/master/croppie.css#L83

Be sure to change the styles for every browser.
