### ISSUE TITLE
Firefox round issue

### ISSUE THREAD

**Issue by thomaspurkaer** [Foliotek/Croppie#24]
If you zoom totally out on some images, firefox gives an error when you want to get the image.

**Line 159:**
ctx.drawImage(img, left, top, width, height, 0, 0, outWidth, outHeight);

**Before that I added:**
width = Math.round(width);
height = Math.round(height);
outWidth = Math.round(outWidth);
outHeight = Math.round(outHeight);

And now it works :-)

**Comment by thedustinsmith** [comment]
Thanks for the detailed information.  Firefox seems to have other zooming/decimal problems, we might need to round all of our numbers to a more manageable decimal point.  In either case, this is helpful.

We'll try to get to it as soon as possible, probably in the next couple weeks.

**Comment by thedustinsmith** [comment]
I'm wondering if the fix for #23 also fixed this one.  Can you pull `1.0.3` and see if you're still having issues?
