### ISSUE TITLE
Zoomed out more than image size on mobile with warped result

### ISSUE THREAD

**Issue by lukealderton** [Foliotek/Croppie#241]
Setting enableOrientation to true allows me to rotate the image as expected, but when I upload an image on my phone it renders sideways, naturally I use the rotate function to correct the issue but now I can zoom out further than my maximum image size and the result given to me by croppie is warped. If I set enableExif to true, the same issue persists.

I found that a combination of commenting out enableOrientation and setting enableExif to true fixed the issue, but I can still rotate the image, which is what I want but it's also odd that I can rotate the image despite not setting enableOrientation to true.

**Comment by thedustinsmith** [comment]
There's a lot going on here ... I'll update the code to not allow rotation without enableOrientation.

I think the zooming related stuff might be fixed in 2.5.2, so I'm going to close this since it's so old.  Sorry I didn't get back to you sooner.  Feel free to reopen this is you see fit.
