### ISSUE TITLE
Croppie failing when Prototype.js also running on the page

### ISSUE THREAD

**Issue by tjarrett** [Foliotek/Croppie#244]
We have a legacy application that is now using both prototype.js and jquery.

When following the example of "Upload Example (with exif orientation compatability)" from the example page directly in our code, the "croppie" interface disappears after the file is selected. 

The problem occurs in the `_triggerUpdate` function. Specifically this line:
`self.$(self.element).trigger('update', data)`

So it turns out, according to the jQuery documentation on [.trigger()](http://api.jquery.com/trigger/) that, if no handlers are found, jQuery will attempt to call a method that matches the name of the event. Prototype injects several "update" methods into multiple Javascript prototypes.

So there appear to be several mitigations to this issue that are possible. 

1. Use namespaced events -- so instead of `.trigger('update', data)` maybe it should be `.trigger('croppie:update', data)` -- of course that might be a breaking change that would make people mad..
2. Use `.triggerHandler()` instead of `.trigger()` -- I confirmed that this works ok but if anybody was relying on the .trigger() functionality this could also be a breaking change
3. Detect Prototype.js and, if installed, either use `.triggerHandler()` or use a `CustomEvent`

I'm going to submit a pull request that goes the route of option number three above -- pushing the logic into using the CustomEvent when Prototype is detected. Long term I'd like to see the library switch to namespaced events or using `.triggerHandler()`. I'd be happy to implement either of the solutions instead if you would like...

**Comment by thedustinsmith** [comment]
fixed in 2.4.1

**Comment by sm1thana** [comment]
Hi

@tjarrett thnx, for the edits.

@thedustinsmith thnx, for the update.

We have got jquery and prototype (1.6.0.2) on site too.
The croppie version is 2.6.2 with this updates. But when we call rotate or result function, croppie does them, but then page reloads.

I think that this makes prototype function fireContentLoadedEvent, but I don't know how can we solve this problem.
Is there any ideas, exept prototype delete?)

Thnx.
