### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by x09326** [Foliotek/Croppie#246]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I found that the license in *package.json* is different from the document *LICENSE*.
Which is right?
Please help me figure out this problem.
Thanks!
https://github.com/cdnjs/cdnjs/pull/9617

**Comment by thedustinsmith** [comment]
There ya go.  Let me know if you need me to publish a new npm release with the license update.  

Thanks for doing this!

**Comment by x09326** [comment]
Okay, we will inform you if we need a npm release.
Thanks!
