### ISSUE TITLE
Upload after using croppie

### ISSUE THREAD

**Issue by lhmosse** [Foliotek/Croppie#250]
HI,

I integrated croppie in a site I am working on. Works perfectly. But I want to upload the cropped result to the server. But my 'input type = file' tag doesn't accept the croppie result to be written to its 'value' (using JS).   This seems to be true in general, you cannot write to an 'input type = file'  field, because of security reasons.

What is the appropiate way to upload the croppie result to the server. What did I miss?

Regards,

Lucas

**Comment by tjarrett** [comment]
The way we are doing this is by having a hidden input field that we set equal to the base64 encoded result from Croppie. We then handle decoding the base 64 on the server.

**Comment by lhmosse** [comment]
OK thanks,

That's exactly what I implemented. Took a while, but it works great now :-)
