### ISSUE TITLE
Callback "on change"

### ISSUE THREAD

**Issue by geri777** [Foliotek/Croppie#251]
Is there any callback function "on change"? I would like to update hidden form fields with the crop points every time the crop information changes. Thanks.

**Comment by thedustinsmith** [comment]
Yep - there's an `update` option: http://foliotek.github.io/Croppie/#update

We also trigger an `update` event that you can listen for with event listeners.

**Comment by ajsuvarna6** [comment]
can give example for Venilla js croppie?
