### ISSUE TITLE
CORS issue with URL which starts with https:// or //s3.blah.blha/blah.png

### ISSUE THREAD

**Issue by elitenomad** [Foliotek/Croppie#255]
Hey Guys, i see a loadImage function in the script which assumes a image URL must be loaded with http. What if the image URL is set as "//s3-ap-blah-2.blah.com/stage.blah.blah.com.au/uploads/item_images/1233344/test-blah-blah-DL9v8kZkyw.jpg" or "https://s3-ap-blah-2.blah.com/stage.blah.blah.com.au/uploads/item_images/1233344/test-blah-blah-DL9v8kZkyw.jpg", Not sure if code could handle the two scenarios to set image CORS attribute.

or am i missing anything ? How to handle this scenario without monkey patching the script file ?

Appreciate if you guys can help !!!!

function loadImage(src, imageEl, useCanvas) {
        var img = imageEl || new Image(),
            prom;

        if (img.src === src) {
            // If image source hasn't changed, return a promise that resolves immediately
            prom = new Promise(function (resolve, reject) {
                resolve(img);
            });
        } else {
            prom = new Promise(function (resolve, reject) {
                if (useCanvas && src.substring(0,4).toLowerCase() === 'http') {
                    img.setAttribute('crossOrigin', 'anonymous');
                }
                img.onload = function () {
                    setTimeout(function () {
                        resolve(img);
                    }, 1);
                };
            });

            img.src = src;
        }

        img.style.opacity = 0;

        return prom;
    }

**Comment by elitenomad** [comment]
I monkey the latest code in my applicaton with the additional conditions in the if block and it works...
                if (useCanvas && (src.substring(0,4).toLowerCase() === 'http' || src.substring(0,4).toLowerCase() === 'https' || src.substring(0,2).toLowerCase() === '//')) {
    /*
       script code...
   */
}

**Comment by thedustinsmith** [comment]
Ah I guess I can see how that might fail in some instances.  Although I think the `if` should look like this:
```
if (useCanvas && (src.substring(0,4).toLowerCase() === 'http' || src.substring(0,2).toLowerCase() === '//')) {
}
```
Since the first part of the `or` would also catch `https`.

Thanks for the info.

**Comment by elitenomad** [comment]
👍 he he .. Good one. Do you want me to raise a PR for this fix or you want to handle it in your next version ?

**Comment by thedustinsmith** [comment]
If you want to submit a PR, I'd be happy to merge it in.

**Comment by elitenomad** [comment]
Thanks @thedustinsmith . I raised a PR for this one. https://github.com/Foliotek/Croppie/pull/256

**Comment by thedustinsmith** [comment]
2.4.1

**Comment by elitenomad** [comment]
👍 Thanks
