### ISSUE TITLE
No default zoom

### ISSUE THREAD

**Issue by Jagalee** [Foliotek/Croppie#257]
We typically use croppie like so:

```
                    $image.croppie({
                        viewport: { width: size.w, height: size.h, type: 'square' },
                        enableExif: true,
                        update: function () {
                            val++;
                            if (val == 3) {
                                $image.croppie('setZoom', 0);
                            }
                        }
                    });
```

Notice that bit around update? Well, we noticed that in the docs there was no default option for setting the default zoom. I got the idea of using the update to see if anything is triggered upon image load (because there is no loaded event). It turns out that the update is called three times, so I check to see if all initial updates have been triggered and then set the zoom to 0. This enables the user to see the full image once it has loaded.

Running setZoom(0) right after enabling croppie did not seem to work for us, doubly-so after exif JS was used to find the orientation data of an image.

**Comment by tjarrett** [comment]
We are handling this issue by using the promise returned when using the bind() method. 

So, for example...
```
croppieContainer.croppie('bind', {url: _profileImagePath}).then(function(){
    croppieContainer.croppie('setZoom', 0);
}.bind(this));
```

Not sure if you can rewrite your code to work this way...

**Comment by thedustinsmith** [comment]
While it's not documented, you can pass zoom into bind.

```
myThing.croppie('bind', {
  url: 'something.png',
  zoom: 0
});
```

You can see this being used in demo.js.

Sorry about it not being documented, I'll get it in there.  The zoom stuff is just so arbitrary that I never saw the need to put it in there.

**Comment by andreszs** [comment]
Neither **maxZoom** nor **zoom** are documented, but luckily I took the time to search for these options, which are exactly what's needed to enforce the right image size by default.
