### ISSUE TITLE
it is work for mobile?

### ISSUE THREAD

**Issue by david43** [Foliotek/Croppie#26]
it work perfect for my android phone
then I try on my iphone 
but it  cant drag or zoom the image

**Comment by thedustinsmith** [comment]
What version of iOS are you running?  I just tried on iOS 9.1 and it worked for me.

**Comment by david43** [comment]
iOS 9.1
work on safari
but not working on chrome
when use  slider to zoom 
the image disappearance

**Comment by thedustinsmith** [comment]
Good catch.  I was using safari.  This was caused by the image being loaded, but not completely.

It's fixed if you grab the latest from `master`.
