### ISSUE TITLE
Crop Image quality is reduced if there is big difference between the original resolution and the viewport resolution

### ISSUE THREAD

**Issue by yong2khoo88** [Foliotek/Croppie#263]
I am wondering if this is un-avoidable:
If the original resolution of the image is **much higher than the viewport's**, the crop result quality is reduced significantly.

![quality-reduced](https://cloud.githubusercontent.com/assets/5007089/21216844/0562f554-c2e4-11e6-819c-f38a116e75cb.jpg)

I come across this [question in the stackoverflow](http://stackoverflow.com/questions/36862138/poor-image-quality-with-javascript-cropping-croppie), but it says that it is fix-able through the setting of quality to 1. However, isn't the default setting is already 1?

**Comment by thedustinsmith** [comment]
Take a look at this thread: #94 - I think it will help you
