### ISSUE TITLE
Problem with save crop img

### ISSUE THREAD

**Issue by AnriKo** [Foliotek/Croppie#266]
Hello.  I have problem to download a cropped image on the server. I assign the cropped image in base64 format in value input text. 
`function() { 
   uploadCrop.result('base64', 'viewport', 'png', 0).then(function(resp) {
   image_crop.value = resp; 
});`
Then sending to the server post request.
The server receives the data from the form post request.
Everything works well if I downloaded the image of small size or in png format
But when I choose to trim the image is larger than 700KB in jpg format the browser begins to slow down when I send this form and send data fails. tell me how can I fix it? Maybe somehow it reduces the size of the cropped image in base64 format, or send the information by other way? Thanks.

**Comment by thedustinsmith** [comment]
Try using the `blob` option in the result method.  It's fairly new, but it seems people are having more luck with that result type.
