### ISSUE TITLE
url with data uri?

### ISSUE THREAD

**Issue by peratik** [Foliotek/Croppie#267]
Hello

```
    var crimg = jQuery('#cimgdiv').croppie({
        viewport: {
            width: 300,
            height: 300
        }
    });
    crimg.croppie('bind', {
        url: 'data:image/jpeg;base64,'+pimg
    });
```

Is it possible to use data:image for image src instead of url?

**Comment by karatektus** [comment]
i just tried and it works fine :)

**Comment by thedustinsmith** [comment]
Yep - it should work.

**Comment by noveweb** [comment]
Hi guys!

Im trying to use this plugin on my cordova app, but on ios the image path uses cdvfile:// path and the plugin dont open the image to crop. How to solve it?

Thanks!

**Comment by gmbad** [comment]
@noveweb, the same problem here.
Did you manage to find a solution?

Tks
