### ISSUE TITLE
Croppie not initiating on safari 

### ISSUE THREAD

**Issue by blackflow** [Foliotek/Croppie#269]
It's pretty bizarre because croppie doesn't initiate on safari (checked 8 and 10) at all.
No errors croppie related in the console, newest version of croppie.
Works fine everywhere else. 
Any ideas how to debug it further? I am using safari via browserstack so it's not that easy:/

I have a live version but unfortunately you have to register to check it- it's on the user avatar upload.
https://www.rekt.gg/

**Comment by pyrliu** [comment]
I can confirm this. Using latest Mac Safari and latest version of Croppie, the image was not shown. Chrome worked well. I found out that the bug has something to do with Croppie div absolute/relative positioning. Quick CSS fix for me was:
`
.croppie-container .cr-boundary {
    min-height: 300px;
}
`
