### ISSUE TITLE
Problems with cropping fully zoomed images with the same height/width in IE/Firefox

### ISSUE THREAD

**Issue by solution404** [Foliotek/Croppie#271]
Hello, i recently used croppie for picture upload in an application im developing, and i came across a problem during cropping. When cropping pictures of the same width/height in IE/Firefox and fully zooming them out they get streched. 
Here's my croppie code and screenshots with the example of the problem:

![mycroppiecode](https://cloud.githubusercontent.com/assets/25146033/21974448/44ae662a-dbc7-11e6-8526-dce59092db33.png)

Here are the normal results when i dont zoom fully:

![notfullyzoomedcrop](https://cloud.githubusercontent.com/assets/25146033/21974631/2fadb0f4-dbc8-11e6-9290-fcc20e98c12a.png)
![uploadedpicturesecond](https://cloud.githubusercontent.com/assets/25146033/21974464/5d6a68d0-dbc7-11e6-8531-cdb25b84ca2e.png)

And here are the results when i fully zoom the same picture and crop:

![fullyzoomedcrop](https://cloud.githubusercontent.com/assets/25146033/21974480/6fef9278-dbc7-11e6-8dba-ae860bc36614.png)
![uploadedpicturefirst](https://cloud.githubusercontent.com/assets/25146033/21974485/7507f91c-dbc7-11e6-999d-1d993aab63e4.png)

This works completly fine in chrome, so im wondering if it's maybe a browser problem?
Is there any solution for this?

**Comment by stolinski** [comment]
Same issue over here.

**Comment by thedustinsmith** [comment]
Thanks the detailed description ... I'm having a hard time getting the problem to happen for myself in firefox, but I did get it to happen in IE.

Then I checked with the latest code, in master, and the issue seems to be fixed.  Could you two confirm that the croppie.js in master fixes your problems?  I've really been waiting for feedback on the latest changes to make sure that it's not going to further break anything, but I haven't gotten much.

**Comment by solution404** [comment]
Sorry the problem happened in firefox developer edition, haven't tested it in the normal version.
The changes from the master version seem to have fixed this issue for me.
Thanks for the update!

**Comment by leeroy88** [comment]
I'm facing the same issue when disabling enforceBoundary, happens in Chrome, Firefox and IE.
The latest code seems to fix the problem!

**Cropping:**
![image](https://cloud.githubusercontent.com/assets/3158625/23659433/052047a0-033e-11e7-9285-b1c61ca343fb.png)


**Image either stretched, incorrectly mapped or missing image data:**
![image](https://cloud.githubusercontent.com/assets/3158625/23659095/f0be54c4-033c-11e7-8449-ada9a9ac58dd.png)

**Image cropped correctly (using code in master):**
![image](https://cloud.githubusercontent.com/assets/3158625/23659289/8cd53c4c-033d-11e7-9b32-10025829bc15.png)

**Comment by thedustinsmith** [comment]
Thanks for the update you two - I'll publish the new version on npm and bower

**Comment by thedustinsmith** [comment]
Fixed in 2.4.1
