### ISSUE TITLE
Hi every Body, i have a problem to rotate picture, when i write enableOrientation: true, the image will disappear

### ISSUE THREAD

**Issue by khalilooooo** [Foliotek/Croppie#272]
<div  class="demo table-responsive"></div>
<input type="button" class="vanilla-rotate" value="90" data-deg="90" />

$('.demo').croppie({
		url:"data:image/JPEG;base64,{{spdr.tallySheetImage[0].data}}",
		viewport: {width: 315,height: 445},
		boundary: { width: 315, height: 445 },
		showZoomer: true,
		enableOrientation: true,
			 });

 $('.vanilla-rotate').on('click', function(ev) 
        {
                    enableOrientation:true, 
                   $('.demo').croppie('rotate', parseInt($(this).data('deg')));
                    });

**Comment by khalilooooo** [comment]
Please answer me !

**Comment by thedustinsmith** [comment]
If you want help, maybe you can throw together a better code example?  What you've given in the issue is not enough to help you out.

For example, it looks like you're templating your url?  How is that working?  

Another example, where's the context of `enableOrientation: true`  You can't just throw that in a click event and expect something to work.  Maybe if you throw together a jsfiddle or a jsbin, we can point out your pain points more clearly.

**Comment by khalilooooo** [comment]
Hi My friend ,  i Thank you first of all to answer me sincerely.

in fact, I work with angularJS 1.5 and the last version of jquery

after trying many times, the problem return to the type of image which i would display it:
other meaning, when i display image from directory,(url:"resources/img/iebc.png",) it's work and rotate very well,

 but if i display image from database, i save my image in database it's disapper due to enableOrientation: true  (//url:"data:image/JPEG;base64,{{spdr.tallySheetImage[0].data}}",) 

url:"data:image/JPEG;base64,{{spdr.tallySheetImage[0].data}}=expression to display image with angularJS
------------------------------------------------------------------------
in htlml:
<div class=" demo table-responsive"></div>  
<input type="button" class="vanilla-rotate"  value="90" data-deg="90" />

-------------------------------------------------------------------
<script>
 
					$('.demo').croppie({
						//url:"data:image/JPEG;base64,{{spdr.tallySheetImage[0].data}}",
						url:"resources/img/iebc.png",

					viewport: {width: 315,height: 445},
					boundary: { width: 315, height: 445 },
					showZoomer: true,
					enableOrientation: true,
					
					});
					$('.vanilla-rotate').on('click', function(ev) 
					{
			 $('.demo').croppie('rotate', parseInt($(this).data('deg')));
                    });
		  </script> 
------------------------------------------------------------------------------------------------
i thank you again to reply my friend

**Comment by khalilooooo** [comment]
in html

**Comment by HartHerbert** [comment]
what have you done to solve this issue ? Because when I crop my images horizontally they will get cropped totally wrong and parts of the image disappear
