### ISSUE TITLE
Bug when croppie div starts closed

### ISSUE THREAD

**Issue by AlexioVay** [Foliotek/Croppie#279]
I'm using Bootstrap and serve a function to change the profile image with croppie. The croppie div isn't visible until you collapse that div with a click. 
However, this way the image size is messed up. It seems to take the full image size. When I'm setting a timer to start the page uncollapsed (to see the contents of the actual croppie div) everything works fine. But not when I'm starting with a collapsed croppie div, and that's what I need.

Is there any workaround or way to fix this? I tried to set the width/height of the container to a specific size, but there's still the same problem. It's something about the canvas.cr-image class as you can see here:

![collllllll](https://cloud.githubusercontent.com/assets/5759953/22764913/c82b5f72-ee6d-11e6-9ded-e215bc16b96f.jpg)

Thanks.

**Comment by thedustinsmith** [comment]
What's the state of the div when you're calling `croppie.bind()`?  Is the div visible?  Not visible?  Maybe you can strip it down to the basics and put together a demo of the issue you're having?
