### ISSUE TITLE
Binding URL Seems to Add '%22' HTML Encoding

### ISSUE THREAD

**Issue by positivecharge8** [Foliotek/Croppie#282]
Below is some code where I take an XMLHttpRequest response (which is my URL path to an uploaded photo) and attempt to bind the URL with Croppie.

As you can see, I'm unnecessarily decoding the returned string just as an extra measure that this issue is with Croppie.

```
var localURL = decodeURIComponent(e.XMLHttpRequest.responseText);
console.log(localURL);


var basic = $('#popupWindow').croppie({
})
basic.croppie('bind', {
     url: localURL
 })
```

Here is the console.log of the localURL string, followed by a 404 error showing how croppy is prepending and appending '%22' to both the beginning and the end of the given URL.

<img width="339" alt="croppie encoding" src="https://cloud.githubusercontent.com/assets/8965315/23077966/a11dea32-f4fb-11e6-81a0-67f50f8e4257.PNG">

**Comment by jdaly13** [comment]
getting same issue how did u fix this?

**Comment by positivecharge8** [comment]
If I remember, its encoding for " character. So you need to strip the quotes.
