### ISSUE TITLE
Flip Image ?

### ISSUE THREAD

**Issue by MentalGear** [Foliotek/Croppie#288]
I was trying over the orientation command to flip the image, but that didn't work out.

Is there any build-in way to flip an image, or how would I flip the image otherwise ?
BTW: Great Plugin, keep up the good work !

**Comment by remluben** [comment]
I am working with *Croppie* right now. As far as I found out from the documentation at http://foliotek.github.io/Croppie/#bind you can provide the *orientation* parameter to make it work. Imho this is not an issue.

Example:

```js
 var c = new Croppie(document.getElementById('item'), {
     enableOrientation: true // required to make the orientation option work in .bind() method
 });
 c.bind({
     zoom: 1,
     url: 'http://example.com/image.jpg',
     orientation: 2 // flips the image horizontally - see docs
 });
```
