### ISSUE TITLE
Issue with Slider: Please enter a value between true and [object HTMLInputElement]

### ISSUE THREAD

**Issue by steveFromNYC** [Foliotek/Croppie#29]
Very strange issue. When Croppie is in a form that has JQuery validation, the slider in croppie always fails with the message:
Please enter a value between true and [object HTMLInputElement]

I've tested this with Firefox, Edge and Chrome. For a test I simply pasted your Basic example in a form that had some validation and sure enough it failed. Note that the croppie control does not have any validation attached to it.

By the way, I also found an odd error with panning. When I pan an image, and then release it, a compatibility problem occurs with the control SummerNote. In summerNote, text selection stop working. I traced it to the mouse down and mouse up events and commented out: 
//document.body.style[CSS_USERSELECT] = 'none';
in each method and that fixed it.

As I'm new to Javascript  (I programmed for years in C# but I'm < 6 months with JS) I not sure that's the right fix, but I figure it would point you in the right direction.

**Comment by thedustinsmith** [comment]
Good call on the user select issue.  I think rather than removing them both, if we just changed the one in mouseUp to `document.body.style[CSS_USERSELECT] = ''` that should fix the issue.

As far as the form, that seems strange, I'll have to look into that a little more.

**Comment by thedustinsmith** [comment]
If you can throw together a jsfiddle or jsbin that demonstrates the form issue, I'd be more inclined to fix it.  As it is, I can't recreate the issue you're describing.
