### ISSUE TITLE
Important Notice: Canvas must be visible for Croppie to work

### ISSUE THREAD

**Issue by MentalGear** [Foliotek/Croppie#290]
Here's an important notice I think you should put promptly into the page's documentation.

I struggled 2 days to resolve why the .croppie("result") function only turned up blank images with 0 width & height.

The answer was, that in my implementation, I hid the canvas the moment the result is produced. Actually, I hid the canvas before the result was asked for, and this seemingly prevents the canvas from extracting an image.

So, please add to the docs that the canvas needs to be visible to produce results, and also that the place where to hid the canvas after the result operation would be in the following .then( $(element).hide() ).

Cheers

**Comment by thedustinsmith** [comment]
Good point.

The beauty of open source is that you can modify the documentation yourself, and submit a PR.  Especially if you'd like it promptly.

I'd gladly merge in any decent documentation improvement.

**Comment by MentalGear** [comment]
Haha, indeed. Kinda forgot that the documentation is in the repo as well. :)
