### ISSUE TITLE
The croppie result isn't working

### ISSUE THREAD

**Issue by john-britto** [Foliotek/Croppie#291]
Hi,
uploadCrop.croppie('result', 'blob').then(function(croppedImage){});

Here I am getting null for blob instead of getting the the blob url
And it's the same issue for base64 as well.

FYI: in your site : https://foliotek.github.io/Croppie/ under the DEMO part for "Vanilla Example" you are using blob even there It's not working.
Please check and help me on that.

**Comment by thedustinsmith** [comment]
This seems to be fixed.  The vanilla example is working on our site.
