### ISSUE TITLE
popupResult nor working

### ISSUE THREAD

**Issue by JiaQazi** [Foliotek/Croppie#294]
i am using demo.js from your repository, i am trying to implement upload example. but i am unable to display the cropped image. I am a newbie so will appreciate help.
Thanks
![croppie](https://cloud.githubusercontent.com/assets/26434903/23949010/4f4d536c-09a7-11e7-94c6-071f3053d1e0.png)

**Comment by thedustinsmith** [comment]
Little late at this point but popupresult takes in an object that either has html or a src.

```
popupResult({
   html: '<img src="//placehold.it/100/100" />'
});
// or
popupResult({
   src: '//placehold.it/100/100'
});
```
both of those will show the same thing.
