### ISSUE TITLE
Question: custom rotation

### ISSUE THREAD

**Issue by langeuh** [Foliotek/Croppie#295]
Hello,

currently rotation is limited to 90degree steps. Is there a way to set this limit to 1?
I'm using the cropper to let people select a circle from an image and later it gets cropped in PHP. 

I understand that if you want a rectangular result this doesn't really make sense, but it does for a circular result.

**Comment by thedustinsmith** [comment]
No, sorry, that's not built into the library.  I can see why it would be useful for your workflow, but I think it'd actually be a lot of work to add it to croppie, and not very useful for most scenarios.  

My recommendation would be to implement this manually.  Sorry for the delayed response.  I'm sure you've moved on at this point.
