### ISSUE TITLE
How to send image to server (Question)

### ISSUE THREAD

**Issue by SimonMoua** [Foliotek/Croppie#298]
Hi, 

I saw your previous answer to a user about converting base64 to image (I'm in c#), but first step first, I'd like to send the cropped image, base64 or not.

I see that the source in cr-image has a long cryptic string that does not change when the style is changed. This suggests that sending this string (is this base64?), would not apply the cropping changes. 

I just want to upload the cropped image to the server, via an ajax post or a form upload (whichever is easiest).

If you answered this question earlier, do you have a full example that I could consult? 

Thanks

**Comment by garek007** [comment]
You can use php, like I did here

https://github.com/garek007/myleb/blob/master/processUploads2.php
