### ISSUE TITLE
Browser became very slow

### ISSUE THREAD

**Issue by huchenhai** [Foliotek/Croppie#302]
Hi, this is very awesome package. But i have an issue is that the browser will become very slow after using many times cut pictures. Is any reason why this happened ? please advise

**Comment by thedustinsmith** [comment]
Do you have several instances of croppie on one page?  Or are you binding one croppie image to several images?

**Comment by huchenhai** [comment]
@thedustinsmith No, it was a single instance which is the simplest one. I put it under the bootstrap modal, it takes time to response and browser looks very heavy

**Comment by thedustinsmith** [comment]
I'm not exactly sure then.  I know plenty of people have put it in BS modals and haven't had a problem.  The demo page had at least 4 croppie instances running at once and it's not slow.  Are you sure it's croppie that's causing your slowness?  Is the demo site slow for you? https://foliotek.github.io/Croppie

**Comment by huchenhai** [comment]
` $uploadCrop = $('#upload-demo').croppie({
                enableExif: true,
                viewport: {
                    width: 180,
                    height: 180,
                    type: 'circle'
                },
                boundary: {
                    width: 248,
                    height: 248
                }
            });
            $('#upload').on('change', function () {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $uploadCrop.croppie('bind', {
                        url: e.target.result
                    }).then(function(){
                        console.log('jQuery bind complete');
                    });
                }
                if (this.files[0].type.match('image.*')) {
                    reader.readAsDataURL(this.files[0]);
                }else{
                    alert('Invalid file type, image only');
                }

            });
            $('.upload-result').on('click', function (ev) {
                $uploadCrop.croppie('result', {
                    type: 'canvas',
                    size: 'viewport'
                }).then(function (resp) {
                    $.ajax({
                        url: "{{url('logo/b/'.$broker->id)}}",
                        type: "POST",
                        headers: {'X-CSRF-TOKEN':"{{csrf_token()}}"},
                        data: {"image":resp},
                        success: function (data) {
                            html = '<img src="' + resp + '" />'+'<button ng-show="btnVisible" onclick="document.getElementById(\'upload_logo\').style.display=\'block\'">Edit</button>';
                            $(".logo img").prop('src',resp);
                            alertify.log("Logo upload successfully");
                            $('#upload_logo').css('display','none');
                        }
                    });
                });`
Thank you , i will check that, this is the code i'm using, do you think the problem is from there?
