### ISSUE TITLE
How to get the cropped image

### ISSUE THREAD

**Issue by karthickms** [Foliotek/Croppie#305]
Hi all,

I used following code for croppie,

```
<script>
$('.demo').croppie({
    url: 'demo/cat.jpg',
    viewport: {
        height: 150,
    },
    boundary: {
        height: 200
    }
});
</script>
```

> `<div` class="demo"></div>

It's working fine. but how to get the result(crop) of the image. Please hands to me

**Comment by thedustinsmith** [comment]
http://foliotek.github.io/Croppie/#demos

**Comment by neegexmayank** [comment]
http://foliotek.github.io/Croppie/#demos

-- no results

**Comment by bret-miller** [comment]
Here's how I do it. First, create the croppie:
	$('#image-crop-container img').croppie({
		//url:img,
		enableOrientation:1,
		viewport:{width:vpw,height:vph,type:'square'}
	});

I have  a  "Save" button on the screen that calls this:

	$('#image-crop-container img').croppie('result',{type:'base64',size:{width:imgsize[0],height:imgsize[1]},format:'png'}).then(function(r) { 
		gciSaveImage(r);
	; });

That generates the result, which you get in your callback function (gciSaveImage) as base64-encoded PNG.
