### ISSUE TITLE
iPhone orientation

### ISSUE THREAD

**Issue by mroftalp** [Foliotek/Croppie#306]
When taking a photo from iPhone, the crop is still okay, but when it returns the data url the image is rotated. Is there anybody there that has a solution for this? Thank you!

**Comment by uslperera** [comment]
Hi @mroftalp if you have enabled ExIf it works for android devices but not for ios devices. There is a white background displayed.  Looking for a workaround to fix it.

**Comment by thedustinsmith** [comment]
http://foliotek.github.io/Croppie/#demos Checkout the exif demo

Thanks @uslperera
