### ISSUE TITLE
How to preview already uploaded image in croppie.js?

### ISSUE THREAD

**Issue by brij-mohan** [Foliotek/Croppie#307]
I am using croppie.js for crop and uploading image. but i want to preview the image in pop if therre is already an image .Let me know How i will add this feature?
Here is my code for uploading the image using croppie.js:

<div id="imageuploadModal" class="modal" role="dialog">
  <div class="modal-dialog">
	<div class="modal-content">
	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Please Select the image and crop for resize</h4>
      </div>

	    	
		 <form id= "filetoupload" action="<?php echo esc_url( $action ); ?>" method="post"  enctype="multipart/form-data">
			<div class="modal-body" style="padding-top:0px; ">
			<div class="modal-body-inner-wrapper">
				<div class="content-block">
				<div class="form-group">
				</div>
				</div>
				<div class="heading-block">
				
				
				
				
				 <input type="hidden" id="image_url" name="image_url" value="" />
				 <input type="hidden" id="image_data" name="image_data" value="" />
				 <div id="upload-demo" style="width:350px"></div>
				 <strong>Select Image:</strong>
				 <input type="file" id="upload" accept="image/jpeg" name="image">

				</div>
			</div>
			<div class="modal-footer for-rating pd-lr-30" style="padding-top:0px; padding-bottom:0px; ">
				<input type="submit"  class="round-btn upload_sucesss" value="Upload">
			</div> 
			</div>			
		  </form>
	 </div>
</div>
</div>
<script type="text/javascript">

$uploadCrop = $('#upload-demo').croppie({ 

enableExif: true,
enableOrientation: true,
showZoomer: false,
viewport: {

width: 200,

height: 200,

type: 'circle'

},

boundary: {

width: 300,

height: 300

}

});

var p = $(".col-sm-2.col-xs-12 .edit-profile.avatar-block .profile-image-box .upload-profile-image img");
url = p.attr('src');

$('#upload').on('change', function () {

var reader = new FileReader();

reader.onload = function (e) {

$uploadCrop.croppie('bind', {

url: e.target.result

}).then(function(){
	
var res = url.split("/"); 
var res_length =  res.length -1;	

var image_name = res[res_length];

<?php
if($_SERVER["SERVER_NAME"] == '112.196.20.243')
{
$url =  "http://".$_SERVER["SERVER_NAME"].":".$_SERVER['SERVER_PORT']."/wp-content/uploads/job-manager-uploads/avatar/2016/10/"; 
}
else
{
$url =  "http://".$_SERVER["SERVER_NAME"]."/wp-content/uploads/job-manager-uploads/avatar/2016/10/";  

}
?>

var original_image_url = '<?php echo $url; ?>'+image_name;

$("#image_url").val(original_image_url);
		
console.log('jQuery bind complete');

});
}
reader.readAsDataURL(this.files[0]);

});

$uploadCrop.on('update', function(event) {
	$uploadCrop.croppie('result', {

		type: 'canvas',

		size: 'original'

	}).then(function (resp) { 
				$('#image_data').val(resp); 
	});
      });

</script>

**Comment by thedustinsmith** [comment]
I don't quite understand the question, and the code isn't formatted in a way that I can read it.

My first guess is that you want a preview of the cropped image, before sending it to the server to save.  If so, then after this line `$('#image_data').val(resp); ` try this: `$('img').attr('src', resp).appendTo('body')`

**Comment by brij-mohan** [comment]
Thanks for the message. i got it.

**Comment by xenedia** [comment]
![SpotMini1](https://user-images.githubusercontent.com/373347/60791752-f5917000-a16c-11e9-907a-fd702568cd38.jpg)

**Comment by yanchai** [comment]
Hi i am having a problem with the image. I'd like to put a default image on the preview container but the default image doesnt fit on the preview area. Here is the link https://prnt.sc/uos6q3.

**Comment by BabaiR** [comment]
I think it can work for you 
<script>
$('.demo').croppie({
    url: 'demo/demo-1.jpg',
});
</script>
