### ISSUE TITLE
EXIF rotation data isn't taken into account for uploaded images

### ISSUE THREAD

**Issue by NikoRoberts** [Foliotek/Croppie#31]
Using the images from https://github.com/recurser/exif-orientation-examples
You can see that Croppie doesn't display the images in the canvas in the way that they would be seen in for example Preview on a Mac.

**Comment by Diego79** [comment]
I'm facing the same problem.

**Comment by thedustinsmith** [comment]
Do either of you have a suggestion for fixing this problem?  The first result in a quick google search points to [Javascript-Load-Image](https://github.com/blueimp/JavaScript-Load-Image) as a solution, but that feels like a lot of code to correctly orient images.

**Comment by Diego79** [comment]
it's just what I'm checking right now but I'm stuck...

**Comment by NikoRoberts** [comment]
Using the https://github.com/exif-js/exif-js library I did the following in my own lib

```javascript
// the exif.js lib is required for this to work
var rotated_src; // where the rotate image content will be
var exifImg = new Image;
exifImg.src = original_src; // original_src is the original image content

EXIF.getData(exifImg, function() {
  var orientation = EXIF.getTag(this, "Orientation");
  var canvas = $('<canvas id="canvas_exif" width="' + exifImg.width + '" height="' + exifImg.height + '"></canvas>');
  $("body").append(canvas);
  var ctx = $("#canvas_exif")[0].getContext('2d');
  ctx.translate(exifImg.width * 0.5, exifImg.height * 0.5);

  switch(orientation) {
    case 2:
        // horizontal flip
        ctx.translate(canvas.width, 0);
        ctx.scale(-1, 1);
        break;
    case 3:
        // 180° rotate left
        ctx.translate(canvas.width, canvas.height);
        ctx.rotate(Math.PI);
        break;
    case 4:
        // vertical flip
        ctx.translate(0, canvas.height);
        ctx.scale(1, -1);
        break;
    case 5:
        // vertical flip + 90 rotate right
        ctx.rotate(0.5 * Math.PI);
        ctx.scale(1, -1);
        break;
    case 6:
        // 90° rotate right
        ctx.rotate(0.5 * Math.PI);
        ctx.translate(0, -canvas.height);
        break;
    case 7:
        // horizontal flip + 90 rotate right
        ctx.rotate(0.5 * Math.PI);
        ctx.translate(canvas.width, -canvas.height);
        ctx.scale(-1, 1);
        break;
    case 8:
        // 90° rotate left
        ctx.rotate(-0.5 * Math.PI);
        ctx.translate(-canvas.width, 0);
        break;
  }

  ctx.translate(-exifImg.width * 0.5, -exifImg.height * 0.5);
  ctx.drawImage(exifImg, 0, 0);
  return_src = $("#canvas_exif")[0].toDataURL();
  $("#canvas_exif").remove();
});
```

**Comment by brianchance** [comment]
Big thanks to @NikoRoberts, I used his solution and it worked great. I am using images loaded from an open dialog and  EXIF needs the image completely loaded first, so I had to modify it a bit, thought I would share in case anyone is looking for a solution.

```javascript
function rotateImage  (original_src, callback) {
    var rotated_src; // where the rotate image content will be
    var exifImg = new Image;
    exifImg.onload = function () {
        EXIF.getData(exifImg, function () {
          // cool code from NikoRoberts goes here
         callback(rotated_src);
        }
    }
    exifImg.src = original_src; // original_src is the original image content    
}
```

And calling it...
```
function readFile(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            rotateImage(e.target.result, function (src) {
                $uploadCrop.croppie('bind', { url: src });
            });               
        }

        reader.readAsDataURL(input.files[0]);
    }
}
```

The onload should be able to be used with local or remote files.

**Comment by NikoRoberts** [comment]
:+1: great work

**Comment by brianchance** [comment]
I will say that this solution is a bit slow since it copies the image before handing off to Croppie. Would it be possible to read just the orientation bit and write the image once on the Croppie canvas?

**Comment by thedustinsmith** [comment]
When you're calling `bind` it's actually not drawing to a canvas, it's just setting a `src` on an `<img />`.  The only time we ever draw to a canvas is when retrieving the result.  So when you guys are saying "canvas", I'm guessing you're referring to the image that you drag around.

I don't know how I feel about including the exif library with croppie.  It would almost double the codebase.

One possibility is we check to see if there is an `EXIF` object on the window, and if so we can use the logic that you guys have come up with.  But I don't know how much improvement we'll get as far as speed.

**Comment by Th3An1m4l** [comment]
Hi guys. I'm stuck with the same issue. I use croppie to make avatars in my client's system. Its great. Lightweight reliable and fast. But when people make their self for an avatar on iPhone or Android phone it makes picture turned 90 CW or 180 CW. So when I drag and zoom in zoom out and then crop. It crop totally wrong parts and cause errors. So as for me EXIF picture preprocessing must have.

And I'm pretty hope it would be included in nearest udates.

**Comment by thedustinsmith** [comment]
I've made some changes in the exif branch to attempt a solution for this problem.

The changes included read the exif orientation when you bind the image to croppie.  Then it draws the correctly oriented image to a `canvas` (instead of an plain `<img />`).  The `canvas` is now the element that you're dragging around.  

Then when getting the result, we just draw the already oriented canvas to another canvas element.

Requirements for this to work:
1. You must have exif-js included on your page.  We're not including this in croppie by default.  Maybe in the future we can have a croppie-exif.js version, but for now just include the library separately (https://github.com/exif-js/exif-js/blob/master/exif.js)
2. Pass an option `exif: true` into the croppie constructor.  Since there's a little more work that goes into these exif images, I feel like it should be optional.  I'm not married to this idea, but that's the way it is for now.

https://github.com/Foliotek/Croppie/blob/exif/croppie.js

If some people can grab the latest from the exif branch and test it out, I'd be grateful.

**Comment by thedustinsmith** [comment]
In the interest of getting more people to test this you can install the exif supported version with npm now.

`npm install croppie@2.0.0-beta1`

**Comment by brianchance** [comment]
This works great. A lot faster than copying the canvas back to an image. Performance is almost identical with or without rotating. 

Nice job and appreciated. Any release timeframe yet?

**Comment by thedustinsmith** [comment]
I appreciate the input.

Ideally we'd release it sometime this week.  I have some other changes in that branch that I'd like to see released.  However, I'm hoping to get a few more people to use the beta just to make sure that 1) this doesn't break anything currently out there and 2) this actually solves the several issues that have pointed to this problem.

**Comment by thedustinsmith** [comment]
https://github.com/Foliotek/Croppie/releases/tag/v2.0.0

**Comment by Th3An1m4l** [comment]
I think I'll try it tomorrow on my project and I will give a feedback to you.

**Comment by atul2011** [comment]
Hi, I was using old croppie tool and it was working fine but for image orientation issue i just tried above croppie version 2.0.0 and its working fine but after upload it rotate back to landscape mode so do i need to rotate manualy after upload?

**Comment by brianchance** [comment]
When I pull the image result with type: 'canvas', size: 'viewport' and save
it, it is working for me.

**Comment by oldspdx** [comment]
I just implemented this latest version and it worked great. Automatically detected the correct orientation of the image (whereas before it was upside down). I too am using type "canvas"
