### ISSUE TITLE
How to set rotate function like your vanilla demo with jquery?

### ISSUE THREAD

**Issue by M-Husein** [Foliotek/Croppie#311]
Hi, Thanks for share your code.

I want use Croppie, but I can't use rotate function in jquery.
So, my question is, How to set rotate function like your vanilla demo with jquery?

Thank you very much.

**Comment by thedustinsmith** [comment]
You can call any method with vanilla or jQuery.

`$('.croppie-el').croppie('rotate', 90)`

**Comment by M-Husein** [comment]
Thanks for reply,
I try ;)
