### ISSUE TITLE
How to use get() ? please Show an example

### ISSUE THREAD

**Issue by FIERMAND** [Foliotek/Croppie#312]
I use this method always get undefined value

**Comment by thedustinsmith** [comment]
Depends on if you're using jquery or vanilla js.

jquery: `$('.my-croppie-el').croppie('get');`
vanilla: `croppieInst.get()`

**Comment by FIERMAND** [comment]
thank you for your participation......
But, how do i get x_coordinate and y_coordinate from image Which is being cropped.....

**Comment by FIERMAND** [comment]
i use " update: {}  ". and i get x1 y1 x2 y2.... but i get a result is a blank image

**Comment by thedustinsmith** [comment]
Might be easier if you provide some code to demonstrate your issue.  Maybe throw together a jsfiddle or jsbin.
