### ISSUE TITLE
get wrong size imege

### ISSUE THREAD

**Issue by Mateusz86** [Foliotek/Croppie#313]
when i set result image size
`cropper.result({
          type:"base64",
          size:{
        	  width:1000,
        	  height:600
          }
      });
`

My settings are always replaced by default  - "viewport"

**Comment by thedustinsmith** [comment]
Probably related to this: https://github.com/Foliotek/Croppie/pull/303

Are you using the code in master or 2.4.1?

**Comment by Mateusz86** [comment]
When I use the old version (2.4.0) everything is fine, But when i use 2.4.1 it does not work.
When  in 2.4.1 I remove line 1167 ` size: 'viewport'` from RESULT_DEFAULTS again all works.

**Comment by Mateusz86** [comment]
is ok sory

**Comment by rdetert** [comment]
Adding that line fixed it in master for `size: 'original'`. Should I be using 2.4.1?
