### ISSUE TITLE
Safari and box-shadow working problems

### ISSUE THREAD

**Issue by martin-kolar** [Foliotek/Croppie#32]
Hey,

box-shadow on .cr-viewport element don't work on Safari (desktop and mobile) latest verion. Working fine when you set box-shadow on "smaller" value (800px). Above this value shadow don't work.

**Comment by thedustinsmith** [comment]
Good catch.  I'm wondering where you got the 800px from?  I tried 899px and it worked.  Although I'm still on Safari 8.  I was just wondering if you found a reference somewhere.
