### ISSUE TITLE
offset image incorrect after bind

### ISSUE THREAD

**Issue by tkvw** [Foliotek/Croppie#323]
Using Chrome Version 58.0.3029.110 (64-bit) (Windows)

When I look at the last example on https://foliotek.github.io/Croppie/ the offset of the image initially is  incorrect when toggling the button. After you slide the zoom, it corrects the offset. 
![croppiescreencasterror](https://cloud.githubusercontent.com/assets/621098/26155059/28301570-3b12-11e7-9a85-8bd65373c9d5.gif)

**Comment by tomay** [comment]
I'm seeing this issue as well, after loading a rotated image using `enableExif`. Adjusting the zoom slider fixes it

**Comment by thedustinsmith** [comment]
This one is fixed in master and will go live with the next release.  Thanks guys.
