### ISSUE TITLE
Vertical bigger image issue

### ISSUE THREAD

**Issue by hbabuc** [Foliotek/Croppie#325]
hi, firstly this plugin is awesome, but we found an issue;
![screenshot_20170523-183210](https://cloud.githubusercontent.com/assets/7676906/26362471/b70bcf0e-3fe6-11e7-95d3-f4f9d2f68a18.png)
![screenshot_20170523-183227](https://cloud.githubusercontent.com/assets/7676906/26362524/dcfacd5a-3fe6-11e7-9a5f-f15f08075144.png)

when we select a vertical bigger image on top, there is no issue but;

![screenshot_20170523-183214](https://cloud.githubusercontent.com/assets/7676906/26362534/e4d554a0-3fe6-11e7-8e89-4e6ae3f0c711.png)
![screenshot_20170523-183239](https://cloud.githubusercontent.com/assets/7676906/26362574/0e44aff2-3fe7-11e7-8feb-a8a0fa9fe112.png)

when we selected vertical bigger image on bottom, there will be a black box in the output image.
I hope i can tell you the issue exactly. In the horizontal bigger images, there is no problem.

Thank you.

**Comment by patrickng** [comment]
I see this issue as well. I think it's related to #247 and #318. The problem seems to be that when the code
```
            if (left < 0) {
                startX = Math.abs(left);
                left = 0;
            }
            if (top < 0) {
                startY = Math.abs(top);
                top = 0;
            }
            if (right > self._originalImageWidth) {
                width = self._originalImageWidth - left;
                outWidth = width;
            }
            if (bottom > self._originalImageHeight) {
                height = self._originalImageHeight - top;
                outHeight = height;
            }
```
is not properly enclosed by a conditional that checks ```if (!self.options.enforceBoundary)``` according to the comment on line 982 (// start fixing data to send to draw image for enforceBoundary: false)

That bit of code seems to not be necessary if you did not specify enforceBoundary: false in the options.

**Comment by hbabuc** [comment]
ohh thank you, it worked really well. you just saved me a lot of work :+1:

**Comment by raykudo** [comment]
Not working when the viewport is circle
