### ISSUE TITLE
Modal Dialog Question

### ISSUE THREAD

**Issue by trstaley** [Foliotek/Croppie#329]
I want to edit an image within a modal dialog. My code does the following:

    $('.crop-image').croppie( {
		boundary: { width:135, height:135 },
		viewport: { width: 100, height: 100, type: 'circle'}
	});
    $('#upload_img_btn').on('click', function() {
        var data = "<input id=filename1 name='__files[]' type='file' single /> 
                           <div class = 'profile-image' 
                                  style='width: 130px;
                                  margin-left: 300px; 
                                  margin-top:200px; 
                                  width:200px; 
                                  height: 200px; 
                                 display:block;'>
                                <img class='crop-image' src='./train4.jpg'>
                          </div>";
        $('#upload_image').dialog('option', 'title', 'Upload Profile Image');
        $('#upload_image').html(data).dialog('open');
        $('input');
    });

The issue is that the statement  img class='crop-image' src='./train4.jpg' is running after the page is loaded and is within a dialog so the croppie wrapper does not get generated.  How do I correct my code so that the image can be edited within a dialog?

**Comment by trstaley** [comment]
Solved my own issue.  jquery was stripping the script tags from the returned html.  Modified the statement:

    $('#upload_image').html(data).dialog('open');

to:

     $('#upload_image').html(data).dialog('open', document, true);

**Comment by kylerberry** [comment]
@trstaley you should close the issue

**Comment by trstaley** [comment]
Sorry about that - issue now closed
