### ISSUE TITLE
Need A Bit of Help with Uploaded Image

### ISSUE THREAD

**Issue by trstaley** [Foliotek/Croppie#330]
I have successfully implemented croppie and am able to properly view an image loaded from the server.

I now want to view an image that is uploaded through the file select using JS and allow the user to crop the file prior to actually saving the image on the server through the canvas (at least that is how I am imagining it).  I am not clear in my code below how I get the selected file (prior to upload) to view in the croppie viewer.  I know I must be missing something but I am uncertain as to what.

You will notice that the selected-image tag is initially loaded with $image.  This is the previously saved image from the server.

All the code below is wrapped in a php var and returned to the client.

Everything is working with the exception of the selected image replacing the original image in the croppie viewer.

Any help would be greatly appreciated.

```
 <link rel='stylesheet' href='./croppie/croppie.css' />
 <script src='./croppie/croppie.js'></script>
  <script>
  function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
	  reader.onload = function (e) {
                $('#selected_image').attr('src', e.target.result);
          }
          reader.readAsDataURL(input.files[0]);
      }       
 }    
 $('#file-select').change(function(){
     readURL(this);
 });
 </script>
    	
 <input id=file-select name='file' type='file' single />
 <div class='profile-image' style='margin-left: 0px; margin-top:20px; width:200px; height: 200px; display:block;'>
     <img id='selected-image' src='" . $image . "' />
 </div>
 
 <script>
 $('#selected-image').croppie( {
     boundary: { width:135, height:135 },
         viewport: { width: 100, height: 100, type: 'circle'}
 });
</script>
    
```

**Comment by lucadem1313** [comment]
This is what I use:

```
var profileInput = $("#editimage").croppie({
	viewport: {
		width: 200,
		height: 200
	},
	boundary: {
		width: 300,
		height: 300
	}
});

$("#profilepicture").change(function(){
	var fr = new FileReader();

	fr.onload = function(e) {
		profileInput.croppie('bind', {
			url: e.target.result
		});
		$("#editimage").croppie('bind');
	}
	fr.readAsDataURL(this.files[i]);
});
```

Where `#editimage` is the original image for Croppie, and `#profilepicture` is my `<input type='file'>`

**Comment by msegmx** [comment]
@lucadem1313, thanks for your exampmle. one question though, what is the variable "i" referring to ?

**Comment by lucadem1313** [comment]
@msegmx Yes that should be `fr.readAsDataURL(this.files[0]);`. I honestly don't know how that works, but it was like that because I had copied that from another spot in my code where I was looping through them with a for loop.

**Comment by thedustinsmith** [comment]
Looks like you all have it figured out.  Closing this one.
