### ISSUE TITLE
blob result image size not fit viewport size

### ISSUE THREAD

**Issue by fabien-michel** [Foliotek/Croppie#331]
With a viewport defined to 250x250.
The command `result('blob', 'viewport')` do not return an image resized to 250x250, but keep the image original scale (so dimensions can be larger or smaller)

```javascript
var croppie = new Croppie(croppie_container, {
            viewport: { width: 250, height: 250, type: 'circle', },
            boundary: { width: 300, height: 300 },
        });
...
croppie.result('blob', 'viewport').then((blob) => {...});
```

**Comment by thedustinsmith** [comment]
That's not the correct usage of the result method.  
Try: `croppie.result({type: 'blob', size: 'viewport'})...`

**Comment by fabien-michel** [comment]
Ok, thanks it's better, sorry for the noise.
Nevertheless, the doc indicate "viewport" as default size which not seems to be the case.

**Comment by thedustinsmith** [comment]
Thanks for the heads up - it'll be taken care of in the next release: 
https://github.com/Foliotek/Croppie/pull/303
