### ISSUE TITLE
Croppie - Images are blurred on mobile phones when cropped. 

### ISSUE THREAD

**Issue by hemandkk** [Foliotek/Croppie#333]
We reproduced this issue with several different phones:

When i uploaded and cropped via mobile phone resultant images gets blurred.
But when i commented the **viewport** section in below code i got clear image but it take extra spacing on top 

	$uploadCrop = $('#upload-demo').croppie({
			viewport: {
				width: 700,
				height: 700,
				//type: 'circle'
			},
			enableExif: true,
			enforceBoundary: false
		});

		$('#upload').on('change', function () { readFile(this); });
		$('.upload-result').on('click', function (ev) {
			ev.preventDefault();
			$uploadCrop.croppie('result', {
				type: 'canvas',
				size: 'viewport'
				
			}).then(function (resp) {
				popupResult({
					src: resp
				});
			});
		});

**Comment by hemandkk** [comment]
Please note that i commented the  line **size : 'viewport'** in above code.

**Comment by hemandkk** [comment]
Please see the sites below and select cover image in mobile phone.
entesarkar.com ==>  image with black strip
entesarkar.com/test1/  ==>  image gets blurred

**Comment by hemandkk** [comment]
@io-ma
@thedustinsmith 
Please look into this

**Comment by thedustinsmith** [comment]
Sorry for the delay, but I'm not seeing the black strip.  I'm also unable to hit the /test1/ route so I can't test the blurring.

**Comment by choudharyjji** [comment]
Same issue ! Image got blurred while uploading from the mobile phone .. https://www.modeloca.com/models/lynn

check the profile image .. it's blurred cuz it is uploaded from the phone but if i upload this from the pc it looks okay. Please help!
