### ISSUE TITLE
Image rotated after render high resolution image

### ISSUE THREAD

**Issue by thinhpc** [Foliotek/Croppie#334]
Hi,

I have an issue when using croppie. This error only with high resolution image (or Large image for example 5MB).

Step1: Select an high resolution image with height > width:
![fdfs](https://user-images.githubusercontent.com/4747266/26963953-a34f4208-4d19-11e7-9c7a-502493055e4c.png)

And it render with rotated image:
![dfdfdf](https://user-images.githubusercontent.com/4747266/26963980-b9e594b8-4d19-11e7-8f5a-1fe6b345b823.png)

This issue not occur on some computer.

I don't know why and how to fix this.
Do you have any idea for this case?
Thanks!

Original Image:
![abc](https://user-images.githubusercontent.com/4747266/26963933-8447b930-4d19-11e7-9f06-2f632945294d.jpg)

**Comment by io-ma** [comment]
Hi, you should enableExif: 
> Enable exif orientation reading. Tells Croppie to read exif orientation from the image data and orient the image correctly before rendering to the page.
> Requires exif.js
![croppie a simple javascript image cropper foliotek](https://user-images.githubusercontent.com/2306628/26979967-5e2b6010-4d39-11e7-815e-088e91ad95f1.png)

**Comment by erperejildo** [comment]
@thinhpc you didn't have any issue with bigs images like me?
https://github.com/Foliotek/Croppie/issues/328
