### ISSUE TITLE
singleInst Undefined

### ISSUE THREAD

**Issue by uxpanchi** [Foliotek/Croppie#338]
i have been trying to use croppie with bootstrap modal and i am getting error 
"TypeError: singleInst is undefined" 
and i am not able to proceed further,any help for this.
var $uploadCrop;

		$uploadCrop = $("#demo_profile").croppie({
		  boundary: {
			  width: 250,
			  height: 250
		  },
		  viewport: {
			  	width: 200,
				height: 200,
		    type: 'square'
		  },
		  customClass: 'demo_wrap',
		  enableExif: true,
		  enableOrientation: false
		});

		var imagePath = $('#ProfilePicture').data('image-path');
		$uploadCrop.croppie('bind', imagePath);
		$('#fancy_edit_new_page_popup').on('shown.bs.modal', function() {
		    $uploadCrop.croppie('bind');
		    $uploadCrop.croppie('setZoom', 1.0);  
		});

**Comment by thedustinsmith** [comment]
Try moving all your croppie initialization into `shown.bs.modal` event listener.  It's been a while since I've done anything with bootstrap, but if their modal system wraps the `#demo_profile` element it's possible that it may lose the previously initiated croppie instance.
