### ISSUE TITLE
IE support issue

### ISSUE THREAD

**Issue by adamyung** [Foliotek/Croppie#34]
Javascript Promise() does not supported by IE browser.

**Comment by russ-ab** [comment]
Can you make a PR? Like https://github.com/adamyung/Croppie/commit/9ab3dc9df02b2e1278bf108c1959f71b4c18251d

**Comment by thedustinsmith** [comment]
The Promise() thing is fixed if you grab the latest from the repo.  I just haven't updated the bower & npm packages

**Comment by adamyung** [comment]
I saw you use a third party library (es6-promise) to fix the issue, I fix the problem myself by using jQuery library. Thanks.

**Comment by thedustinsmith** [comment]
I saw that, and it looks good.  Unfortunately since Croppie isn't just a jquery plugin, we can't depend on it.      I'll close this one for now, feel free to comment on it if you have suggestions.
