### ISSUE TITLE
Newbie question: Do I need serverside program for this ?

### ISSUE THREAD

**Issue by msegmx** [Foliotek/Croppie#344]
Sorry for newbie question, but I have to ask : 

Do I need a server-side script / servlet etc. for an image to be processed ?
Or does this library send an "ready to be saved as a file" image to the server ?

**Comment by thedustinsmith** [comment]
If you want to save it to a server, I would assume you'd need some kind of of server side script.  if you just want to download the cropped image, there's plenty of things you can do.  

Here's a method if you're using a blob result: https://stackoverflow.com/questions/19327749/javascript-blob-filename-without-link

Here's one if you're using base64: https://stackoverflow.com/questions/14011021/how-to-download-a-base64-encoded-image

**Comment by msegmx** [comment]
Sorry for not having stated my goal here : 

I have a user registration form where the user can also upload an image. But before finishing the registration (submitting the form) I want to, well, force the user to crop the image (if it's a bigger one) so that every uploaded photo is a perfectly sized profile pic.

I've never done that, so my question is : normally the image would be uploaded to a server via 'multiform' html form, like a normal file upload. So I will have a servlet on the server side either way. 

But what will the servlet receive : 
- a ready cropped image, so the only thing the servlet has to do is to write the received bytes on the file system and hence creating a profile.jpeg ?

- Or a coordinate of the cropped parts, which it would then use to crop the image physically (image manipulation) and save the cropped part on the file system ?

**Comment by msegmx** [comment]
ok, nevermind. I think I've figured it out : 
I get a string from Croppie like this : 

data:image/png;base64,iVBORw0KGgoAA...

That's the part I didn't know / understand.
The rest should be easy on the server side servlet.

Thanks for this great library !
