### ISSUE TITLE
result method only works with visible viewport

### ISSUE THREAD

**Issue by DinoSane** [Foliotek/Croppie#346]
I create a form and the images is put on differents tabs. 

Before post, I'm trying to get the result values, but it returns empty if the tab is not shown at the moment.

Please acknowledge this as a feature or a bug...

**Comment by thedustinsmith** [comment]
This would be a feature.  We depend on the position of the boundary, viewport, and image when determining crop points.  Without those things being visible, we can't get points from them.

A potential work around, while not ideal, would be to make the container `opacity: 0`, and throw it behind everything else, if you need.  I'm not sure this would work, but it's something to try.

There's already a case open to remove this dependency of elements being visible, so I'm closing this case. 

Ref: #83

**Comment by DinoSane** [comment]
For others who may landing here with the same problem. 

                crop_photo = $("#img_photo").croppie({
                    update: function (data) {
                            crop_foto.croppie('result', { type: 'base64', size: 'viewport' }).then(function(base64) {
                                $('#bak-photo').val(base64); 
                            });
                    }, 
                });

So I keep saving the changes in a input field then I have the updated change on submit.
This aproach has the obvious disavantage of run "result" method on every change on picture, but it is working better than my other try of turn image visible, run result and then submit.

Thank you anyway.
