### ISSUE TITLE
Issues of IndexSizeError in IE

### ISSUE THREAD

**Issue by wuyingyou** [Foliotek/Croppie#348]
Hi Guys,

Could you please help to address this issue only in IE10/IE11 ?

<img id='demoImg'  src='images/cat.jpg' />

        var cropDemo = $('#demoImg').croppie({
            viewport: {
                width: 309,
                height: 309,
            },
            boundary: {
                width: 309,
                height: 309
            },
            enforceBoundary: false,
            customClass: 'square-image'
        });

Heads up for these 2 tips:
1.  Viewport is the same to the boundary
2.  enforceBoundary is false

Then when we zoom out, say, 0.5 and move the picture to clip partially, the 'IndexSizeError' occurs. After we do some research, we found the root cause is in the API call " ctx.drawImage(this.elements.preview, left, top, width, height, startX, startY, outWidth, outHeight);", if the 'width'/'height' is greater than 'this.elements.preview's width or height, then we got the bug.

We want to add some code to fix this issue, but some times still does not work.

 .........  
      var ua = window.navigator.userAgent;
        var old_ie = ua.indexOf('MSIE ');
        var new_ie = ua.indexOf('Trident/');
        if ((old_ie > -1) || (new_ie > -1)) {
            if (width > self._originalImageWidth) {
                width = self._originalImageWidth - left;
                outWidth = width;
            }
            if (height > self._originalImageHeight) {
                height = self._originalImageHeight - top;
                outHeight = height;
            }
        }
   ctx.drawImage(this.elements.preview, left, top, width, height, startX, startY, outWidth, outHeight);
.......

Attached some screenshots and my IE is IE11.

@manast @fdanielsen @bigamil @spookee86 @kmagiera , could some guys help to look at it? Appreciate your help.

**Comment by wuyingyou** [comment]
![old](https://user-images.githubusercontent.com/13143669/28163291-1c70ffac-67fd-11e7-869f-bce0cf787f25.PNG)

**Comment by wuyingyou** [comment]
![clipped](https://user-images.githubusercontent.com/13143669/28163359-5c54bcda-67fd-11e7-867f-f3acb4f306bb.PNG)

**Comment by wuyingyou** [comment]
![fixing](https://user-images.githubusercontent.com/13143669/28163366-66650b1c-67fd-11e7-95ef-f0b4a75cf9d3.PNG)

**Comment by wuyingyou** [comment]
Here is how we get base64 data. 

$('#demoImg').croppie('result', {
                        type: 'base64'
                    }).then((resp) => {
                        
                    }).catch((err) => {
                           console.log('IndexSizeError ');
                    });

**Comment by wuyingyou** [comment]
here is the example in jsfiddle.

https://jsfiddle.net/barretwu/L5cr6fba/3/

Please use IE11 open it. Thanks again for your help.
 
![error](https://user-images.githubusercontent.com/13143669/28166344-1e8f7a18-680a-11e7-9c68-b38690a988c4.PNG)

**Comment by thedustinsmith** [comment]
This will be fixed in the next release, thanks for pointing it out.
