### ISSUE TITLE
Is there any way to create two objects without repeating the code?

### ISSUE THREAD

**Issue by vinit2885** [Foliotek/Croppie#353]
I have page page having two upload element.
i am trying to use croppie function by creating one single function

var uploadconfig = {
     imgw: "360",
     imgh: "240",
     type:"square",
     upid:"id_upload",
     displaydiv:"imgupdiv"
};
showuploader(uploadconfig,'upload1');

function showuploader(uploadconfig,divid){
**$uploadCrop = $('#'+displayid+'-demo').croppie({
    enableExif: true,
    viewport: {
        width: uploadconfig.imgw,
        height: uploadconfig.imgh,
        type: uploadconfig.type
    },
    boundary: {
        width: 500,
        height: 400
    }
});**
}

Here i am calling this function for two diffrent id's , But its getting override and only upload function of second div is working.
I guess this is due to $uploadCrop object getting override.
Anyone having workaround to solve this issue?

**Comment by thedustinsmith** [comment]
Is there a reason you need `$uploadCrop` to be global?  I would recommend not making it global.  Just put `var $uploadCrop` in front of it.
