### ISSUE TITLE
zoom out, no result excepted

### ISSUE THREAD

**Issue by yoan1005** [Foliotek/Croppie#355]
Hello,
In first, sorry for my english, i'm french :)
I meet a problem with croppie, when i zoom on images who the size are just (like original size are 450x450 and viewport are 400x400)
when i zoom out, the render genered are not the same like in viewport, looks attachments 

i use a "bind" like in example upload on site.

![capture d ecran 2017-07-25 a 08 21 15](https://user-images.githubusercontent.com/14938326/28558636-0b05d85e-7113-11e7-9ece-87e2cdb01542.png)

![capture d ecran 2017-07-25 a 08 21 38](https://user-images.githubusercontent.com/14938326/28558609-e3bea32a-7112-11e7-88de-83c90ff7ac5e.png)

thanks a lot

**Comment by yoan1005** [comment]
After many search, the problem it's was because i'm in modal, for resolve i bind picture after open the modal (with a setTimeout) maybe not perfect solution but it's work for me

**Comment by thedustinsmith** [comment]
Thanks for the info.  Sorry for the delayed repsonse.
