### ISSUE TITLE
Croppie upload in Safari returns strange error!

### ISSUE THREAD

**Issue by thezahir1** [Foliotek/Croppie#360]
When uploading (any) image file within Safari (on Mac OS), this strange popup is returned with 'close' in it (in Dutch this is 'sluiten'). Uploading the file does not work then, by the way.

It seems to be a popup generated by the browser / OS popup, as opposed to a normal page popup. Which means I cannot inspect this popup with a browser inspector to retrieve any page errors whatsoever.
![schermafbeelding 2017-08-14 om 16 50 29](https://user-images.githubusercontent.com/15107075/29277075-f404260c-8110-11e7-9474-5db1b4200c03.jpg)

**Comment by thedustinsmith** [comment]
Try using the `blob` option when getting the result instead of `base64`.  I believe safari has an issue with large base64 strings.  

see: #324
