### ISSUE TITLE
duplicate image not accepting

### ISSUE THREAD

**Issue by vishalsingh119** [Foliotek/Croppie#362]
if i upload image (eg. test.png), when i try to upload same image again, its not working. at secound time its accepting other image but i want to accept same image again

**Comment by flysheep92** [comment]
I have the same problem. If you are saying that you are not able to choose the same file again, trying putting this "this.value = null;" after you select an image.

Something like this:
<input type="file" id="uploadButton" />

$("#uploadButton").on("change", function() {
      var reader = new FileReader();
      reader.onload = function (e) {

     $uploadCrop = $('#preview_pic_area').croppie({
					enableExif: true,
					 viewport: {
					               width: 200,
						       height: 200,
						        type: 'circle'
						 },
						 boundary: {
							width: 300,
							height: 300
						 }
					});

	$uploadCrop.croppie('bind', {
				    	
				   url: e.target.result
		}).then(function(){
				    $('#change_profilePic').modal('show');				    		
		});
				    	
		  }
		  reader.readAsDataURL(this.files[0]); 
		**this.value = null;**   
});

});

**Comment by vishalsingh119** [comment]
This also good option, before that we achieved using clear the input value on click of input option.
Thanks
