### ISSUE TITLE
Laravel upload croppie image

### ISSUE THREAD

**Issue by majweb** [Foliotek/Croppie#364]
Hello.
I want to save croppie img to db. All is working but request save normal img to db not croppie.
https://pastebin.com/YnyZ58ip

**Comment by thedustinsmith** [comment]
If you're getting the base64 result try this: https://stackoverflow.com/questions/26785940/laravel-save-base64-png-file-to-public-folder-from-controller

If you're getting a blob result try this:
https://laravel.io/forum/02-17-2014-how-do-you-save-image-to-database-and-display-it-on-website

Saving images to the database is pretty bad idea, IMO.  If you have the option, it would be better to save the image to the file system, and save the path to the image in your db.
