### ISSUE TITLE
Square image in a not square box

### ISSUE THREAD

**Issue by WesVleuten** [Foliotek/Croppie#367]
When I upload a square image in a not square cropper and put part of it outside the border, the result is stretched.

```
$uploadCrop = $('#upload-demo').croppie({
    enforceBoundary: false,
    viewport: {
        width: 300,
        height: 200,
    },
    boundary: {
        width: 400,
        height: 300
    }
});
```

Here you can see input and output: http://imgur.com/a/l97Mx?

**Comment by nathanwienand** [comment]
Hi there guys I have loaded a PR with a fix for this issue: https://github.com/Foliotek/Croppie/pull/378
