### ISSUE TITLE
Images on iOS

### ISSUE THREAD

**Issue by brianchance** [Foliotek/Croppie#37]
I have croppie working on mobile iOS 9.2, but I am having some challenges getting what I want...

My viewport is 260x260, square and the boundary is 300x300. When I load an image from on my phone that is, say 960x1260 (the default), it does not scale down and with the zoom all the way left, it is still to close up to make any details out.

You can see the same results on the demo page's upload example.

Digging in with Safari's web inspector, it looks like iOS is giving a "Cross-Origin Resource Sharing policy error" in loadImage so img.onload never fires to resolve the promise and _updatePropertiesFromImage never gets called. If I manually call _updatePropertiesFromImage, the image looks correct.

Checking around the internet, I am thinking that
`img.setAttribute('crossOrigin', 'anonymous');`
should be...
```
if(src.substring(0,4).toLowerCase()==='http') {
    img.setAttribute('crossOrigin', 'anonymous');
}
```

**Comment by r6047736** [comment]
Thank You, had same problem and your solution fixed it :+1:

**Comment by thedustinsmith** [comment]
Perfect!  We'll make this change sometime this week.  Been out for the holidays for the past couple weeks, sorry it took so long to respond.
