### ISSUE TITLE
TypeError: $(...).croppie is not a function[Learn More]

### ISSUE THREAD

**Issue by sarvesh20** [Foliotek/Croppie#370]
I have include CSS and Js in header area bottom on jquery call, and Code to initiate library is in footer.

**Comment by alsmpd** [comment]
Hello @sarvesh20,

- [ ] Check the ordering of your script tags. jQuery before croppie. 

```
<script src="jquery.js"></script>
<script src="croppie.js"></script>
```

- [ ] Check the source attribute and confirm the location of croppie.js is correct.

**Comment by klausbreyer** [comment]
Found this by google. It is also a problem, if you include later a second, older, version of jquery ;)

**Comment by KAUSHIKKAPIL8750** [comment]
Hey thanks

> Hello @sarvesh20,
> 
> * [ ]  Check the ordering of your script tags. jQuery before croppie.
> 
> ```
> <script src="jquery.js"></script>
> <script src="croppie.js"></script>
> ```
> * [ ]  Check the source attribute and confirm the location of croppie.js is correct.

Hey Thanks, man, It really solved my problem in one go... Thank you very much

**Comment by prateekvyas2121** [comment]
where can i get croppie.js ?

**Comment by Light-M** [comment]
> Found this by google. It is also a problem, if you include later a second, older, version of jquery ;)

Solved my problem...Thanks!

**Comment by faridmzd** [comment]
<div id="modal">
    <div id="main-cropper"></div>
    <a class="button actionUpload">
        <span>Upload</span>
        <input type="file" id="upload" value="Choose Image" accept="image/*">
    </a>
    <button class="actionDone">Done</button>
    <button class="actionCancel">Cancel</button>
</div>


<script>

    var basic = $('#main-cropper').croppie({
        viewport: { width: 250, height: 250 },
        boundary: { width: 300, height: 300 },
        showZoomer: false
       
    });

    function readFile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                basic.croppie('bind', {
                    url: e.target.result
                });
                $('.actionDone').toggle();
                $('.actionUpload').toggle();
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $('.actionUpload input').on('change', function () { readFile(this); });
    $('.actionDone').on('click', function () {
        $('.actionDone').toggle();
        $('.actionUpload').toggle();
    })


</script>

**and add jquery and croppie js croppie css also )

**Comment by jurri** [comment]
I get everytime: Uncaught TypeError: $(...).croppie is not a function
if I dont use minified file.

same porblem with npm
