### ISSUE TITLE
I have created https server on node server and after that i am not able to get the socket.io.js here is my code:

### ISSUE THREAD

**Issue by brij-mohan** [Foliotek/Croppie#374]
var fs 		= require('fs');
var server 	= require('https');
var express = require('express'); 
var app 	= express();

// This is needed if the app is run on heroku:

var port = process.env.PORT || 8181; 
//var port = process.env.HTTPS_PORT || 8181;

// Initialize a new socket.io object. It is bound to 
// the express app, which allows them to coexist.
httpsServer = server.createServer({
      key: fs.readFileSync('my.agentmx.com.key'),
      cert: fs.readFileSync('my.agentmx.com.crt'), 
      ca: fs.readFileSync('my.agentmx.com.ca-bundle')
    }, app).listen(port); 

//var io = require('socket.io').listen(app.listen(port));

var io = require('socket.io')(httpsServer);
// Require the configuration and the routes files, and pass
// the app and io as arguments to the returned functions.

require('./config')(app, io);
require('./routes')(app, io);

var url = require('url');

console.log('Your application is running on http://my.agentmx.com:' + port);

**Comment by thedustinsmith** [comment]
I think you're in the wrong github repo.  Try this one: https://github.com/socketio/socket.io

**Comment by brij-mohan** [comment]
Thank you thedustinsmith.
