### ISSUE TITLE
Demo HTML missing

### ISSUE THREAD

**Issue by nueverest** [Foliotek/Croppie#38]
Maybe it is obvious to everyone else, but it would be nice to see the HTML file in the demo directory. That would get me off to a quick start.

**Comment by thedustinsmith** [comment]
If you're talking about the html driving http://foliotek.Github.io/Croppie,
it's the index.html in the root of the project.  If we moved it to the demo
folder, github pages wouldn't work without more effort.

**Comment by thedustinsmith** [comment]
[here's the file](https://github.com/Foliotek/Croppie/blob/master/index.html)

**Comment by hrlwfres** [comment]
Actually, it is not clear what the minimal HTML to use for a single example. Your demo contains a lot of extra stuff.

**Comment by hrlwfres** [comment]
`<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/croppie.css?v=1.0">

  
</head>

<body>
	<div class="demo-wrap upload-demo">
		<div class="actions">
			<input type="file" id="upload" value="Choose a file" accept="image/*" />
			<button class="upload-result">Result</button>
		</div>
	</div>
	<div>
		<img id="crop-result" src="" />
	</div>
	<div id="upload-demo"></div>
	 
	<script src="js/jquery-1.12.1.min.js"></script>
	<script src="js/croppie.js"></script>
	<script>
	
	demoUpload();
	
	function demoUpload() {
		var $uploadCrop;

		function readFile(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();
				
				reader.onload = function (e) {
					$uploadCrop.croppie('bind', {
						url: e.target.result
					});
					$('.upload-demo').addClass('ready');
				}
				
				reader.readAsDataURL(input.files[0]);
			}
			else {
				swal("Sorry - you're browser doesn't support the FileReader API");
			}
		}

		$uploadCrop = $('#upload-demo').croppie({
			viewport: {
				width: 1000,
				height: 525,
				type: 'square'
			},
			boundary: {
				width: 1100,
				height: 585
			},
			showZoomer: false
		});

		$('#upload').on('change', function () { readFile(this); });
		$('.upload-result').on('click', function (ev) {
			$uploadCrop.croppie('result', {
				type: 'canvas',
				size: 'viewport',
				format: 'jpeg'
			}).then(function (resp) {
				$("#crop-result").attr("src", resp);
				popupResult({
					src: resp
				});
			});
		});
	}
	</script>
</body>
</html>
`

**Comment by hrlwfres** [comment]
`<body>
	<div class="demo-wrap upload-demo">
		<div class="actions">
			<input type="file" id="upload" value="Choose a file" accept="image/*" />
			<button class="upload-result">Result</button>
		</div>
	</div>
	<div>
		<img id="crop-result" src="" />
	</div>
	<div id="upload-demo"></div>
	 
	<script src="js/jquery-1.12.1.min.js"></script>
	<script src="js/croppie.js"></script>
	<script>
	
	demoUpload();
	
	function demoUpload() {
		var $uploadCrop;

		function readFile(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();
				
				reader.onload = function (e) {
					$uploadCrop.croppie('bind', {
						url: e.target.result
					});
					$('.upload-demo').addClass('ready');
				}
				
				reader.readAsDataURL(input.files[0]);
			}
			else {
				swal("Sorry - you're browser doesn't support the FileReader API");
			}
		}

		$uploadCrop = $('#upload-demo').croppie({
			viewport: {
				width: 1000,
				height: 525,
				type: 'square'
			},
			boundary: {
				width: 1100,
				height: 585
			},
			showZoomer: false
		});

		$('#upload').on('change', function () { readFile(this); });
		$('.upload-result').on('click', function (ev) {
			$uploadCrop.croppie('result', {
				type: 'canvas',
				size: 'viewport',
				format: 'jpeg'
			}).then(function (resp) {
				$("#crop-result").attr("src", resp);
				popupResult({
					src: resp
				});
			});
		});
	}
	</script>
</body>`

**Comment by nueverest** [comment]
I agreed with hrlwfres.

**Comment by thedustinsmith** [comment]
I see what you're asking.  Sorry, I misunderstood.

I'll add the minimum html & js that powers the top croppie before the `Usage` section.  I can see how that large chunk of code would be distracting.

Sorry about the confusion.

**Comment by hrlwfres** [comment]
I gave it a try this morning for the upload and crop example.

`<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/croppie.css?v=1.0">

  
</head>

<body>
	<div class="demo-wrap upload-demo">
		<div class="actions">
			<input type="file" id="upload" value="Choose a file" accept="image/*" />
			<button id="crop_button">Result</button>
			<button id="erase_button">Erase</button>
		</div>
	</div>
	<div id="upload-demo"></div>
	
	<div>
		<img id="crop-result" src="" />
		<input type="hidden" id="crop_result_input"/>
	</div>
	 
	<script src="js/jquery-1.12.1.min.js"></script>
	<script src="js/croppie.js"></script>
	<script>
	
	cropGenerator($("#upload-demo"),$("#upload"), $("#crop_button"), $("#erase_button"), $("#crop-result"), $("#crop_result_input"), 1000, 525);
	
	function cropGenerator(uploadDiv, uploadInput, cropButton, eraseButton, cropResultImage, cropResultInput, width, height) {
		eraseButton.hide();
		var $uploadCrop;

		function readFile(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();
				
				reader.onload = function (e) {
					$uploadCrop.croppie("bind", {
						url: e.target.result
					});
				}
				
				reader.readAsDataURL(input.files[0]);
			}
			else {
				swal("Sorry - your browser doesnt support the FileReader API");
			}
		}

		$uploadCrop = uploadDiv.croppie({
			viewport: {
				width: width,
				height: height,
				type: "square"
			},
			boundary: {
				width: width + 50,
				height: height + 50
			},
			showZoomer: false
		});

		uploadInput.on("change", function () { readFile(this); });
		cropButton.on("click", function (ev) {
			$uploadCrop.croppie("result", {
				type: "canvas",
				size: "viewport",
				format: "jpeg"
			}).then(function (resp) {
				cropResultImage.attr("src", resp);
				uploadDiv.hide();
				cropButton.hide();
				eraseButton.show();
				cropResultInput.val(resp);
			});
		});
		
		eraseButton.on("click", function (ev) {
			cropButton.show();
			cropResultImage.attr("src", "");
			uploadDiv.show();
			eraseButton.hide();
			cropResultInput.val("");
		});
	}
	</script>
</body>
</html>
`

**Comment by hrlwfres** [comment]
I gave it a try this morning : 
[TestCrop.zip](https://github.com/Foliotek/Croppie/files/172210/TestCrop.zip)

It is an "upload and crop" example. I added an input element wich collect the base64 data (for form upload purpose)

Congratulation on this tool btw!

**Comment by pray4snow2** [comment]
> I added an input element wich collect the base64 data (for form upload purpose)

I thank you for your TestCrop.zip work. That helped me a lot. My only question is what to do with the result so I can upload it? I already have a php script to upload an image, but how do I use your input element to grab the result. Any suggestions hrlwfres??

**Comment by hrlwfres** [comment]
I am not sure to understand the question :)
You chose a file, then you crop it, then the base64 data is stored in the input element as a string. 
Once you are here, when the form containing this input is submitted, you only have to decode the base64 string and store it on your server.

Image -> cropie -> base64 encode -> form validated, data send to server side -> base64 decode -> store on drive

I am not a PHP player so I can't help you with some chunk of code :)
