### ISSUE TITLE
Laravel - create croppie img in store method

### ISSUE THREAD

**Issue by majweb** [Foliotek/Croppie#385]
When I create tool I want to croppie image and save to DB:

        $tool = new Tool();
        $tool->przyrzad = $request->przyrzad;
        $tool->ilosc = $request->ilosc;
        if ($request->hasFile('photo'))
        {
            $image = $request->file('photo');
            $imagename = uniqid('przyrzad_').'.jpg';
            $image->storeAs('public/obiekty/przyrzady/', $imagename);
            $tool->photo = $imagename;
        }
        $user = Sentinel::getUser()->gym;
        $user->tools()->save($tool);

I found this method. How implements this in store method?

        $img = $request->photo;

        list($type, $img) = explode(';', $img);
        list(, $img)      = explode(',', $img);

        $img = base64_decode($img);
        $imagename = uniqid('przyrzad_').'.jpg';
        file_put_contents(storage_path().'/app/public/'.$imagename, $img);

**Comment by thedustinsmith** [comment]
Sorry ... as you might have noticed ... You'll have better luck finding help with issues like this on StackOverflow or a more laravel specific site:

https://laravel.io/forum/02-17-2014-how-do-you-save-image-to-database-and-display-it-on-website

For what it's worth, I agree with them, I woudln't save an image to the database.  Saving paths is a way better idea.
