### ISSUE TITLE
Feature request: Rectangluar image despite circle viewport

### ISSUE THREAD

**Issue by hardcodet** [Foliotek/Croppie#386]
I'm using a circle viewport because I'm showing my users' avatars in circles, and this gives the user a great UX that shows how the cropped image will look. However, in order to be future-proof, I'd very much not want to store the images as circles, but rectangles. Is there a way to keep the nice circle editing UX, but store the cropped pictures as a square without resorting to hackery with a custom circle overlay?

Thanks!

**Comment by cromartie1984** [comment]
Yes : 
```
imageCrop.croppie('result', {
                                                        type: 'blob',
                                                        quality: 0.8,
                                                        format: "jpeg",
                                                        circle:   false
                                                    }).then(function (resp) {
}

you put on circle : false
```

**Comment by hardcodet** [comment]
Awesome! I tried that one but probably made a typo because it didn't apply that. Tried it again and it was working. Thanks so much for taking the time Guillaume!

**Comment by thedustinsmith** [comment]
Thanks @cromartie1984
