### ISSUE TITLE
any way to get the result automatically just sending parameter with javascript( without display the viewport and preview .. just the result?)

### ISSUE THREAD

**Issue by guillermochalliol** [Foliotek/Croppie#387]

**Comment by thedustinsmith** [comment]
Possibly, but it's tricky.  The Croppie element has to be visible so we can get positions via the DOM API.  My suggestion would be to put your croppie elements inside a div that you position way off the screen.  That could work.  

Let me know how it goes.

Sorry the response was so delayed.

**Comment by guillermochalliol** [comment]
thedustinsmith: thanks but i solve it using other way.
