### ISSUE TITLE
Croppie bind url in bootstrap modal

### ISSUE THREAD

**Issue by majweb** [Foliotek/Croppie#389]
Hello. Why when i used croppie bind in modal i have empty box without image. When i doesn't used modal its works fine.

**Comment by AdrianPiechota** [comment]
Try to initialize Croppie after modal is shown (on `shown.bs.modal` event):

````
modalElement.on('shown.bs.modal', function () {
    // Initialize Croppie here
 });
````

Worked for me.

**Comment by thedustinsmith** [comment]
Thanks for the help.  Closing due to no response.

**Comment by richard-naud** [comment]
Ohhhhh nice! It solved my problem!! Thank!!

**Comment by deepanmas** [comment]
Thanks, It saved my time. Worked for me too!
