### ISSUE TITLE
Zoom Out

### ISSUE THREAD

**Issue by Skariach** [Foliotek/Croppie#390]
Hi,
I think it's not a issue is just i don't know how to do it :S
When i zoom out the image (cr-slider min at 0.500 for example)  and the image is little than the viewport, i can't move the image, it is stuck at bottom-right.

**Comment by thedustinsmith** [comment]
I believe you have `enforceBoundary: false` ... if you don't want the image to get smaller than the viewport, you should set that to `true`.

**Comment by thedustinsmith** [comment]
Closing due to no response.
