### ISSUE TITLE
Is Croppie Download Up To Date

### ISSUE THREAD

**Issue by captainrod** [Foliotek/Croppie#402]
I could not find the version number of the Croppie download. What is the most up to date version number and is the download the most current version?

Thank You

**Comment by thedustinsmith** [comment]
This is pretty standard across github, but just so you know ... most repo's these days utilize "releases"  ... you can find Croppie's here: https://github.com/Foliotek/Croppie/releases

2.5.0 is the latest release.  As far as the "download" you're talking about.  I have no idea.
