### ISSUE TITLE
How can I use croppie in reactjs?

### ISSUE THREAD

**Issue by carloscba** [Foliotek/Croppie#406]
I've used croppie very well with angularjs and now I want include in my reactjs projects. I'm very apreciate if anyone have a example to share.

**Comment by thedustinsmith** [comment]
This would be a good place to seek help: https://github.com/arssly/react-coppie.  Or at least get you a start.  Sounds like the dev has stopped work on it, but maybe you can help out.

I don't have the time to do any kind of react + croppie work.

**Comment by JWLangford** [comment]
Don't know if anyone is still looking at this, but I'll share how I used croppie in my react application
I'm using react + typescript + Material-UI

```
import "croppie/croppie.css"
import { Button, Grid } from "@material-ui/core"
import * as React from "react"
import Croppie from "croppie"

export function CroppieExample() {
  const [image, setImage] = React.useState("")
  const [croppie, setCroppie] = React.useState<Croppie | null>(null)

  function handleImage(image: string) {
    setImage(image)
    const el = document.getElementById("image-helper")
    if (el) {
      const croppieInstance = new Croppie(el, {
        enableExif: true,
        viewport: {
          height: 250,
          width: 250,
        },
        boundary: {
          height: 280,
          width: 400,
       }
    });
    croppieInstance.bind({
      url: image,
    });
    setCroppie(croppieInstance)
    }
  }

  function handleSubmit(event: any) {
    event.preventDefault()
    if (croppie !== null) {
      croppie.result({type: 'base64',
      size: {
          width: 480,
          height: 480
      }}).then((blob) => {
        console.log(blob)
      }
      )
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <Grid container spacing={2}>
        {image === "" && (
            <Grid item xs={12}>
                {/* Your image upload functionality here */}
                <ImageUpload image={image} setImage={handleImage} />
            </Grid>
            )}
        {image !== "" && (
            <Grid item container justify="center" xs={12}>
              <div id="image-helper"></div>
            </Grid>
            )}
        <Grid container item xs={12} justify="flex-end">
          <Button color="primary" variant="contained" type="submit">
            Submit
          </Button>
        </Grid>
      </Grid>
    </form>
  )
}

```

**Comment by teddy3728** [comment]
very good sample. thanks

**Comment by ChrisFromLafare** [comment]
> Don't know if anyone is still looking at this, but I'll share how I used croppie in my react application
> I'm using react + typescript + Material-UI
> 
> ```
> import "croppie/croppie.css"
> import { Button, Grid } from "@material-ui/core"
> import * as React from "react"
> import Croppie from "croppie"
> 
> export function CroppieExample() {
>   const [image, setImage] = React.useState("")
>   const [croppie, setCroppie] = React.useState<Croppie | null>(null)
> 
>   function handleImage(image: string) {
>     setImage(image)
>     const el = document.getElementById("image-helper")
>     if (el) {
>       const croppieInstance = new Croppie(el, {
>         enableExif: true,
>         viewport: {
>           height: 250,
>           width: 250,
>         },
>         boundary: {
>           height: 280,
>           width: 400,
>        }
>     });
>     croppieInstance.bind({
>       url: image,
>     });
>     setCroppie(croppieInstance)
>     }
>   }
> 
>   function handleSubmit(event: any) {
>     event.preventDefault()
>     if (croppie !== null) {
>       croppie.result({type: 'base64',
>       size: {
>           width: 480,
>           height: 480
>       }}).then((blob) => {
>         console.log(blob)
>       }
>       )
>     }
>   }
> 
>   return (
>     <form onSubmit={handleSubmit}>
>       <Grid container spacing={2}>
>         {image === "" && (
>             <Grid item xs={12}>
>                 {/* Your image upload functionality here */}
>                 <ImageUpload image={image} setImage={handleImage} />
>             </Grid>
>             )}
>         {image !== "" && (
>             <Grid item container justify="center" xs={12}>
>               <div id="image-helper"></div>
>             </Grid>
>             )}
>         <Grid container item xs={12} justify="flex-end">
>           <Button color="primary" variant="contained" type="submit">
>             Submit
>           </Button>
>         </Grid>
>       </Grid>
>     </form>
>   )
> }
> ```

Hi everybody

Are you sure this example works?
It seems by the time handleImage event is called, <div id="image-helper"></div> is not rendered in the DOM, hence no croppieInstance is initialized. Am I right?

**Comment by ghost** [comment]
@ChrisFromLafare his code didn't work correctly for me too. The main problem was with file. So I take a part of solution from https://codesandbox.io/s/k5n1l3zym3?file=/src/index.js:844-916

And I got smth like this (it's ugly code just to make sure this solution works)
```
import React from 'react';
import Croppie from 'croppie';

// styled
import * as S from './styled';

import 'croppie/croppie.css';

export function CropAvatar() {
    const [image, setImage] = React.useState('');
    const [blob, setBlob] = React.useState('');
    const [croppie, setCroppie] = React.useState<Croppie | null>(null);

    const handleImage = (event: any) => {
        console.log('image', event.target.files);
        console.log('image', event.target.files[0]);
        const image = event.target.files[0];
        setImage(image);
        const el = document.getElementById('image-helper');
        const reader = new FileReader();
        reader.readAsDataURL(image);
        if (el) {
            console.log('EL', el);
            const croppieInstance = new Croppie(el, {
                enableExif: true,
                viewport: {
                    height: 250,
                    width: 250,
                },
                boundary: {
                    height: 280,
                    width: 400,
                },
            });
            reader.onload = () => {
                // @ts-ignore
                croppieInstance.bind({ url: reader.result });
            };
            // croppieInstance.bind({
            //     url: image,
            // });
            setCroppie(croppieInstance);
        }
    };

    const handleSubmit = (event: any) => {
        console.log('sncscbscscscsc');
        event.preventDefault();
        if (croppie !== null) {
            croppie
                .result({
                    type: 'base64',
                    size: {
                        width: 480,
                        height: 480,
                    },
                })
                .then((blob) => {
                    console.log(blob);
                    setBlob(blob);
                });
        }
    };

    return (
        <S.CroppModal isShown>
            <div>
                <div>
                    <input type="file" id="files" onChange={handleImage} />
                </div>
                <div>
                    <div id="image-helper" />
                </div>
                <div>
                    <button type="button" onClick={handleSubmit}>
                        Submit
                    </button>
                </div>
                <img src={blob} alt="result" />
            </div>
        </S.CroppModal>
    );
}

export default CropAvatar;
```
