### ISSUE TITLE
Tainted Canvas problem

### ISSUE THREAD

**Issue by thibaultvanluchene** [Foliotek/Croppie#407]
What's going wrong?

<img width="1390" alt="screen shot 2017-10-24 at 22 43 19" src="https://user-images.githubusercontent.com/8404502/31967065-03a6a16e-b90d-11e7-8cf6-a84c8a154c3d.png">

**Comment by thibaultvanluchene** [comment]
The image source is form the root folder.

**Comment by thedustinsmith** [comment]
It's been a while, but if I recall correctly CORS is pretty difficult to get to work with the `file:\\` protocol.  Two recommendations:
1. Use a static web server.  I use `nodejs` `npm` and `npm install live-server`.
2. Google "CORS file protocol tained canvas" and see if you find an answer elsewhere.

**Comment by thibaultvanluchene** [comment]
In FireFox I get the base64 data. 
Chrome and Safari throw an exception.

**Comment by thibaultvanluchene** [comment]
Hi thedustinsmith, thanks for the quick reply. 
I'll try the live-server.
