### ISSUE TITLE
Return rotation data in "Get" method

### ISSUE THREAD

**Issue by drasier** [Foliotek/Croppie#408]
It would be just awesome to have the rotation information in the Get method. I'm trying to handle all the image cropping at server side so I'm sending the points and zoom information but I have to handle and store the rotation degrees separately. Would you be willing to add that param in the crop_data returned by "Get" method?
Thanks a lot, awesome pluggin 👍

**Comment by thedustinsmith** [comment]
Yeah - that seems like an oversight on my part.  If you want to add that and submit a PR, I'd love the help. 

Either way, thanks for the suggestion.

**Comment by thedustinsmith** [comment]
Will be in 2.5.2
