### ISSUE TITLE
outWHeight is not defined

### ISSUE THREAD

**Issue by mhnpc** [Foliotek/Croppie#410]
Hi guys
I'm using Croppie with bootstrap modal like [https://codepen.io/tnrnz/pen/KNKLbN](https://codepen.io/tnrnz/pen/KNKLbN)  but I get the following error in console of browser, this means that when I click on the Crop button, the error goes below:
**ReferenceError: outWHeight is not defined**

**Comment by IDEDOnline** [comment]
Same issue only present when including width and height in result options for me.
Just for trouble shooting purposes the image result being requested is larger than the viewport (depending on resolution), output is base64 jpeg.

**Comment by IDEDOnline** [comment]
Note this issue only appears using the minified version of croppie, if I use the raw version found https://foliotek.github.io/Croppie/croppie.js here the issue disappears, so maybe when being minified the reference is becoming corrupted

**Comment by thedustinsmith** [comment]
Sorry guys, this is known, but to be honest, you shouldn't be referencing the script that way.  If you don't  want download it, you should use the CDN Url ... not Github's.

https://cdnjs.com/libraries/croppie

Official versions are located there ... the github files may not necessarily be an official release.

**Comment by IvanShrt** [comment]
Same error here when trying to use croppie with bootstrap modal. Will try cdn now.

**Comment by IvanShrt** [comment]
Hm, that's totally weird. Even though my local minified file is the same as CDN one it still  @gives me this error. But using CDN src work fine though. -__-

**Comment by mhnpc** [comment]
Thanks

**Comment by nenuadrian** [comment]
Confirmed issue here too, minified version is somewhat corrupted.
