### ISSUE TITLE
Request Entity Too Large iPhone 7 plus Camera Upload

### ISSUE THREAD

**Issue by thecookie12** [Foliotek/Croppie#413]
ANY iPhone photo I use directly from my camera roll taken from the phone gives me this 413 error -
"Request Entity Too Large

The requested resource
/aidan/upload.php
does not allow request data with GET requests, or the amount of data provided in the request exceeds the capacity limit.
Additionally, a 413 Request Entity Too Large error was encountered while trying to use an ErrorDocument to handle the request.}

**Comment by thedustinsmith** [comment]
Have you tried doing a blob result instead of a base64 result?

**Comment by thedustinsmith** [comment]
Closing due to no response.

**Comment by halgatewood** [comment]
I was able to change the croppie setting <code>quality</code> to <code>0.99</code> to get this to stop. It decreased my file sizes by 4x making the request to the server smaller. I cannot tell a difference in the outcome. I assume you could probably go even lower on the quality to make the crop feel more responsive.

    basic.croppie('result', {
		type: 'base64',
		quality: '0.99',
		format: 'jpeg',
		size: {width: 1280, height: 720}
	}).then(function (resp) { } );
