### ISSUE TITLE
enableResize not functional for iOS

### ISSUE THREAD

**Issue by arthurcannon** [Foliotek/Croppie#414]
Ver. 2.5.1 of Croppie does not initialize resizing of the viewport functionally on iOS devices. After examining your code, I found a solution that worked for me, so I thought that I should let you know, so you can examine it and decide the best overall solution.

Problem: iOS does not fire mousedown event when you touch the screen in most situations, and code relies on aforementioned event as it's sole means of operation.

Implemented Solution: Add two lines of code initiating operation using touchstart event as well as mousedown event.

edited lines of code:
```
        if (vr) {
            vr.addEventListener('mousedown', mouseDown);
            vr.addEventListener('touchstart', mouseDown);
        }

        if (hr) {
            hr.addEventListener('mousedown', mouseDown);
            hr.addEventListener('touchstart', mouseDown);
        }
```

**Comment by thedustinsmith** [comment]
Looks good.  Submit a PR, and I can get it merged in.
