### ISSUE TITLE
How to Flip Croppie image Horizontal Mirror | Reverse Horizontal

### ISSUE THREAD

**Issue by iLearnAndCode** [Foliotek/Croppie#417]
Hello, first I want to thank you for an awesome plugin for cropping image,
I'm new here in github and i created this account just to post this issue that I don't know to solve.
I'm fairly new to jquery/javascript so I still don't quite understand how your plugin works. I'm sorry :[

I want to have a button that flips the image vertically and horizontally and reverse horizontal before uploading it to my server.

And I'm having problem flipping the croppie in reverse horizontal not just rotating it. 
In your demo I saw how you rotate image by degrees and only flip horizontal works for me.

So I want to know how to achieve flip croppie Horizontal Mirror | Reverse Horizontal on button click.

This is the original orientation.
![download](https://user-images.githubusercontent.com/33442190/32477419-eb6af3fa-c3b8-11e7-9f55-dbd3021d7284.jpg)

Flip it Horizontal Mirror | Reverse Horizontal on button click
![download-convertimage](https://user-images.githubusercontent.com/33442190/32477437-223d55d0-c3b9-11e7-9b62-99cdceb065b8.jpg)

I don't know if I'm clear enough but you'll get the idea.
Any help will be appreciate :) Thanks

**Comment by kanatkubash** [comment]
Something like this ?
https://jsfiddle.net/afb76b7f/54/

**Comment by iLearnAndCode** [comment]
Yes! that's it! Thank you so much and after i've seen your fiddle, I finnaly understand how the orientation works! :+1:

**Comment by kanatkubash** [comment]
You're welcome.
