### ISSUE TITLE
Rotate to any degree

### ISSUE THREAD

**Issue by kanatkubash** [Foliotek/Croppie#418]
Hello,
Thank you for wonderful library
Is it possible to rotate the image by angles other than 90 or 180 degrees?

**Comment by thedustinsmith** [comment]
This isn't built into the croppie API, but what you can do is use the result method to get the `rawcanvas` result ... and then manipulate the canvas by rotating it yourself.

Here's a SO post ... not sure if it's any good, but I'm sure there are tons of others: https://stackoverflow.com/questions/17411991/html5-canvas-rotate-image

**Comment by kanatkubash** [comment]
I meant rotating and cropping , just like moving picture before cropping
Anyways, thanks for clarification.

**Comment by rob-lindman** [comment]
I haven't worked out 'any angle' yet because there are issues in croppie which I've reported, but you can rotate and flip using code I put here. 
https://github.com/Foliotek/Croppie/issues/506
