### ISSUE TITLE
Can't move the image vertically in default Android browser

### ISSUE THREAD

**Issue by Andromidas** [Foliotek/Croppie#42]
Using version 4.4.2. 
Moving fine horizontally.
Moving fine in both directions in Chrome on Android, but not in the default browser.

**Comment by k-lusine** [comment]
The same issue on mozilla for android. Moving it vertically scrolls the window

**Comment by teamandrei** [comment]
yes. this. same issue with vertical scrolling in default browser and adblock browser.
