### ISSUE TITLE
Generate Image with dark line left and top issue

### ISSUE THREAD

**Issue by manektechmehul** [Foliotek/Croppie#430]
Hi,
I am using croppie js for crop image using base64, when I am save my form with image, the image generate the left and top with dark border.

**Comment by thedustinsmith** [comment]
We're going to need a lot more information ... sounds like you have `enforceBoundary: false`?  

It sounds like what may be happening is you're only cropping the top left part of the image, so the top left part of the canvas is empty, I believe some browsers fill the blank space with `#000`, but without seeing an example of the issue, it's hard to say whether or not that's the case.
