### ISSUE TITLE
Wrong image position after second upload

### ISSUE THREAD

**Issue by hhjung2013** [Foliotek/Croppie#433]
When you crop an uploaded image for the first time the result is fine. When you upload a seond image and crop it the result has wrong postitions. This behaviour can be reproduced on the upload demo:

![unbenannt](https://user-images.githubusercontent.com/28895406/33765524-8305311c-dc19-11e7-837c-0c561377f2af.JPG)

The wrong positions get worse when you change the container dimensions to e.g. 300px x 200px via CSS as done in the screenshot.

**Comment by thedustinsmith** [comment]
thanks for the issue, but it's the same as #352 - it'll be fixed in 2.5.2
