### ISSUE TITLE
How to rotate the viewport？

### ISSUE THREAD

**Issue by Mmzer** [Foliotek/Croppie#446]
After reading the document, I know I can rotate the picture, I need to rotate the viewport what should I do?

**Comment by thedustinsmith** [comment]
Sounds like what you're wanting to do is swap the viewport dimensions.  Unfortunately, we still don't have a way to change properties of an already initialized croppie instance, but what you can do is destroy and recreate your croppie with your viewport.height and viewport.width swapped.
