### ISSUE TITLE
Query related to image straighten functionality.

### ISSUE THREAD

**Issue by bhavikvaishnani** [Foliotek/Croppie#447]
Hello,
I am using Croppie tool for image cropping. Now I need to implement image straightening in my project.
I have searched a lot related to it but didn't get any satisfactory solution. 
As Croppie support Flip and Rotate functionality.
 So do Croppie support straightening functionality too?  
If not, then how can I achieve the same? 
Kindly guide on the same.

**Comment by thedustinsmith** [comment]
Sorry, but there are no plans to do image straightening.  I don't think Croppie is the place for it.  For me, the expected behavior would be for the image to be straightened before it's sent to croppie.
