### ISSUE TITLE
Need to get round and square both cropped image at once.

### ISSUE THREAD

**Issue by naitikpatel1990** [Foliotek/Croppie#449]
Hi,

I am using tool which is awesome.

But i have one scenario i need to crop image in square and circle both at one time. Means user copped image in square , i need it's output in square and circle both, is it possible?

I need to ser cropped set as circle and square both, but i want to set only one time user crop input.

Thank you.

**Comment by Textras** [comment]
If anyone has done this, or has any ideas I'd be interested in this also. We'd like to use a circle avatar on Google maps which requires a circle URL and cannot be masked (our current user avatars are square and of course we do not want to ask the user to crop twice) cc @thedustinsmith maybe any ideas?

**Comment by thedustinsmith** [comment]
Maybe I'm misunderstanding something, but can't you do...

```
$myCroppie.croppie('result', {
  type: 'base64',
  format: 'png'
}).then(function(){ // do something with square result});

$myCroppie.croppie('result', {
  type: 'base64',
  format: 'png',
  circle: true
}).then(function() { // do something with circle result });
```

**Comment by naitikpatel1990** [comment]
Thanks @thedustinsmith , I already did same way and i got output as i needed.
