### ISSUE TITLE
Debounce update event on mouseWheelZoom / drag zoom slider too

### ISSUE THREAD

**Issue by Aerue** [Foliotek/Croppie#45]
It should be usefull if the update event was debounce too on mouseWheelZoom / drag zoom slider. I have implemented that to my own purpose, but it should good for everyone ?

```javascript
update: utils.debounce(function(cropper) {
    console.log('update : ' , cropper);
    // Now we refresh the result
    $uploadCrop.croppie('result', {
        type: 'canvas',
        size: 'viewport'
    }).then(function (resp) {
        var $attachmentSubmit = $('.attachment.attachment-output');
        if ($attachmentSubmit.next('img').length) {
            $attachmentSubmit.next('img').attr('src', resp);
        } else {
            $attachmentSubmit.after('<img src="' + resp + '" />');
        }
    });
})
```

**Comment by thedustinsmith** [comment]
Thanks for the suggestion!  I can see why you'd want to debounce that update event (especially for a mouse wheel zoom), but personally I don't think that should be done by the API.  IMO that should be handled by the API user.

@ecalvert - have any thoughts on this?

**Comment by ecalvert** [comment]
Some users might like having that function called immediately.  Easier for an API user to add the functionality than always debouncing the update event, since you can't really un-debounce a debounced function

**Comment by Aerue** [comment]
After rethink that I agree with the way of thinking of ecalvert
