### ISSUE TITLE
croppie is not exporting at the correct size

### ISSUE THREAD

**Issue by An-AngryBear** [Foliotek/Croppie#453]
$('#save-img').on('click', function (event) {
    basic.croppie('result', 'canvas', {
        size: {
            width: 400,
            height: 400
        }
    }).then( (data) => {
        addUserImage(data)
        .then( (data2) => {
            console.log("Image added");
        });
    });
});

croppie seems to only export in whatever the viewport size is.  and completely disregards the size property.

Ive tried changing the result type, but it's always the same.

version 2.5.1

**Comment by thedustinsmith** [comment]
The signature for the result method has two options ... either you pass in only the result type
`result('canvas')`
or you pass in options
`result({type: 'canvas', ...})`

```
$('#save-img').on('click', function (event) {
	basic.croppie('result', {
		type: 'canvas',
		size: {
			width: 400,
			height: 400
		}
	}).then( (data) => {
		addUserImage(data)
			.then( (data2) => {
			console.log("Image added");
		});
	});
});
```

**Comment by An-AngryBear** [comment]
ahhh ok thanks ill give it a go!

**Comment by An-AngryBear** [comment]
works great. thanks for quick reply 👍
