### ISSUE TITLE
Site navigation not working

### ISSUE THREAD

**Issue by MarioJuniorPro** [Foliotek/Croppie#464]
## Expected Behavior
Access link

## Steps to Reproduce the Problem

  1. Access https://foliotek.github.io/Croppie/
  2. Try to navigate in Documentation or Demos links
  1.
  
## Specifications

  - Browser: Chrome
  - Version:

**Comment by thedustinsmith** [comment]
Weird.  Thanks for the heads up.  

Maybe it's caused by us not closing a tag somewhere?  Just doing `$('body').scrollTop(100)` doesn't do anything either.

**Comment by thedustinsmith** [comment]
This is fixed.  Thanks again.
