### ISSUE TITLE
Problem (doubt) to upload file before croppie

### ISSUE THREAD

**Issue by MarceloBonifazio** [Foliotek/Croppie#467]
I need to upload an image to the server, and just use the library, but before uploading the user may already have an image, I'm having trouble using the library in the current image, if I decide to crop the image without uploading another image, and if the user decides to "reset" the image, I dont understand where I'm wrong.

Apparently it has to do with base64 date conversion:

> croppie.js:1029 Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

This is my code where conversion should be done:

		var $uploadCrop;
	
		$(function () {
			$('[data-toggle="tooltip"]').tooltip();
			
			jQuery('.crop').on('click', function() {
				$uploadCrop.croppie('result', {
					type: 'canvas',
					size: 'viewport'
				}).then(function(resp) {
					popupResult({
						src: resp
					});
				});
			});
			
			$uploadCrop = $('.thumbnail').croppie({
				enableExif: true,
				viewport: {
					width: 200,
					height: 200,
					type: 'circle'
				},
				boundary: {
					width: 300,
					height: 300
				},
				customClass: 'thumbnail',
				url: 'https://lorempixel.com/640/480/city/'
			});
		});
		function readURL(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();
				
				reader.onload = function (e) {
					$uploadCrop.croppie('bind', {
						url: e.target.result
					});
				}
				reader.readAsDataURL(input.files[0]);
			}
		}
		$(".file").change(function(){
			readURL(this);
		});
		$(".clear").on("click", function () {
			$uploadCrop.croppie('bind', {
				url: 'https://lorempixel.com/640/480/city/'
			});
			$('.cropped').attr("src", "");
			$('.file').val('');
		});
		
		function popupResult(result) {
			var html;
			if (result.html) {
				jQuery(".cropped").val(html);
				jQuery(".picture").attr("src", html);
			}
			if (result.src) {
				jQuery(".cropped").attr("src", result.src);
				jQuery(".picture").val(result.src);
			}
		}
  
[Fiddle for the probleam](https://jsfiddle.net/on3egavx/)

**Comment by mohittyagi6677** [comment]
@MarceloBonifazio i am having the same issue. Were you able to solve it and how ?
