### ISSUE TITLE
enforce aspect ration with a min width/height

### ISSUE THREAD

**Issue by staabm** [Foliotek/Croppie#468]
we want a cropper to allow the user to crop a area with a fixed aspect ratio but also restrict the min width or/and height.

lets say I want the user to crop the image to a 4/3 aspec ratio with 300 width.
he is allowed to use a bigger width as long as the aspect ratio fits (when the user increases width or height the cropping area should automatically reflect the aspect ratio).

after the user e.g. pick a 4/3 area with a width of 500 px, the cropper should this image rectangle down-sized to 300px in 4/3.

**Comment by thedustinsmith** [comment]
Sorry, I'm having a hard time understanding ... 

Are you saying you want the viewport to maintain an aspect ratio? 
![image](https://user-images.githubusercontent.com/1330308/35976755-b88e385c-0ca6-11e8-88b9-718dbb5e2f30.png)

Meaning when you resize the width of the view port, the height would also change to maintain a 4/3 aspect ratio?  

If that's what you mean, I would suggest not using the viewport resizing feature.  The original intention of croppie was to force images to crop to a consistent aspect ratio, the viewport resizing was a feature that someone else wanted and built on top of this.  

The resizing viewport doesn't fall within my usecases of this tool, so there's a slim chance this will ever get worked on unless someone else submits a pull request.  Assuming I'm describing what you're wanting.

**Comment by staabm** [comment]
> Meaning when you resize the width of the view port, the height would also change to maintain a 4/3 aspect ratio?

exactly.


> If that's what you mean, I would suggest not using the viewport resizing feature. The original intention of croppie was to force images to crop to a consistent aspect ratio, the viewport resizing was a feature that someone else wanted and built on top of this.

since the user should be able to adjust width/height of the viewport, this doesnt make sense in my case.



> The resizing viewport doesn't fall within my usecases of this tool, so there's a slim chance this will ever get worked on unless someone else submits a pull request. Assuming I'm describing what you're wanting.

I see thx. I guess https://github.com/fengyuanchen/cropperjs will provide what I need.
