### ISSUE TITLE
Hi please advice, how to use in angular 2??

### ISSUE THREAD

**Issue by rajeshtbabu** [Foliotek/Croppie#469]
## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications

  - Browser:
  - Version:

**Comment by thedustinsmith** [comment]
Try this: https://github.com/deej81/ngx-croppie
this: https://github.com/gatimus/angular-croppie
this: https://github.com/allenRoyston/ngCroppie/issues/13
or this: https://github.com/jwoehrle/angular2-croppie-example
or this: https://www.google.com/search?q=croppie+angular+2
