### ISSUE TITLE
is there a way that I can change the opacity when trying to zoom in or out?

### ISSUE THREAD

**Issue by laksh95** [Foliotek/Croppie#478]
## Expected Behavior
![screen shot 2018-02-19 at 4 35 25 pm](https://user-images.githubusercontent.com/9084333/36374995-734e25fe-1593-11e8-96bc-00b7ed5ad8fa.png)

## Actual Behavior
If you notice the image outside the viewport is a darker than the one in the viewport. I want to increase that opacity. is it possible? 

## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications

  - Browser:
  - Version:

**Comment by thedustinsmith** [comment]
The shadow comes from our viewport styles: https://github.com/Foliotek/Croppie/blob/master/croppie.css#L34

Some of these styles are mandatory, but the box shadow is not.  If you want to decrease the opacity on the rgba of the box shadow, feel free.

**Comment by laksh95** [comment]
Thanks for the help.
