### ISSUE TITLE
possibly issue with strict mode

### ISSUE THREAD

**Issue by DanielRuf** [Foliotek/Croppie#480]
The AMD / UMD wrapper has an undefined `root` in specific cases where strict mode is used.
In this cases we have to set `root` to `window` if it is defined.

I'll prepare a testcase which demonstrates this (this is often the case with Gulp, webpack and other solutions).

**Comment by nolimits4web** [comment]
Facing same issue, also found this one #481

**Comment by DanielRuf** [comment]
Something like https://github.com/bebraw/libumd/commit/f43a331e7c484ed9c5696d4827d5b16a918ec3bb

https://github.com/dimsemenov/PhotoSwipe/pull/1413

**Comment by DanielRuf** [comment]
More references:

https://github.com/fians/Waves/pull/181
https://github.com/jonathantneal/svg4everybody/issues/162
