### ISSUE TITLE
How to init croppie several times?

### ISSUE THREAD

**Issue by OlegZavrazhin** [Foliotek/Croppie#482]
## Expected Behavior

Hello!
I need to init and hide (or destroy) your plugin for current element.

```
$('#someID').croppie({
   viewport: {
      width: 128,
      height: 128
   }
});
$('#someID').croppie('bind', {
   url: 'some base64 encoded image'
});
```

Then I hide it.

$('#someID').toggle();
$('#someID').croppie('bind');

After all there are cases when I need croppie again and first part of js code works again, so I have in console:

`croppie.min.js:1 Uncaught Error: Croppie: Can't initialize croppie more than once`

And obviously I just have to check initialized plugin for current element now or not. What I found:

```
// it supposed to be the answer, however it doesn't work correctly for me.    
if (!jQuery().fn.croppie) {

       $('#someID').croppie({
           viewport: {
                width: 128,
                height: 128
           }
       });

    }
```

So, how to make sure that plugin initialized now or not? Or I need a hack from you how to init and destroy croppie for the same element several times (not the best way, however the solution too)

## Actual Behavior

Described above.

## Steps to Reproduce the Problem

Described above.

## Specifications

  - Browser: Google Chrome
  - Version: 64.0.3282.140 (Official Build) (64-bit)

**Comment by thedustinsmith** [comment]
Destroy: http://foliotek.github.io/Croppie/#destroy

This doesn't do what you think it does: `if (!jQuery().fn.croppie) {`
Try: `if(!$('#someID').data('croppie'))`

**Comment by iknox27** [comment]
how i can reload cropie with new image ?

**Comment by thedustinsmith** [comment]
http://foliotek.github.io/Croppie/#bind
