### ISSUE TITLE
Croppie Constructor Error

### ISSUE THREAD

**Issue by walimi** [Foliotek/Croppie#487]
When importing croppie with require like below and specifying new Croppie I get an error "Croppie is not a constructor."

var Croppie = require("croppie");

## Steps to Reproduce the Problem

  1. npm install croppie
  2. var Croppie = require("croppie")
  3. var myCroppie = new Croppie(myConatiner, {

});
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications

  - Browser: Chrome 
  - Version: 64.0.3282.167

**Comment by thedustinsmith** [comment]
See: https://github.com/Foliotek/Croppie/issues/470
