### ISSUE TITLE
Uncaught Croppie: Cannot rotate without enableOrientation && EXIF.js included

### ISSUE THREAD

**Issue by jofftiquez** [Foliotek/Croppie#489]
Hi I am planning to upgrade [vue-croppie's](https://github.com/jofftiquez/vue-croppie) Croppie version from `**2.5.0**` to `**2.6.1**`. Upon doing so I noticed that the rotate function doesn't work as it used to. I am now getting the error.

> Uncaught Croppie: Cannot rotate without enableOrientation && EXIF.js included

I checked the docs for `enableExif` and it says "Requires exif.js". Is EXIF.js not included in the new Croppie? Do I need to add it myselft? 

Thanks!

**Comment by thedustinsmith** [comment]
I'm not sure what changed between the two versions to give you this exception, but exif.js has never been included with croppie.  Maybe one day.

Did you set the option `enableOrientation: true` ?  I think the exception is just misleading.  At one point maybe we required exif.js for rotation abilities, but now we don't.  

As far as the code's concerned, I'm pretty sure we can change the exception to 
> "Uncaught Croppie: Cannot rotate without enableOrientation **or** EXIF.js included."

**Comment by jofftiquez** [comment]
@thedustinsmith Yes I agree the exception was a bit misleading. If that's the case I guess that's fine. I got it working by rebuilding the my plugin. It's crazy I don't really know what caused it. But anyways thanks for your time answering this. Kudos!

**Comment by vickyranium** [comment]
@jofftiquez  are you find solution. for this " Uncaught Croppie: Cannot rotate without enableOrientation && EXIF.js included"

**Comment by jofftiquez** [comment]
Hello @vickyRomil sorry for the very late reply. No I haven't figured it out yet.
