### ISSUE TITLE
Cropped image not showing

### ISSUE THREAD

**Issue by sakshisyscom** [Foliotek/Croppie#491]
## Expected Behavior
Cropped image should be shown when we click of 'Result' button

## Actual Behavior
It is not showing cropped image on click of result button.

## Steps to Reproduce the Problem

  1.Download zip folder and extract it and run it in xampp.
  2.Select image portion to be cropped.
  3.Click the result button
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:
http://syscomprojects.com/aaa/Croppie-2.6.1/

## Specifications

  - Browser:Firefox
  - Version:

**Comment by BVazquezAlvarez** [comment]
You have missing libraries, so Croppie is throwing an error:

![screenshot_4](https://user-images.githubusercontent.com/8861685/37090416-91532284-2204-11e8-957f-f536a2cbd1a7.png)

![screenshot_5](https://user-images.githubusercontent.com/8861685/37090420-96b40e6e-2204-11e8-82ec-c0fd6dc38b16.png)

**Comment by sakshisyscom** [comment]
I have included the libraries, still not getting cropped image .

Url:-
http://syscomprojects.com/aaa/Croppie-2.6.1/

**Comment by BVazquezAlvarez** [comment]
Same 404 as before. Check your path (/bower_components/dist) and make sure you've included the libraries.

![screenshot_7](https://user-images.githubusercontent.com/8861685/37092906-cb67055e-220d-11e8-8edb-06d1363af150.png)

**Comment by sakshisyscom** [comment]
Yes, now libraries error is not there. I am getting image tag alert but still not getting cropped image .

Check Url:-
http://syscomprojects.com/aaa/Croppie-2.6.1/

**Comment by sakshisyscom** [comment]
Solved it. Thanks for your interest as well as support.
