### ISSUE TITLE
croppie doesn't work

### ISSUE THREAD

**Issue by ArkadiZav** [Foliotek/Croppie#494]
## Expected Behavior
Croppie should work

## Actual Behavior
Croppie doesn't work

## Example Link
https://codepen.io/TheBigfootCyclop/pen/pLoJbm
![croppie-issue](https://user-images.githubusercontent.com/25530966/37161249-d321d42a-22fa-11e8-80e3-02001fbe4906.png)

## Specifications
  - Browser: any

**Comment by thedustinsmith** [comment]
This isn't a bug.

http://foliotek.github.io/Croppie/#bind

https://www.foliotek.com/devblog/cropping-images-with-javascript-and-croppie-js/

**Comment by ersingenc** [comment]
Hi,
Can someone send working sample of saving cropping file  ?
I am newbie and need it.
Thank you for your helps
