### ISSUE TITLE
Cropping inside modal does not work

### ISSUE THREAD

**Issue by puzzydeztroyer** [Foliotek/Croppie#502]
## Expected Behavior
It should work like it does on regular page

## Actual Behavior

It doesnot

## Steps to Reproduce the Problem

  1. Create modal using bootstrap
  2. Create croopie inside modal
  3. It kind of not work 🤔 
  

## Specifications

  - Browser: every
  - Version: even snapshot

**Comment by thedustinsmith** [comment]
Here's a codepen demonstrating that it does: https://codepen.io/patrickjane/pen/QmgmXL

Please read the documentation before submitting any issues.  Also, please provide a demonstration of the issue.  Closing this because there's nothing I can do with the provided information.
