### ISSUE TITLE
How to check if no file is selected?

### ISSUE THREAD

**Issue by jjaegerjaquez** [Foliotek/Croppie#503]
I already asked this question on Stackoverflow, but no response yet. So pardon if I am asking this here. I am able to crop and upload image on my site. But when I try to upload without selecting an image, a black image is being uploaded.

JS:
```
$image_crop = $('#upload-image').croppie({
	enableExif: true,
	viewport: {
		width: 342,
		height: 192,
		type: 'square'
	},
	boundary: {
		width: 380,
		height: 250
	}
});
```
```
$('#images').on('change', function () {
	var reader = new FileReader();
	reader.onload = function (e) {
		$image_crop.croppie('bind', {
			url: e.target.result
		}).then(function(){
			// console.log('<?php echo base_url() ?>');
		});
	}
	reader.readAsDataURL(this.files[0]);
});
```

```
$('.cropped_image').on('click', function (ev) {
	$image_crop.croppie('result', {
		type: 'canvas',
		size: { width: 1366, height: 768 }
	}).then(function (response) {
		$.ajax({
			url: "<?php echo base_url() ?>Light/upload_home_bg",
			type: "POST",
			data: {"image":response},
			success: function (data) {
        alert(data);
        $(location).attr('href','<?php echo base_url() ?>Light/home');
			}
		});
	});
});
```

Here is my code for uploading image:
`$path = 'uploads/'.$this->data['account']->username.'/';`
`$croped_image = $_POST['image'];`
`list($type, $croped_image) = explode(';', $croped_image);`
`list(, $croped_image)      = explode(',', $croped_image);`
`$croped_image = base64_decode($croped_image);`
`$image_name = time().'.png';`
`file_put_contents($path.$image_name, $croped_image);`

I tried checking if `$_POST['image]` is empty using  `if (!empty($_POST['image'])) {}`, but regardless if I selected an image or not, there are data being passed. (Here is the data being passed *on the alert window [https://i.stack.imgur.com/DtqFD.png](url))

So how can I check if the user selected an image or not?

**Comment by jjaegerjaquez** [comment]
Okay. I finally managed to come up with a solution. Here is what I did:

I passed another value `var file_input = $('#images').val();` on my ajax which hold the value of the file upload.

```
$('.cropped_image').on('click', function (ev) {
	$image_crop.croppie('result', {
		type: 'canvas',
		size: { width: 1366, height: 768 }
	}).then(function (response) {
    var file_input = $('#images').val();
		$.ajax({
			url: "<?php echo base_url() ?>Light/upload_home_bg",
			type: "POST",
			data: {"image":response,"file":file_input},
			success: function (data) {
        alert(data);
        $(location).attr('href','<?php echo base_url() ?>Light/home');
			}
		});
	});
});
```

And then on my php file I check if it is empty:

```
if (!empty($this->input->post('file')))
{
 //Upload code
}
else 
{
 //Prompt user to select an image
}
```

**Comment by sedrak1987** [comment]
thanks
