### ISSUE TITLE
feature? ability to change image with a button or hyperlink

### ISSUE THREAD

**Issue by rob-lindman** [Foliotek/Croppie#505]
I am new to Croppie and I have a requirement to be able to click a button, specify the image that is in Croppie, and then be able to crop it. There could be more than one image that needs to be cropped. I've scanned the issues but it's not clear if this functionality is available? Thanks. 

Please delete this I have been programming all night and not thinking clearly. Of course I found the bind function and this is a brain fart on the internet.

**Comment by thedustinsmith** [comment]
haha we've all been there.  Glad you found something that works for you.
