### ISSUE TITLE
Result image gets distorted

### ISSUE THREAD

**Issue by AlexanderLyon** [Foliotek/Croppie#515]
When uploading an image that's zoomed all the way out (or close to it), the result image sometimes becomes stretched and distorted. The further out I zoom, the more distorted the image becomes. Not sure what's causing it or how exactly to recreate the issue since it only happens with certain images. 

As far as I can tell it happens on Chrome, Firefox, and IE. Has anyone else experienced this? Any ideas?

## Max zoomed out (with distorted result)
![1](https://user-images.githubusercontent.com/17458641/39007506-f72be5be-43d3-11e8-8106-d4861d35f6ff.jpg)
![result1](https://user-images.githubusercontent.com/17458641/39007520-ff7cbe46-43d3-11e8-87fb-27967cb131f2.JPG)

## Zoomed in, working normally
![2](https://user-images.githubusercontent.com/17458641/39007538-04a6b084-43d4-11e8-8208-7f65cccf9ba6.JPG)
![result2](https://user-images.githubusercontent.com/17458641/39007547-0b2db614-43d4-11e8-9b47-e1d772cc85f5.JPG)

**Comment by thedustinsmith** [comment]
We need more information:

* How are you getting the result image ... base64? blob? html?
* How are you rendering the result image?  An `img` tag?  Does it have a width and height?

**Comment by key60529** [comment]
I have the same issue as you, I'm using croppie 2.6.2, so it happen when I zoomed all the way out and drag until viewport exist the bottom of the image, then it will happen.

And here are some of the code:
```
var resultWidth = 900, resultHeight = 1200;

uploadCrop.croppie('result', {
  type: 'base64',
  format: 'jpg',
  size: {
    width: resultWidth,
    height: resultHeight
  }
})
```

It seems like the result is not getting the correct width and height of the setting maybe? not so sure.

**Comment by trevorlangston** [comment]
I'm having a similar experience. @AlexanderLyon How exactly are you swapping these variables?

**Comment by AlexanderLyon** [comment]
@trevorlangston at the bottom of the `_rotate()` function, I created temp variables to store the old orientations, then just reassigned them to each other:
```javascript
function _rotate(deg) {
  if (!this.options.useCanvas || !this.options.enableOrientation) {
    throw 'Croppie: Cannot rotate without enableOrientation && EXIF.js included';
  }

  var self = this,
    canvas = self.elements.canvas,
    ornt;

  self.data.orientation = getExifOffset(self.data.orientation, deg);
  drawCanvas(canvas, self.elements.img, self.data.orientation);
  _updateZoomLimits.call(self);
  _onZoom.call(self);
  copy = null;

  // Reverses image dimensions:
  let oldHeight = self._originalImageHeight;
  let oldWidth = self._originalImageWidth;
  self._originalImageWidth = oldHeight;
  self._originalImageHeight = oldWidth;
}
```

**Comment by aamiguet** [comment]
After applying the fix, I had some issues dragging the picture after a rotation. Moving the following two lines :
```
_updateCenterPoint.call(self, true);  
_updateZoomLimits.call(self); 
```
After updating `self._originalImageWidth` & `self._originalImageHeight` seems to fix them.

**Comment by bwakabats** [comment]
Do you need an extra check that the "deg" is divisible by 90/270/-90 etc?
Something like

```
if ((Math.abs(deg) / 90) % 2 === 1) {
   ...
}
```
