### ISSUE TITLE
how to display a image aws s3 link into the plugin?

### ISSUE THREAD

**Issue by abhishek10281** [Foliotek/Croppie#526]
## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications

  - Browser:
  - Version:

**Comment by thedustinsmith** [comment]
https://github.com/Foliotek/Croppie/issues?utf8=%E2%9C%93&q=is%3Aissue+s3
