### ISSUE TITLE
Exif data not being read

### ISSUE THREAD

**Issue by matbeard** [Foliotek/Croppie#534]
## Expected Behavior
Uploaded image should have correct orientation based on Exif data.

## Actual Behavior
Uploaded image is not rotated correctly.

## Steps to Reproduce the Problem

  1. Duplicate upload demo code
  2. Upload rotated image with exif data

## Specifications
  - Browser: Chrome
  - Version: 66

I can't get the `enableExif: true,` option to work. I've essentially duplicated the upload demo code and I'm using the same versions of croppie.js and exif.js, but my uploaded images are not correctly oritented. However, the same image uploaded to the demo page is correctly oriented.

Any suggestions?

**Comment by matbeard** [comment]
Update: Interesting thing is, if I rotate the image using something like: `photo.croppie('rotate', 90);` it actually rotates through 180 degrees. It's like croppie has corrected the orientation 'internally' based on the Exif data, but the displayed image is not rotated.

**Comment by ollieBaker** [comment]
@matbeard In my project I found that exif.js was not on the window. 

I had to manually import and assign e.g. 
```import EXIF from 'exif-js';
window.EXIF = EXIF;```

Maybe double check exif.js is present on the window before you initialise croppie.

**Comment by matbeard** [comment]
@ollieBaker I'm using Webpack, so I've just changed from `require('exif-js')` to `window.EXIF = require('exif-js')`

Exif is definitely on the window, but still no luck.

It's not a big deal... just a minor annoyance.

**Comment by uwolfer** [comment]
You could try current master (probably my change fixed your issue as well: https://github.com/Foliotek/Croppie/commit/6a6bc79410214cd23d9b35d6d4a1d11891c45e06).

**Comment by matbeard** [comment]
Yup... current master has fixed it.

Thanks
