### ISSUE TITLE
Empty result returned when uploading portrait-oriented photo on iPad

### ISSUE THREAD

**Issue by dane-pi** [Foliotek/Croppie#54]
Hi Everyone,

Before getting into the question, I just wanted to say thanks for the great work on this project. It's a very useful library that seems to be gaining much traction, can't wait to see where it goes!

I'm using the latest version - 1.0.3 - and when uploading a photo from an iPad I'm noticing an empty base64 string returned when calling: 
croppie.result('canvas').then(function(result) { //code } );

After digging around, I'm seeing this effect only when (A) portrait-oriented photos have been uploaded by an iPad (B) the image has either been zoomed-out or panned so that its right and bottom borders are evenly-aligned (flush) with the right and bottom sides of the viewport. (test case images attached)

Has anyone else experienced this issue? I did see issue #31 , and have implemented the suggested solution without any luck. 

Any thoughts or direction would be awesome, thanks again

Zoomed out

![1-zoomedout](https://cloud.githubusercontent.com/assets/13358686/12485913/5f40547c-c02e-11e5-896b-f90b21d9e97d.png)

Panned, zoomed-in

![2-panned](https://cloud.githubusercontent.com/assets/13358686/12485914/5f443cc2-c02e-11e5-883a-da0ceacd018a.png)

Results

![2-result](https://cloud.githubusercontent.com/assets/13358686/12485916/5f5b1da2-c02e-11e5-9151-1a8121106978.png)

**Comment by thedustinsmith** [comment]
This kind of seems like it would be related to the exif orientation in #31.  Let me look into it a little bit more, I just wanted to assure that we're looking into it.

**Comment by dane-pi** [comment]
Okay, thanks for looking into this.

**Comment by dane-pi** [comment]
Has anyone been able to replicate the issue - on the demo site or within your own project? Unsure how to resolve this, I'm open to any direction or feedback.

**Comment by thedustinsmith** [comment]
I was able to replicate it given your steps.  I'm working on a solution in my spare time.  It seems we're going to have to offer an option to read the exif rotation.

**Comment by thedustinsmith** [comment]
@dane-pi See the note here: https://github.com/Foliotek/Croppie/issues/31#issuecomment-182112418

I tried on the iPad with those changes and the problem seems to be fixed there.  Does that fix it for you?

**Comment by thedustinsmith** [comment]
@dane-pi You can install the beta version of croppie and see if it fixes your issues: 

`npm install croppie@2.0.0-beta1`

**Comment by thedustinsmith** [comment]
i think this is fixed in https://github.com/Foliotek/Croppie/releases/tag/v2.0.0.

My test case was resolved.  Hopefully yours is too.

**Comment by dane-pi** [comment]
Hey - Sorry for the delay, yes it seems to be working. Thanks for your help!

**Comment by dws-arjun** [comment]
It says 'then', 'result' etc function not exist
