### ISSUE TITLE
Min zoom visual mismatch on boundary

### ISSUE THREAD

**Issue by Deams51** [Foliotek/Croppie#547]
## Actual Behavior
At min zoom with enforceBoundary set to true, it shouldn't be possible to zoom out further than the size of the image.

## Steps to Reproduce the Problem

  1. Create a modal dialog via angular material and angular 6.0
  2. Add croppie to the dialog
  
## Example 
![issue_croppie](https://user-images.githubusercontent.com/6062062/42102592-a50238ee-7bc6-11e8-8e6a-ef0e230e7281.gif)

## Specifications

  - Browser: Chrome 66.0.3359.181 (Official Build) (64-bit)
  - Version: Croppie 2.6.2
--

**Comment by thedustinsmith** [comment]
Can you share some code?  Usually issues like this occur if you `bind` croppie before the modal is completely shown.

**Comment by Deams51** [comment]
I was calling bind in ngOnInit.
Just tested with a 1s timeout and it does fix the issue. Now trying to figure out when in the angular component lifecycle it is safe to bind croppie.

**Comment by thedustinsmith** [comment]
I'm going to close the issue.  Feel free to comment with your solution to help other people in the future.

**Comment by Deams51** [comment]
Strangely, it seems to be after the 3rd view checked...
Thanks @thedustinsmith for the help.

 ```
 constructor() {
    this._cpt = 0;
  }

  ngAfterViewChecked(): void {
    if (!this._croppie && this._cpt > 2) {
      const cropElement = document.getElementById('image');
      this._croppie = new Croppie(cropElement, {
        viewport: { width: 350, height: 350 / this._ratio, type: this._data.type },
        boundary: { width: 550, height: 550 / this._ratio },
      });
      this._croppie.bind({
        url: this._data.image,
      });
    }

    this._cpt++;
  }
```
