### ISSUE TITLE
Error with b.js 

### ISSUE THREAD

**Issue by approce** [Foliotek/Croppie#55]
We are using requier.js in our application. On initing croppie.js we have an error 'b.js could not be found'.
For proper initialization we had to remove lines 9-11 and after that it started.

lines 9-11: 
'if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports', 'b'], factory);
    } else 
'

**Comment by thedustinsmith** [comment]
Thanks for the issue - I'm not sure why we chose the umd that we did, but I think we can simplify it.  Simplifying the umd should also fix your issue.  I'm thinking we should use this one: https://github.com/umdjs/umd/blob/master/templates/amdWeb.js

**Comment by vitalii-dmytruk** [comment]
Why do you need to load 'b'? As far as I understand 'b' is the name of the module croppie depends on. I don't see any dependencies. So it should be possible to entirely remove loading 'b'. So result may look like this

`(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports'], factory);
    } else if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {
        // CommonJS
        factory(exports);
    } else {
        // Browser globals
        factory((root.commonJsStrict = {}));
    }
}(this, function (exports) {`

**Comment by 1N50MN14** [comment]
+1

**Comment by thedustinsmith** [comment]
#67 Fixed this.  It'll be in the next release.
