### ISSUE TITLE
Next version (2.6.3) release?

### ISSUE THREAD

**Issue by whein** [Foliotek/Croppie#551]
When do you expect to publish version 2.6.3? If there isn't a definite date, a rough timeline would be helpful as well.

We are in need of the fixes from #532 , which has already been merged but has not yet been packaged to npm.

**Comment by thedustinsmith** [comment]
I can do it as soon as possible.  I'd like to have a second opinion on the code in `master` to make sure that it works.  Last time we merged in a PR to the `export` stuff it broke everything, so I'm a little hesitant to make another release just for that.  

This is where tests would come in handy, but I just don't have the time that I used to have.

**Comment by whein** [comment]
Makes sense. Thank you for the response!
