### ISSUE TITLE
Vanilla Example not working

### ISSUE THREAD

**Issue by fabio-C** [Foliotek/Croppie#553]
I am in Chrome (Ubuntu), and the Vanilla Example in the web page https://foliotek.github.io/Croppie/ doesn't work.

This is the result, after clicking on Resut button. The image is totally transparent.

![screenshot from 2018-07-29 18-50-21](https://user-images.githubusercontent.com/15702612/43368638-ba78216e-9360-11e8-8c9f-2d88289c99a8.png)

I had a similar problem working on my app, so I would understand why it happen.

I tried to clear site data, hard reloading and incognito page, but the problem persist.

Chrome version: Version 63.0.3239.108 (Official Build) (64-bit), Ubuntu
It works on Mozilla Firefox.

**Comment by fabio-C** [comment]
I solved this issue updating chrome version.

**Comment by zdennis** [comment]
@fabio-C , would you mind closing this issue if it's no longer relevant?
