### ISSUE TITLE
Errors with deleting and then reinstancing croppie

### ISSUE THREAD

**Issue by harmonherring** [Foliotek/Croppie#556]
## What I'm trying to do
I need the ability to change the size of the viewport with a couple of buttons.  The idea is that pressing a button will call .destroy() and then reinstance croppie with the new viewport values.

## Expected Behavior
It would be expected for croppie to be deleted, and then reappear with the new viewport.

## Actual Behavior
On the first button press, everything works fine.  If you try to click on another button to resize, the error "Uncaught TypeError: Cannot read property 'boundary' of undefined" is thrown.

## Steps to Reproduce the Problem

  1.  Resize using one button
  2.  Try to resize again
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

Yeah I'm completely unable to get Croppie to work in CodePen and I have no idea why.  Won't pull image from any URL that I pass it.  Here's the basics of my code here.  I've removed the part where the viewport dimensions change, because at this point it's not the problem.  It's having the viewport reinitialized two times.

##this function is called to create Croppie
function createCroppie() {
var el = document.getElementById('poster-crop');
        var poster = new Croppie(el, {
          viewport: { width:viewportWidth, height:viewportHeight},
          boundary: { width:500, height:500},
          showZoomer:false
        });
        poster.bind({
          url: 'uploads/' + filename
        });
}

function updateViewport() {
    poster.destroy();
    createCroppie();
}

Looks like this occurs across all browsers.  If anyone has any idea as to what's causing this (or if I can use a different route for resetting croppie, I'm eternally grateful to you.  Thanks!

**Comment by harmonherring** [comment]
Hey, I fixed this and I have no idea what the actual problem was, but it works now.  For anyone else who sees this, here's what I did.

To start with, I used the jQuery implementation instead of Javascript.  

## Initialization 
function createCroppie(viewportWidth, viewportHeight) {
    $posterCrop = $('#poster-crop').croppie({
        url:"MYURLHERE",
        viewport: {
            width: viewportWidth,
            height: viewportHeight
        },
        boundary: {
            width: 500,
            height:500
        }
    });
} 

I then called that function on the page load with my desired height and width.  

## Updating/Resizing Croppie

function resizeCroppie(width, height) {
    $('#poster-crop').croppie('destroy');
    createCroppie(width, height);
}

I then called the resizeCroppie() function with my new desired viewport width and height on button clicks.  

Hope this helps someone!

**Comment by thedustinsmith** [comment]
Glad you figured out your issue!

**Comment by erisvaldo777** [comment]
efefefef
