### ISSUE TITLE
setZoom not working.

### ISSUE THREAD

**Issue by sctaix** [Foliotek/Croppie#56]
Here is my code.

cropper = $('#cp').croppie({
			viewport: {
				width: marker.width,
				height: marker.height,
				type: 'square'
			},
			boundary: {
				width: window.innerWidth/2,
				height:window.innerHeight/2
			}
		});
		cropper.croppie('bind', {
			url: obj_src
		});
		cropper.croppie('setZoom', '0.1');

I changed different value for setZoom, but zoom slider didn't move also image zoom level too.

Where am I wrong?

**Comment by thedustinsmith** [comment]
Could you try this for me? 
```
cropper.croppie('bind', {
url: obj_src
}).then(function() {
cropper.croppie('setZoom', '0.1');
});
```

**Comment by sctaix** [comment]
I just tried but...

Uncaught TypeError: cropper.croppie(...).then is not a function on ".then(function() {"

**Comment by sctaix** [comment]
Well, I just got a news!

setTimeout(function(){
			cropper.croppie('setZoom', '1.5');
		},100);

this code works fine!

I think that the setZoom method had called before croppie bind to element.

Is there any way without using setTimeout function?

**Comment by thedustinsmith** [comment]
Looks like you're right - we're not returning the promise from `bind` if you're using jquery.  This a bug, we'll fix it soon.

https://github.com/Foliotek/Croppie/blob/master/croppie.js#L846

**Comment by sctaix** [comment]
For now, should use setTimeout function.

Thank you!

**Comment by kmservergarden** [comment]
If anyone still need this, the following would be a solution:
var counter = 0;
jQuery('#element').croppie({
 update: function() {
  if(counter==0)
   jQuery('#element').croppie('setZoom', '0');
  counter++;
 }
});

**Comment by brentonmaas** [comment]
I edited kmservergarden's solution slightly as it caused an infinite loop.
This will work for you:

var counter = 0;
cropper = $('#cp').croppie({
viewport: {
width: marker.width,
height: marker.height,
type: 'square'
},
boundary: {
width: window.innerWidth/2,
height:window.innerHeight/2
}
update: function() {
  if(counter==0) {
    counter++;
    jQuery('#element').croppie('setZoom', '0');
   }
 }
});
cropper.croppie('bind', {
url: obj_src
});

**Comment by rob-lindman** [comment]
thanks, brentonmaas!

**Comment by tnguyenxuan** [comment]
@brentonmaas thank you, it's worked!
