### ISSUE TITLE
cannot access croppie inside a modal

### ISSUE THREAD

**Issue by nicolasvahidzein** [Foliotek/Croppie#561]
hello,

i love this applet and i cannot get it to work inside a modal. It's a dom issue i know because when its in a regular vue template it works but i'm loading it inside a modal.

Any idea what i can do to fix this?

i'm using document.getElementById but it's returning null.

Thanks.

**Comment by marco-esposito** [comment]
Hi Nicola.
From the doc. page I read:

Visibility and Binding
Croppie is dependent on it's container being visible when the bind method is called. This can be an issue when your croppie component is inside a modal that isn't shown. Let's take the bootstrap modal for example..


var myCroppie = $('#my-croppie').croppie(opts);
$('#my-modal').on('shown.bs.modal', function(){ 
    myCroppie.croppie('bind', bindOpts);
});
                    
If you are having issues getting the correct crop result, and your croppie instance is shown inside of a modal, try taking your croppie out of the modal and see if your issues persist. If they don't, then make sure that your bind method is called after the modal is done animating.

**Comment by nicolasvahidzein** [comment]
Hello Marco,

Yes indeed you are absolutely right. It took me a lot of time to figure this out, i wasn't aware that this happened because of v-show in vue.js.

This is very helpful and thank you for your help on this matter. Once again thank you for this great module. I really love it!!

**Comment by cameliafakhar** [comment]
> Hi Nicola.
> From the doc. page I read:
> 
> Visibility and Binding
> Croppie is dependent on it's container being visible when the bind method is called. This can be an issue when your croppie component is inside a modal that isn't shown. Let's take the bootstrap modal for example..
> 
> var myCroppie = $('#my-croppie').croppie(opts);
> $('#my-modal').on('shown.bs.modal', function(){
> myCroppie.croppie('bind', bindOpts);
> });
> 
> If you are having issues getting the correct crop result, and your croppie instance is shown inside of a modal, try taking your croppie out of the modal and see if your issues persist. If they don't, then make sure that your bind method is called after the modal is done animating.

Hi would you please help me to understand how to use it into a jquery steps? when I use it in one of the section of jquery steps it dosn't work and I think it's because of the parent that have display none in first step
