### ISSUE TITLE
IE 11 gives 0 height and 0 width

### ISSUE THREAD

**Issue by dasatcher** [Foliotek/Croppie#562]
## Expected Behavior
Image is loaded with correct dimensions and is visible in the viewport.

## Actual Behavior
The height and width of the image (and cr-overlay) is set to 0 when loading an image. 

## Steps to Reproduce the Problem

  1. Open Internet Explorer 11
  2. Browse to https://foliotek.github.io/Croppie/
  3. Notice the first croppie demo is blank. (see screenshot)

![image](https://user-images.githubusercontent.com/2515963/44900226-53129000-ad04-11e8-9f31-47fbe77a4959.png)

  
## Specifications

  - Browser:  Internet Explorer 
  - Version: 11.0.9600.19100

**Comment by zdennis** [comment]
There's a good chance this is fixed with PR #592 .

**Comment by thedustinsmith** [comment]
The demo page works on IE11 after 2.6.3 so I'm closing this one.
