### ISSUE TITLE
warning: Croppie in WP

### ISSUE THREAD

**Issue by Lenndev** [Foliotek/Croppie#57]
Attention! When using croppie (pretty nice and light cropping tool) inside a Wordpress environment,
make sure you overrule de .entry-content img style rules. Cause the width and height properties of the default WP style screw up the positioning of your crop.

**Comment by thedustinsmith** [comment]
I don't have a wordpress blog that I can look at off hand.  Could you post the css that's causing problems?  Maybe we can overwrite those styles in croppie.css.

**Comment by Lenndev** [comment]
sure. i believe this is the stuff that is bugging
/*start wp styling
 * Responsive images
 *
 * Fluid images for posts, comments, and widgets
 */
.entry-content img,
.entry-summary img,
.comment-content img,
.widget img,
.wp-caption {
	max-width: 100%;
}

/* Make sure images with WordPress-added height and width attributes are scaled correctly. */
.entry-content img,
.entry-summary img,
.comment-content img[height],
img[class*="align"],
img[class*="wp-image-"],
img[class*="attachment-"] {
	height: auto;
}
/*end of wp styling*/
/*this is my fix*/
.entry-content img.cr-image {
	max-height: none !important;
	max-width: none !important;
	width: auto !important;
	height: auto !important;
}

**Comment by thedustinsmith** [comment]
We just made a change in master, yesterday, for the max-width issue: https://github.com/Foliotek/Croppie/issues/51.  I'm thinking that should fix this issue.

**Comment by Lenndev** [comment]
hmm okey... I actually installed the npm this morning 9.00h GMT+1

**Comment by thedustinsmith** [comment]
Yeah - it wouldn't have been in `1.0.5`, but it will be in `1.0.6`.  I'm going to go ahead and close this issue.  Thanks for the submission.
