### ISSUE TITLE
ReferenceError: copy is not defined at Croppie._rotate

### ISSUE THREAD

**Issue by WhitePolice** [Foliotek/Croppie#570]
Steps to Reproduce the Problem

  1. rm -rf node_modules package-lock.json
  2. npm install croppie
  3. import { Croppie } from 'croppie'
  4. instantiate and bind croppie
  5. use rotate function passing any valid values.

## Specifications

  - Browser: Chrome
  - Version: 69.0.3497.100

**Comment by WhitePolice** [comment]
Looks like, v2.6.2 on npm is just before this pull request #500

**Comment by olegshilov** [comment]
Same problem.
Can anyone publish newer version of package?

**Comment by thedustinsmith** [comment]
2.6.3 is released
