### ISSUE TITLE
Is it possible to use croppie to crop an image stored in canvas?

### ISSUE THREAD

**Issue by Swizzler121** [Foliotek/Croppie#574]
I'm Trying to write a tool for one of our departments to use that takes a photo, and crops it to a predetermined size (200x300). I have a working version that does this with the middle of the video frame, but it requires the user to wrangle the camera to fit the subject in the middle of the frame or have them move around until they're framed up right. I want to change this to allow the user to pan/zoom the finished image to fit the subject in with minimal posing/wrangling of the camera.

right now my code takes the photo and writes it to canvas, I want to then be able to crop it in canvas, but I can't find a dirt-simple tool that lets me do this. Croppie comes the closest, but I can't figure out how I can get it to work with canvas data as opposed to an imported image. Any help would be great.

  
## Example Link
* Link:[Codepen](https://codepen.io/anon/pen/yRyPYd)

## Specifications

  - Browser: Firefox
  - Version:62.0.2

**Comment by michelcve** [comment]
You could convert your image to base64, and set the base64 data as the 'imageUrl'.

**Comment by Swizzler121** [comment]
Gonna go ahead and close this, I ended up learning javascript and writing my own tool from scratch :) It should be on my github soon.
