### ISSUE TITLE
Question: Possible to create result img larger than croppie viewport/boundary

### ISSUE THREAD

**Issue by Lenndev** [Foliotek/Croppie#58]
Hi,
eg. i want to crop/size a 1920x1080px image to 500x300px img. is it possible to do that with a croppie box of 300x150px? or should the viewport always be as large as the desired result image?
thnx in advance

**Comment by Lenndev** [comment]
ah got it.. just take the canvas type with size: original... makes sense

**Comment by thedustinsmith** [comment]
Seems like this one is fixed - I'm going to close it.  If clarification is needed, feel free to reopen it.

**Comment by gianmariaraiteri** [comment]
i've the same problem, i want to crop images to 400x400 large using croppie on mobile, so not larger than 320px..is it possible?

**Comment by thedustinsmith** [comment]
It's not documented yet, but with the result method you can pass `{size: { width: 400, height: 400}}`
