### ISSUE TITLE
Cropped Result with enforceBoundary set to false

### ISSUE THREAD

**Issue by damienroche** [Foliotek/Croppie#580]
## Expected Behavior
Hi guys,
I'm using croppie with the vue wrapper (vue-croppie)
I would like to allow user to upload their logo in a defined-size container, in order to display them on different templates.
To do this, I have to set enforceBoundary to false for cases that image width is smaller than actual croppie viewport.
The result is ok when image width fit to container, however when I have to fit with the height, the output is not correct, as you can see on this video

https://v.usetapes.com/o7YHKK7HFd

My croppies options are 

```
croppieViewport = {
  width: 400,
  height: 175,
  type: 'square'
 }

croppieBoudary = {
  width: 400,
  height: 175
}

enableResize = false
enforceBoundary = false
```

```
this.$refs.croppie.result({
    size: {
      width: 800,
      height: 350
     },
   type: 'base64'
   }, (output) => {
    this.$emit('submit', output)
  })
```

## Specifications

  - Browser: Chrome
  - Version: 69

**Comment by thedustinsmith** [comment]
Closing this due to no response.  If 2.6.3 doesn't fix it, feel free to comment.
