### ISSUE TITLE
Not able to drag drop image

### ISSUE THREAD

**Issue by aloha222** [Foliotek/Croppie#581]
## Expected Behavior
When we darg drop image on the container it is should upload that image.

## Actual Behavior
When we darg drop the image on the container it is not working

## Steps to Reproduce the Problem

  1. Drag drop image on container.
  1.
  1.
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications
I have bind croppie using jquery
  - Browser:
  - Version:

**Comment by thedustinsmith** [comment]
Croppie's not responsible for uploading images.  Only cropping it.  We provide upload examples on our demo just for ease of demo.
