### ISSUE TITLE
Warning! Do not use this plugin

### ISSUE THREAD

**Issue by naXa777** [Foliotek/Croppie#587]
I've spent 3 DAYS configuring this plugin to work nicely in a Bootstrap modal and the final result looks UGLY. It turned out that the plugin has numerous issues. In other cases, I'd fill detailed bug reports, but now I feel so desperate... I don't see any sense in posting issues that will duplicate existing ones.

If you're reading this while choosing a JS plugin for image cropping, DO NOT USE CROPPIE!!! Go look for any better alternatives. Don't waste your time.

The most important issues that I encountered:
* when input image is of type JPG and I try to get result (of type PNG or JPEG), it produces a blank image.
* when `enableResize: true` and `enableZoom: true` and image is zoomed in, it's possible to drag viewport bounds outside of the container bounds. it results in hidden viewport bounds and an overzoomed image; it's impossible for user to fix this, user is forced to refresh the whole page.
* when `enableResize: true` it's impossible to make aspect ratio fixed.
* it's not responsive. image container can overflow modal window (popup) bounds.

## Expected Behavior
it works.

## Actual Behavior
it doesn't.

  - Browser: Chrome 71
  - Plugin version: 2.6.2

**Comment by thedustinsmith** [comment]
Sorry you experienced issues with croppie.  I'll be the first to admit that I don't have as much time as I'd like to support this anymore. 

That being said, plenty of people use croppie with the bootstrap modals:
https://github.com/Foliotek/Croppie/issues/61
https://github.com/Foliotek/Croppie/issues/195
https://github.com/Foliotek/Croppie/issues/389

If you don't want to use Croppie, that's fine.  I honestly don't care.  But to post an insulting issue in an open source project that I (and several other people) have spent a lot of time building, and have been gracious enough to share with the community  .... is rude. 

Next time try just asking for help before you lose your temper.
