### ISSUE TITLE
enforceBoundary

### ISSUE THREAD

**Issue by oscarhandsome** [Foliotek/Croppie#588]
Hello all.
On iOS, if we put false doesn't work correctly. Somebody know why?

**Comment by thedustinsmith** [comment]
I don't have iOS to test with, but the more information you can provide, the more likely you'll get recommended solutions.  What problems are you encountering?

**Comment by oscarhandsome** [comment]
Hello @thedustinsmith  at first thank you for your best work!
Second? about my issue. Will try to explain.
I created small application [link](https://www.almall.com/friday/) testing [here](http://almall-friday.elbargo.ru/)
i used code from another application from another developer from [this site](https://subinsb.com/create-profile-picture-framer-web-app/)

all code js [here ](https://runkit.com/oscarhandsome/enforceboundary)
All code is written not by me. but i'm trying to fix everywhere what we need.

Every time when an image is uploaded works function with croppie and this part
when have this setting 
`enforceBoundary: false`
and save the image in the PHP by ajax we get on iOS[ this image ](http://almall-friday.elbargo.ru/B28DE4E0-1CD1-4B30-8248-5A25CFE63AED.jpg)
with a black color on the background.
But when enforceBoundary is true, the image is saving, but we can't fix size...

Third: I wanted to use script **domtoimage** (snapshot button) but can't correctly convert to base64 with blob to save on the php side. But this is not for this chat

**Comment by zdennis** [comment]
@oscarhandsome, there's a good chance that the fix for #591 will resolve this issue for you. Can you try this version of Croppie (from PR #592)?

https://raw.githack.com/zdennis/Croppie/63c34e165c53da1624784b611680eafdeec57c60/croppie.js

**Comment by oscarhandsome** [comment]
@zdennis Hello thank you! 
That works for me!
Do you know what exactly was an issue? interesting for me.

**Comment by thedustinsmith** [comment]
2.6.3 is released and contains #592
