### ISSUE TITLE
lagged on Android

### ISSUE THREAD

**Issue by silenceM** [Foliotek/Croppie#59]
hi,
  when i use on android i select a picture then move picture.picture moved solw.

**Comment by thedustinsmith** [comment]
Sorry for the delayed response - if you can provide more information, we can possibly help.  What browser are you using on android?  Are you using croppie on a custom site, or is the demo site slow?  What version of android?  At what point during the process do you experience the lag?

**Comment by metalminded99** [comment]
@thedustinsmith I also experiencing this right now, I am using Chrome on android mobile, I also tried it on the demo site but still laggy, specially when scrolling through the page. Do you have any updates about this? thanks!

**Comment by geraldarcega** [comment]
@thedustinsmith I also experiencing this right now, I am using Chrome on 4.4.2 android mobile, I also tried it on the demo site but still laggy, it occurs when scrolling through the page even the page just got loaded. Do you have any updates about this? thanks!
