### ISSUE TITLE
2.6.2 npm package works, but 2.6.2 tag doesn't

### ISSUE THREAD

**Issue by zdennis** [Foliotek/Croppie#593]
I found issues when trying to test out the fix to #591 on an Angular 6 project. I tracked down an issue that demonstrates that the 2.6.2 npm package works fine, but the 2.6.2 tag does not.

The issue present in the `2.6.2` tag seem to be present in the latest `master`. 

## Expected Behavior

I would have expected both the 2.6.2 tag and npm package to work the same. 

## Actual Behavior

There appears to be difference between the 2.6.2 npm package and the 2.6.2 tag. Here's a screenshot to demonstrate:

![croppie-2 6 2-build-issue](https://user-images.githubusercontent.com/967/48854198-4c356f80-ed7f-11e8-95d9-4dffd77b57a5.png)

The code that produces this is:

```typescript
const croppieOptions: CroppieOptions = {
  viewport: { width: 250, height: 250, type: this.shape },
  boundary: { width: 310, height: 310 },
};

this._croppie = new Croppie(this._croppiePortal.nativeElement, croppieOptions);
this._croppie.bind({
  url: this.srcUrl
});
```

Where `srcUrl` is the data url for a user-selected image. There are no errors logged.

## Steps to Reproduce the Problem

Right now, I've dropped this into our Angular project.

  1. If you install croppie@2.6.2 into a project that uses npm  and bind an image it will work. 
  1. Next, install croppie from the 2.6.2 tag on the same project and watch it no longer work.
  
## Example Link

TBD

## Specifications

  - Browser:
  - Version:

**Comment by zdennis** [comment]
_ may be doing something naive and terribly wrong. There appear to be no changes to `croppie.js` or `croppie.min.js` between the tag and the tarball up on npm. _Sigh_.

**Comment by zdennis** [comment]
Okay, so this is not a _real_ issue. It appears that installing from Git or filesystem directly will cause the issue. But if you run `npm pack` on the checkout and then install the tarball directly then everything is okie dokie. 

@thedustinsmith, out of curiosity, do you know enough about npm to know why this might be? 

I'm going to go ahead and close this as it's appears to be a non-issue on Croppie's part and a misunderstanding on my part.

**Comment by thedustinsmith** [comment]
Off the top of my head, I have no idea.  How exactly are you installing the 2.6.2 tag?

**Comment by zdennis** [comment]
I had cloned the project locally and then tried to install from the file-system:

```
npm install --save /path/to/local/checkout/of/Croppie
```

I noticed this created a symlink of `node_modules/croppie -> /path/to/local/checkout/of/Croppie`. I then checked out the tag and restarted my application.

it looks like installing from file-path is a bad idea. I installed a tarball from Github just now as a test and that works fine:

```
# works fine
npm install --save https://github.com/zdennis/Croppie/tarball/v2.6.2

# works fine
npm install --save https://github.com/zdennis/Croppie/tarball/master
```

**Comment by dobromir-hristov** [comment]
You need to re-link the file after checking it out locally :) You probably had the old file linked.
