### ISSUE TITLE
Choose the quality ?

### ISSUE THREAD

**Issue by ncou** [Foliotek/Croppie#60]
Hi,

Very nice script.
Do you think it's possible to add parameter to choose the quality ?

Actualy the "toDataURL()" don't take parameter so the output is saved as .png file. And the uploaded file is bigger than the input file.

Do you think it's possible to add parameter to select the mime type and quality ? like :
 
toDataURL("image:jpeg", "0.7")

Thank you.

**Comment by thedustinsmith** [comment]
I'm unclear on what you're wanting to happen with the quality.  Croppie isn't changing the image's resolution.

Maybe you're referring to the `result` method's `size` argument.  You can pass in `size: 'original'` and it returns the image at it's native size, but cropped.

**Comment by ncou** [comment]
I use the script with the "canvas" option.
When I choose to upload an .jpg filen the saved cropped picture, got the right size, but it's no more an jpeg file but a png file.

In your script the function "toDataURL" (line 173 in your .js file) is used to return the content of the canvas area.
But if there is no parameter for this function, the data return is automaticly converted to "png" at 96dpi.
=> https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

In my case i choose an input file .jpg at 160kb, but the output file is cropped but with the conversion to .png I got a size of 833 kb :(

**Comment by thedustinsmith** [comment]
I see what you're saying now - that seems like a useful feature.  We'll see if we can get to it soon.

**Comment by ncou** [comment]
nice. thank you :) keep up the good work.

**Comment by thedustinsmith** [comment]
#75

**Comment by thedustinsmith** [comment]
This is in https://github.com/Foliotek/Croppie/releases/tag/v2.0.0

**Comment by 3Dpassion** [comment]
> 
> 
> I'm unclear on what you're wanting to happen with the quality. Croppie isn't changing the image's resolution.
> 
> Maybe you're referring to the `result` method's `size` argument. You can pass in `size: 'original'` and it returns the image at it's native size, but cropped.

It is not taking this value :( I am trying to not resize image at all, but only to crop. Am I missing anything?
