### ISSUE TITLE
Trying to set viewport not in center - problem with zooming

### ISSUE THREAD

**Issue by dszwed** [Foliotek/Croppie#604]
## Expected Behavior
I want to move viewport position from center with top/left properties.

## Actual Behavior
When I moved viewport it's fine when I drag&drop image, but when it sticks to bounds and I'm zooming it to the smallest, image is unzoomed improperly.

## Steps to Reproduce the Problem
  1. [Codepen](https://codepen.io/dszwed/pen/wRaoOz)
  2. Move image its bottom left corner is aligned with bottom left corner of viewport
  3. Unzoom to the smallest size
  4. ![croppie-viewport](https://user-images.githubusercontent.com/1706430/49819210-1f201f80-fd75-11e8-9e43-2835f95a9ff3.png)
  
## Specifications
  - Browser: Any
  - Version: 2.6.2

**Comment by thedustinsmith** [comment]
The viewport has to be in the center of the boundary, any custom positioning isn't supported by the library.  Sorry about that.

**Comment by dszwed** [comment]
Thanks for a quick response. So I have to customize this method right?
https://github.com/Foliotek/Croppie/blob/master/croppie.js#L756
