### ISSUE TITLE
Initializing Croppie inside a Bootstrap3 Modal messes up the zoom functionality

### ISSUE THREAD

**Issue by Xgatt** [Foliotek/Croppie#61]
I'm uploading an image using the FileReader api and binding it to a croppie instance inside a Bootstrap 3 modal. When the binding completes, the following issues seem to happen:

1. Image starts out zoomed in to extreme levels, but the slider is near the beginning. Pulling it all the way to the left only marginally zooms out.
2. Zooming ranges seem inconsistent. First time zooming, the range is between 1.5x (approximately) minimum and some enormous number for maximum. After letting the handle go and starting again, I can now zoom all the way out to 0. But after hitting 0, the slider does nothing until I mouse up and mouse down again. The third time, the range is again different. 

If I get rid of the modal and just load croppie inside another regular div, the zoom behavior and levels are perfect.

**Comment by neverthemachineforever** [comment]
@Xgatt 

I'm also using Bootstrap 3, so threw my view into a Modal to see if I could reproduce this, but could not (Chrome on OS X).

Any chance you've got some styles which may be interfering here? I could imagine if you had modal specific styles (specifically CSS transforms) in place, they may cause something like this..

**Comment by thedustinsmith** [comment]
Agreed - if you can throw together a jsfiddle or jsbin demonstrating the issue, tracking it down would probably be easier.

**Comment by murilonkz** [comment]
Remove the class "fade" in modal and it will be ok. Same problem here.

**Comment by Xgatt** [comment]
@murilonkz Hah! I was just setting up the JSFiddle that @neverthemachineforever and @thedustinsmith requested when I saw your comment. That did indeed fix the issue, thanks!

**Comment by WimWidgets** [comment]
@murilonkz You can still use the 'fade' effect. The problem is that the fade effect takes time to complete and meanwhile Croppie detects the image as invisible. Just open the modal first and bind your image to Croppie when the `shown.bs.modal` event fires.

**Comment by ibnuh** [comment]
Thanks @murilonkz and @WimWidgets !

**Comment by xmaestro** [comment]
@murilonkz Thanks for saving my ass buddy!

**Comment by aliassad** [comment]
Thanks @murilonkz  🥇
