### ISSUE TITLE
How to init Croppie ?

### ISSUE THREAD

**Issue by lorraineS** [Foliotek/Croppie#610]
Hello!
## Actual Behavior
I need to init your plugin but... i've always error : `Uncaught Error: Croppie: Can't initialize croppie more than once`
Croppie is initialized once. I don't understand this error...

## Steps to Reproduce the Problem

Link: [Codepen](https://codepen.io/lorraineS/pen/WLdOGq?editors=1010)

1.  Load a random image and open your console.
2. Error : `Uncaught Error: Croppie: Can't initialize croppie more than once`

## Specifications

  - Browser: Chrome
  - Version: Version 71.0.3578.98 (Build officiel) (64 bits)

**Comment by thedustinsmith** [comment]
Your upload demo element should look like this: 
```
<div id="upload-demo"></div>
```

**Comment by lorraineS** [comment]
> Your upload demo element should look like this:
> 
> ```
> <div id="upload-demo"></div>
> ```

The `#upload-demo` ID is already used for the parent block (it's a copy / paste of your demo).

If I change the id of the input file by `#upload-demo`, the error is the same.

**Comment by lorraineS** [comment]
Thanks!

**Comment by DjSeNaSs** [comment]
> Let me be more specific. Change this:
> 
> ```
>         <div class="upload-demo-wrap">
>           <div id="upload-demo" class="croppie-container"><div class="cr-boundary" aria-dropeffect="none"><canvas class="cr-image" alt="preview" aria-grabbed="false"></canvas><div class="cr-viewport cr-vp-circle" tabindex="0" style="width: 100px; height: 100px;"></div><div class="cr-overlay"></div></div><div class="cr-slider-wrap"><input class="cr-slider" type="range" step="0.0001" aria-label="zoom"></div></div>
>         </div>
> ```
> 
> to this
> 
> ```
> <div id="upload-demo"></div>
> ```

Omg thx you so much! I took the code in a old project and I searched for hours to make it work. It wans't obvious that it was already "instanced" because there was html in the wrapper. It's not the usual way to verify. Bless you!
