### ISSUE TITLE
Iphone photos flipped when uploaded through macbook 'photos' software.

### ISSUE THREAD

**Issue by teamandrei** [Foliotek/Croppie#63]
Hello Everyone, thanks for looking into this.

Photos taken with the iphone camera which are uploaded to Croppie through the default software 'photos' on the mac book are flipped to either side. If the same picture is not uploaded from the 'photos' software but copied onto the desktop first and uploaded from there this does not happen. It  does not happen with other pictures, even if uploading through the 'photos' software.. only with camera photos. 

This happens on all browsers and even on the Croppie demopage. 

![croppie firefox](https://cloud.githubusercontent.com/assets/16683007/12702126/d3f38d8c-c81e-11e5-8bee-a4e63bbdd79e.png)

Iphone: 6
Mac book pro
latest browser builds

**Comment by thedustinsmith** [comment]
This is directly related to #31.  We're working on solutions for it, but in the meantime, you should be able to use the code in that case.

**Comment by teamandrei** [comment]
@thedustinsmith thank you for directing me in the right direction. I really hope this gets addressed in a official new build, seems to be something that could potentially affect a lot of users with everyone using iphones these days. cheers :)
