### ISSUE TITLE
Vertical panning in Chrome mobile scrolls the page

### ISSUE THREAD

**Issue by diegoaa** [Foliotek/Croppie#632]
## Expected Behavior
Touching the image and dragging it will only reposition the image

## Actual Behavior
The image gets slightly repositioned but the browser page scrolls as well, making accurate positioning very tough and frustrating.

## Steps to Reproduce the Problem

  1. Open a page with a croppie on Chrome mobile browser (tried on Android) 
  2. Zoom in a little, then try to reposition the image vertically. 

  
## Example Link
* Link: https://foliotek.github.io/Croppie/

## Specifications

  - Browser: Chrome mobile browser
  - Version: 72

This behaviour is also seen on DuckDuckGo browser but not on Firefox mobile. It works like a charm on Firefox, unfortunately more people use Chrome mobile.

**Comment by agusterodin** [comment]
I think Google just fixed this

**Comment by agusterodin** [comment]
Try updating Chrome

**Comment by diegoaa** [comment]
Thanks for the update! Yes, it seems to be fixed in Chrome 73. Updating WebView also improved the behaviour in DuckDuckGo - the address bar still moves but I guess that is up to DDG to fix.
