### ISSUE TITLE
Spent half of a day, no result

### ISSUE THREAD

**Issue by Buraky89** [Foliotek/Croppie#636]
Hello, 

First of all I want to say that the examples on the main page (https://foliotek.github.io/Croppie/) are working properly. However, I need to say that, it does not seem to be developer-friendly. 

I followed the installation steps and included all the script and css. And then firstly i followed "the basics" section of the site. I copy-pasted that part and now I can zoom in and out on the image. 

Then, the usage part. OK, I understand that there are 2 options which I can choose to use jQuery or not. Then a "documentation" part appears. I skip that part since I don't know how it works yet. Let me see some examples. 

"Demos" part. There is a "basic example". I want to try that part on my local. However, there is only the "script" part. Where is HTML? Where is the HTML of the result button? Where are the HTML codes of that textboxes? 

I appreciate your efforts but when I am trying a new plugin, I expect a few lines of JS + html codes that actually work. 

However, I have finally managed to use the "result" function, then I assigned the base64 result into the src of an img element. Then, a black image has come up. 

## Expected Behavior

A cropped image in the img tag.

## Actual Behavior

A black image in the img tag.

## Steps to Reproduce the Problem

  1. Paste that HTML into a page
```
        <div id="demo-basic">

        </div>

        <img id="imgbase64" />
```
  2. Paste those scripts
```
            var el = document.getElementById('demo-basic');
            var vanilla = new Croppie(el, {
                viewport: { width: 100, height: 100 },
                boundary: { width: 300, height: 300 },
                showZoomer: false,
                enableOrientation: true,
                enableResize: true,
                mouseWheelZoom: 'ctrl'
            });
            vanilla.bind({
                url: 'test.jpg',
                orientation: 4
            });

            vanilla.result({ type: "base64", format: "jpeg", size: 'original' } ).then(function(base64) {
                document.getElementById("imgbase64").setAttribute("src", base64);
            });    
```
  3. Save a random image as test.jpg, in the main folder. 
  4. Run the page, and see the black image on the image tag's src.
  

## Specifications

  - Browser: Chrome
  - Version: 72.0.3626.121

**Comment by thedustinsmith** [comment]
Doesn't really seem like you appreciate it, but I'll try not to be insulted.  

Every single example says "on button click" before calling the result method, but I understand if you just skip over comments, that's an easy mistake.

https://codepen.io/thedustinsmith/pen/KEEBKX

Next time, instead of criticizing, try being helpful.  If you think the documentation could use some updating, it's an open source repository to which you can contribute changes.  I can't promise they'll make it in, but it's a way better approach than your current one.

**Comment by gabrielscr** [comment]
Fucked up documentation, Jesus Christ
