### ISSUE TITLE
Materialize JS modal also brakes zoom functionality

### ISSUE THREAD

**Issue by volshebnick** [Foliotek/Croppie#64]
In #61 you found a solution with removing the .fade class from modal. I was trying to find the reason of why it's not working on Materialize JS modal, but no luck. If it's possible, please help with this issue.
When zooming out, image is not being centered and you can't drag it...

**Comment by thedustinsmith** [comment]
Can you throw together a http://jsfiddle.net or a http://jsbin.com to demonstrate the issue?

**Comment by volshebnick** [comment]
Here it is: http://jsbin.com/cirulonimi/edit?html,js,output

**Comment by thedustinsmith** [comment]
I'd say most of your problems stem from the croppie initializing as the modal is opening.  If you add the `ready` method to your `openModal()` function and bind the croppie in there, the zooming works correctly.

Check out this modified bin: http://jsbin.com/xepoxenobu/edit?html,js,output

Croppie's very dependent on the element being visible and positioned when it's bound.  So waiting until that modal's open has completed is important.

**Comment by thedustinsmith** [comment]
I will say - that there is some odd behavior right at the beginning of zooming in the bin referenced.

**Comment by volshebnick** [comment]
Got it, thanks a lot for suggestion. Can you please also comment #65 ?
