### ISSUE TITLE
Can't hide cr-original-image nor modify it, else croppie stop working

### ISSUE THREAD

**Issue by Nialcen** [Foliotek/Croppie#640]
## Expected Behavior
I have a picture and a button.
On button click, I trigger the croppie.
Croppie shows up, working fine
**Original picture goes hidden.**

## Actual Behavior
I have a picture and a button.
On button click, I trigger the croppie.
Croppie shows up, working fine
Original picture get "cr-original-image" class, that have a display:none; css rule
However, the picture stay displayed.

I tried to add after croppie call : 
.hide();
.css('display','none');
.css('width', halfCurrentWidth); // trying to make it smaller if can't hide it.
dev console modifications

At any tries, when original img.cr-original-image is hidden or modified, croppie system refuse to do the trick. Asa i put the original information, it works again.

## Steps to Reproduce the Problem

The easiest way : 

1. Go to [http://fr.militaria-and-co.com/submit-listing/](http://fr.militaria-and-co.com/submit-listing/)
2. Go down the page to the "Images" section.
3. Select an image : it will load and display as a thumbnail.
4. Click on the thumbnail, the image will open in a lightbox, with a "Recadrer" button.
5. Click the button, you will see crop section showing and working.
6. In console, modify css rule : 

`.croppie-container .cr-original-image { display: none; }`
to 
`.croppie-container .cr-original-image { display: none !important; }`

forcing it to hide.
-> Crop does not work anymore.

Undo it, it works again.
 
## Specifications

  - Browser : Both chrome and firefox up to date.

**Comment by alsmpd** [comment]
@Nialcen were you able to resolve this issue?

**Comment by Nialcen** [comment]
Yup solved.

**Comment by alsmpd** [comment]
Good job. I'm going to close but feel free to post any tips you think other users might find useful.

**Comment by Nialcen** [comment]
Roger that. I'll explain how then.
