### ISSUE TITLE
Destroy function throwing an error

### ISSUE THREAD

**Issue by shubhajagtap88** [Foliotek/Croppie#641]
## Expected Behavior
Destroy function should delete the croppie instance

## Actual Behavior
Getting Error:
croppie.js:1477 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
![image](https://user-images.githubusercontent.com/43500005/55416829-7423b380-5567-11e9-9170-896cfc65830c.png)

## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications
![Croppie Destroy](https://user-images.githubusercontent.com/43500005/55416963-aaf9c980-5567-11e9-82f4-1b06a275b89c.PNG)

  - Browser:Chrome
  - Version:

**Comment by Nialcen** [comment]
Give us the code where you call destroy()

**Comment by shubhajagtap88** [comment]
$(".reset").click(function () {

            $('.upload-demo').removeClass('ready');
            $("#upload-demo").html("");
            $('#upload-demo').croppie('destroy');
                        
            $uploadCrop = $('#upload-demo').croppie({
                viewport: {
                    width: 1000,
                    height: 562,
                    type: 'square'
                },
                enforceBoundary: false,
                boundary: {
                    width: 1100,
                    height: 650
                },
            });
        })

**Comment by Nialcen** [comment]
Can you show me html structure goin' with it ?

**Comment by shubhajagtap88** [comment]
Hi Niaclen, 
Thanks for looking in it.
I was setting  $("#upload-demo").html(""); , removed this line and it started working as expected.

Thanks,
Shubhangi
