### ISSUE TITLE
Can't drag the image if it's smaller than viewport.

### ISSUE THREAD

**Issue by volshebnick** [Foliotek/Croppie#65]
![screenshot 2016-02-01 04 05 10](https://cloud.githubusercontent.com/assets/1108401/12706209/3035ac36-c899-11e5-83be-b3f313782d3c.png)

As mentioned in #64 image is not centered when using in Materialize JS and it can't be dragged if smaller then viewport. I've changed minZoom = Math.max(minW, minH) line to minZoom = 0.1 in croppie.js to make the problem more visible.

**Comment by thedustinsmith** [comment]
This one would be easier to diagnose if we had that fiddle or bin from #64.  What's the ratio of the size of your image to your viewport?

**Comment by volshebnick** [comment]
Check this please http://jsbin.com/cirulonimi/edit?html,js,output

**Comment by thedustinsmith** [comment]
If you check out this modified bin - where the zoom out correctly centers on the image: http://jsbin.com/xepoxenobu/edit?html,js,output

When you're zoomed all the way out, I wouldn't expect to be able to drag it.  The image has to fill up the viewport, that's one of the limitations of croppie.  What behavior are you expecting?

**Comment by volshebnick** [comment]
For example lets say we have a viewport size 100x100 and image is 100x80
I think it would be better if croppie can fill the blank 20pixels with white bg or transparent bg so the image fits the viewport.

**Comment by thedustinsmith** [comment]
In the scenario you described, croppie sees that your image isn't as tall as your viewport so it sets the minZoom to `100/80=1.25`.  Then the max zoom is arbitrarily set to `150%` (or something like that) of the min value, so there isn't any blank space.

If you change the `viewport.height` in the latest bin to 120, you can see what I'm talking about.

**Comment by volshebnick** [comment]
I'm trying to achieve an option where minZoom is not 100/80=1.25 but 80/100=0.8 and after this we still can drag the image in viewport.

**Comment by thedustinsmith** [comment]
I understand, but I will say the chances of this being done are slim.  There's a ton of logic in croppie.js that is restricting you from dragging the image outside of the viewport, so that minzoom becomes pretty important.  

Also, currently the image that you're dragging around is an actual <img /> tag.  I could see this being a possibility if we drew the image to a canvas (like we're experimenting around with in a different branch), and you drag the canvas around.  Even then, I'm having a hard time understanding why you wouldn't want the image to span the entire viewport.  

What if you had the ability to resize the viewport after knowing the dimensions of the image?

**Comment by volshebnick** [comment]
Let's say we need to get 100x100 image on the out. But user is uploading a rectangle image and he wants it to fit the 100x100 viewport. Is there any way I can resolve this?

**Comment by thedustinsmith** [comment]
Not with the stock croppie code, you might be able to change [line 652](https://github.com/Foliotek/Croppie/blob/master/croppie.js#L652) to Math.min(minW, minH).

But I'm not sure retrieving the result canvas type will work.  You can sure give it a try.

**Comment by volshebnick** [comment]
I guess this could be a great option if you can implement it later. Fitting an image into viewport is a common task. Anyway, thanks a lot for response and support, you are the best!!! )))
