### ISSUE TITLE
Rectangle shape required

### ISSUE THREAD

**Issue by abelardolg** [Foliotek/Croppie#650]
## Expected Behavior
Require rectangle shape

## Actual Behavior
Don't support.

## Steps to Reproduce the Problem

  1. Set shape property to 'rectangle'
  1.
  1.
  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link:

## Specifications

  - Browser: any
  - Version: any

**Comment by thedustinsmith** [comment]
You can set the width and height of your viewport and/or boundary to rectangular dimensions.  The shape property is mostly for "circles".

**Comment by junaidahmad112** [comment]
> You can set the width and height of your viewport and/or boundary to rectangular dimensions. The shape property is mostly for "circles".

still not working,
is there any other way to get a rectangle shape?
