### ISSUE TITLE
Question : what actually returned in croppie.get()

### ISSUE THREAD

**Issue by mandaputtra** [Foliotek/Croppie#652]
I need some image points to edit a video on the server, when I use `get()` it shows this :
```js
orientation: 1
points:  [ 0, 182, 480, 662]
zoom: 1.2083
```
what actually points mean? where is the offset?

**Comment by webmasterMeyers** [comment]
RTD, points Array of points that translate into [topLeftX, topLeftY, bottomRightX, bottomRightY]

**Comment by mandaputtra** [comment]
@webmasterMeyers  Hmm, that may be is. But if you test with 3000 x 4500 image it will returning like this (centre of the image)

```
["0", "649", "3694", "4343"]
``` 

So top left is always 0, it is where its start. X-axis and 3694 are the end of X-axis? Hmm, I Should test this with sharp.js

**Comment by mandaputtra** [comment]
Yeah, you right. 

```js
// I crop with sharpjs its same as ffmpeg
const sharp = require('sharp')
const path = require('path')
const imgPath = path.join(__dirname, 'img')

sharp(`${imgPath}/curology-1540895-unsplash.jpg`)
  .extract({ left: 0, top: 649, width: 3649, height: 4343 })
  .toFile('output.jpeg', function(err) {
    if(err) throw Error(err)
    console.log('success')
  })

// metadata of image
sharp(`${imgPath}/curology-1540895-unsplash.jpg`)
  .metadata()
  .then(metadata => console.log(metadata))

// format: 'jpeg' 
// width: 3694
// height: 4992
```

The crop is the same as the Croppie Image result thanks.

**Comment by mandaputtra** [comment]
I look at the source code, it doesn't work that way I think.

It's said [ x1, y1, x2, y2], but when I do `(x2 - x1) (y2 - y1)` its doestn return right `X Y` on images againts croppie
