### ISSUE TITLE
On demo page, clicking Result button says swal is not defined

### ISSUE THREAD

**Issue by swergas** [Foliotek/Croppie#655]
## Expected Behavior

I see the cropped image

## Actual Behavior

Nothing happens in the window, and the console says "ReferenceError: swal is not defined"

## Steps to Reproduce the Problem

  1. Click on a "Result" button on https://foliotek.github.io/Croppie/

  
## Example Link
Please recreate your issue using [JSbin](https://www.jsbin.com), [JSFiddle](https://jsfiddle.net), or [Codepen](https://codepen.io).
* Link: https://foliotek.github.io/Croppie/

## Specifications

  - Browser: Firefox (on Ubuntu 16.04)
  - Version: 67.0

**Comment by dmakhno** [comment]
seems bower_components were deleted from gh-pages in ab4c4361194c77d4b515efff9df96a94268b6d00

**Comment by Jdeboysere** [comment]
Same problem on August 2019.
This is not serious, it still not fixed.

**Comment by roenfeldt** [comment]
Almost a year later, issue still not fixed.

**Comment by thedustinsmith** [comment]
Sorry - there was an issue deploying the last release to github pages. Fixed now.
