### ISSUE TITLE
croppie is slow with android

### ISSUE THREAD

**Issue by sctaix** [Foliotek/Croppie#66]
Croppie had initialized right after an image(2016 × 1512, 599kb) with android browser(chrome mobile), every dragging image action was so slow.

see performance test video at https://drive.google.com/file/d/0B4Dd52uYX9-1LVFHalVVTWZybzg/view?usp=sharing

[General native Browser info.]
chromium
Javascript: V8 webtech-jsengine: 3.19.18.24-F.2.40a-ss-m2

[Browser gpu support info.] -- Not really helpful for this issue I think
Graphics Feature StatusCanvas: Hardware accelerated
Compositing: Hardware accelerated on all pages and threaded
3D CSS: Hardware accelerated
CSS Animation: Accelerated and threaded
WebGL: Hardware accelerated
WebGL multisampling: Hardware accelerated
Flash 3D: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Texture Sharing: Hardware accelerated
Video Decode: Software only, hardware acceleration unavailable
Video: Hardware accelerated
Panel Fitting: Unavailable. Hardware acceleration disabled.
Rasterization: Software only, multi-threaded

[Device info.]
Model: Galaxy Grand2
Kernel: 3.4.0-3440063
Android Kitkat 4.4.4

[Hardware info.]
Embedded Operating System: Google Android 4.3 (Just upgraded to 4.4.4)
CPU Clock: 1200 MHz
CPU: Qualcomm Snapdragon 400 MSM8926 (Browse devices based on this microprocessor)
RAM capacity: 1.5 GiB (accessible: 1.4 GiB)

Is that normal?

**Comment by thedustinsmith** [comment]
Thanks for the details, and the video!  I definitely wouldn't consider that normal or expected.  Out of curiosity, do you experience the same lag when you use that device on http://foliotek.github.io/Croppie ?

**Comment by sctaix** [comment]
Thank you for reply :)
I just tested http://foliotek.github.io/Croppie with the device. Please see video at https://drive.google.com/file/d/0B4Dd52uYX9-1M19Bakd0cHJ1OHM/view?usp=sharing

There were little lags on here too but could be acceptable.
So, my conclusion is that croppie performance is related with image size.

Is there any tip on handling a lage size image?

BTW I found a bug on pinch in/out zoom on croppie.
At the end of video I tried to pinch out zoom an image but the image was not zooming by the center of viewport.

**Comment by sctaix** [comment]
> At the end of video I tried to pinch out zoom an image but the image was not zooming by the center of viewport.

fixed by add `_updateCenterPoint.call(self);` to change() function.

mobile just bypass start() function some how.
