### ISSUE TITLE
Feature request: Allow image to be smaller than viewport

### ISSUE THREAD

**Issue by datdinhquoc** [Foliotek/Croppie#670]
Not an issue or bug, but a feature request: 
Currently image can be zoomed out but can't be smaller than viewport.
We need option to allow image to be smaller than the viewport.

Use case: 
Sometimes there are square icons which should be added with blank/white margins.

**Comment by thedustinsmith** [comment]
http://foliotek.github.io/Croppie/#enforceBoundary

**Comment by datdinhquoc** [comment]
I found a work-around which is not in documentation: Set the value for 'maxZoom' in new Croppie options. By default this value is 1.5, set it to higher value to zoom out for images even as small as 1 pixel.

```
new Croppie({
    maxZoom: 50,
    ...
});
```
