### ISSUE TITLE
Viewport & Cropped Image is Wrong

### ISSUE THREAD

**Issue by imeidopf** [Foliotek/Croppie#673]
## Expected Behavior
Using SweetAlert2 and Croppie, I should be able to upload an image for cropping and have the image appear with a min-width of the viewport and the cropped image properly cut from within that viewport.

## Actual Behavior
Image is smaller than viewport and the cropped result is not what's inside the square/circle. In order to get the viewport and crop to be in the full circle/square, a lot of zoom is required. This happens in Chrome and Firefox, while Edge works fine.

## Steps to Reproduce the Problem
I have setup a demo account on a personal project dashboard for testing.
  1. Click the button in the example link.
  2. Upload an image.
  3. Click 'okay' - This is where firefox/chrome have the image smaller than the view port.
  4. Do not zoom and click 'save' to see the cropped result. Then, optionally, go to the next step.
  5. Repeat steps 1-3, but this time zoom the image in until the slider is around, at least, the middle of the pop-up.
  
## Example Link
* Link: [https://codepen.io/anon/pen/LwGBOY](https://codepen.io/anon/pen/LwGBOY)

## Specifications

  - Browser: Chrome | Firefox | Edge
  - Version: 75.0.3770.142 | 68.0.1 | 44.18362.1.0

**Comment by rob-lindman** [comment]
Hi Jason,

Thank you for your interest in my profile.  I will follow up with you as soon as possible.

Key points of interest to recruiters (please review carefully):

The best way to reach me is on LinkedIn

FULL PORTFOLIO AND RESUME: https://roblindman.net/
SKILLS MATRIX: https://roblindman.net/resume-skills.php

IMPORTANT: I REQUIRE relocation or travel expenses covered for on-site roles.

US CITIZEN
REMOTE WORK PREFERRED
LOCATION: RIVERSIDE, CA

* NOT INTERESTED IN ALL INCLUSIVE *
* NO OVERSEAS AGENCIES *

I look forward to working with you,

Rob Lindman
(951) 394-2665
https://roblindman.net/
ADD ME ON LINKEDIN 
https://www.linkedin.com/in/roblindman

This message does not confer the right to represent. You are not authorized to submit me for roles without my explicit approval. This communication is copyrighted material.

**Comment by imeidopf** [comment]
@thedustinsmith I've read through the referenced links and issues that are related to similar cropping problems, but they don't seem to present a fix for me. Thoughts?

**Comment by thedustinsmith** [comment]
This is because the swal isn't completely shown before you're binding croppie.  I quickly looked through swal2's documentation, but couldn't find any method that's fired after the swal is completely shown, but that doesn't mean it doesn't exist.

Here's an exaggerated example showing what I mean.  I'm using `setTimeout(()=>{}, 2000)` and the bind works properly. https://codepen.io/thedustinsmith/pen/gVPQBW

**Comment by imeidopf** [comment]
Thanks for this. Good workaround for now.

**Comment by zakaria-chahboun** [comment]
@thedustinsmith there is a function called `didOpen` or  `didRender` to do what you want in [docs](https://sweetalert2.github.io/#didRender)

But i have an issue even when i trying this like image below, The image is not fit the boundary box or i don't know!



![image](https://user-images.githubusercontent.com/18173275/123698848-7ebc7880-d856-11eb-9c2d-82cfb007af52.png)

BTW this is my code (jquey)

```js
// Chose And Cut Default image
$("#DEFAULT-IMAGE-UPLOAD").click(function () {
  Swal.fire({
    title: "Sélectionnez votre image",
    showCloseButton: true,
    confirmButtonText: "Okay",
    input: "file",
    inputAttributes: {
      accept: "image/*",
      "aria-label": "Upload your profile picture",
    },
    preConfirm: () => {
      $(".swal2-file").change(function () {
        var reader = new FileReader();
        reader.readAsDataURL(this.files[0]);
      });
    },
  }).then((result) => {
    let uploadCrop; // global xD
    // Case 1: Confirm
    if (result.value && result.isConfirmed) {
      // result.value = input.value = file ✌
      // generate a modal dialog
      Swal.fire({
        title: "recadrer votre image",
        html: `<span style="width:100%" id="image_upaload_space"></span><div><img id='uSi'/><div>`,
        didRender: () => {
          // then generate the cropper inside the modal
          uploadCrop = $("#image_upaload_space").croppie({
            enableExif: true,
            viewport: {
              width: 200,
              height: 200,
              type: "squar",
            },
            boundary: {
              width: 300,
              height: 300,
            },
          });
          // get the image url, and bind it in the cropper
          const objectURL = URL.createObjectURL(result.value);
          uploadCrop.croppie("bind", {
            url: objectURL,
          });
          // live preview cut
          $("#image_upaload_space").on(
            "update.croppie",
            function (ev, cropData) {
              uploadCrop
                .croppie("result", {
                  type: "canvas",
                  size: "viewport",
                })
                .then(function (resp) {
                  $("#uSi").attr("src",resp);
                });
            }
          );
        },
      }).then((res) => {
        if (res.isConfirmed) {
          uploadCrop
            .croppie("result", {
              type: "canvas",
              size: "viewport",
            })
            .then(function (resp) {
              Swal.fire({ html: `<div><img src="${resp}"/></div>` });
            });
        }
      });
    }
    // Case 2: Cancel
    else if (!result.value && result.isConfirmed) {
      Swal.fire({
        html: `<i class="fas fa-3x has-text-success fa-image"></i> <br><br>S'il vous plaît ajouter une image!`,
      });
    }
  });
});
```
