### ISSUE TITLE
Crop in ios

### ISSUE THREAD

**Issue by skymanc** [Foliotek/Croppie#69]
When I use Croppie 1.0.3 in ios device
I'll get base64 data like this(not all string)
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGfCAYAAABx6YQZAAAAAXNSR0IArs4c6QAAC2lJREFUeAHt0DEBAAAAwqD1T20IX4hAYcCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQ

It seems to be some error?

**Comment by thedustinsmith** [comment]
What seems to be the error?  Are you not wanting a base64 string?

**Comment by skymanc** [comment]
I mean the string can't be convert to origin image, it's a blank png.
In web android OS, it works well but in ios, it always be a blank png with the same code.

**Comment by thedustinsmith** [comment]
Does the same thing happen if you're using the latest version of croppie, 1.0.5?

**Comment by thedustinsmith** [comment]
@skymanc If you're still having issues with this - you might check out `npm install croppie@2.0.0-beta1`.  It has some mobile picture support built in, if you pass the `exif:true` parameter to the constructor.

**Comment by thedustinsmith** [comment]
https://github.com/Foliotek/Croppie/releases/tag/v2.0.0
