### ISSUE TITLE
Clarification - Can I update croppie programatically after initialization?

### ISSUE THREAD

**Issue by jdylanmc** [Foliotek/Croppie#697]
After Croppie has been initialized, is it possible to programatically zoom/move the crop point?  How do you do this?

**Comment by thedustinsmith** [comment]
The `bind({opts})` method should help with this.

http://foliotek.github.io/Croppie/#bind

**Comment by jdylanmc** [comment]
When using bind, do you always have to pass in the image?  I just want to bind points but this seems to cause issues.

croppie.js:190 Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at croppie.js:190
    at new Promise (<anonymous>)
    at loadImage (croppie.js:181)
    at Croppie._bind (croppie.js:1312)
    at Croppie.bind (croppie.js:1594)
    at PictureEditor.js:167
    at Array.forEach (<anonymous>)
    at Object._setFocalPoint (PictureEditor.js:142)
    at Object.onDrag (PictureEditor.js:187)
    at o.drag (draggable.min.js:1)

**Comment by thedustinsmith** [comment]
Oops - yeah good point. You probably always need to include the url.

**Comment by jdylanmc** [comment]
Also, when using bind it only appears to work if the croppie has been interacted with previously.  Is there a way to get around this?

I basically am initializing multiple croppies, and then allowing a user to select a "Focal Point" of my image.  Moving the focal point element around programatically updates all of the croppies to follow.

**Comment by thedustinsmith** [comment]
I'm not familiar with that bug, if it is one can you provide some example code jsbin/jsfiddle/codepen?

**Comment by jdylanmc** [comment]
Sorry, I have just realized it's because I'm hiding Croppies behind modals.  The modals have their visibility set to hidden at the time I'm trying to programatically bind them.  I believe I need to set their opacity to 0 and push them down with z-index instead.  I'll tinker with it and let you know if there really is a bug.

Thanks for your help.
