### ISSUE TITLE
Allow for base64 image data input

### ISSUE THREAD

**Issue by 1N50MN14** [Foliotek/Croppie#70]
It would be great if `bind()` could support base64 image data as well, alternatively introduce `bind64()` or similar.

**Comment by thedustinsmith** [comment]
@1N50MN14 What happens when you pass in a base64 image into `bind({url: 'base64here'})`?

**Comment by 1N50MN14** [comment]
@thedustinsmith Apologies I didn't see your response, it does indeed work it was my fault that's why I closed this issue.

**Comment by thedustinsmith** [comment]
OK - I saw this [comment ](https://github.com/Foliotek/Croppie/pull/67#issuecomment-181983061)and remembered this issue, so I thought I'd post for clarity

**Comment by 1N50MN14** [comment]
Yup, the only thing in that regard is that Croppie is not requirable in a Node/CommonJS environment due to the lack of module.exports. Another thing I noticed is with large images there's a "flick" for a split second as Croppie first inserts the image element and then applies the css on it once its been added to the DOM. I fixed that by setting the default opacity to zero, then set it back to 1 when applying the css. Happy to send a PR if you think the above makes sense. (Ps well done! Love Croppie)

**Comment by thedustinsmith** [comment]
I like the idea of the opacity change, if you can submit a PR, that'd be great.

**Comment by 1N50MN14** [comment]
Awesome, just send a PR and enabled module.export while at it so that Croppie can be used in Lasso and Browserify (I believe this was the original purpose the `b` thing you had in your original factory, now this is generic and should work across all Node.js bundlers)

**Comment by atgillette** [comment]
FYI - npm is still pointing to version 1.0.3
