### ISSUE TITLE
Bug resizing

### ISSUE THREAD

**Issue by voskobovich** [Foliotek/Croppie#72]
See video https://youtu.be/D2d57C_nK1s
I use demo code
```
var mc = $('#js-croppie');
mc.croppie({
    viewport: {
        width: 150,
        height: 150,
        type: 'circle'
    }
});
mc.croppie('bind', 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/pie.png');
```
Why is this happening?

**Comment by voskobovich** [comment]
This happens after the bootstrap connection.css (Twitter Bootstrap 3)

**Comment by thedustinsmith** [comment]
Thanks for the info! 

FYI, if you'd prefer to call `mc.croppie('bind', {with parameters});` outside of your `shown.bs.modal` event, you can.  Then you can just call `mc.croppie('bind')` inside the callback to refresh croppie's location.
