### ISSUE TITLE
Object is not a constructor (evaluating 'new Croppie')

### ISSUE THREAD

**Issue by atgillette** [Foliotek/Croppie#73]
Hi,

I'm using Croppie via npm. In one of my files, I'm using require to load Croppie:
`var Croppie = require('croppie');`

Then I'm trying to create an Croppie instance:
`self.croppie = new Croppie(document.getElementById('croppie'));`

But I get the following error when I run my app:
`Object is not a constructor (evaluating 'new Croppie')`

Any ideas on what I'm doing wrong?

**Comment by atgillette** [comment]
Look like https://github.com/Foliotek/Croppie/pull/71/files should address the npm issue.  I vote for this one.

**Comment by thedustinsmith** [comment]
#71 is part of the latest npm release now, thanks for interest.
