### ISSUE TITLE
Cordova App iOS - not returning result

### ISSUE THREAD

**Issue by dhwalin** [Foliotek/Croppie#732]
This is little weird but I have made a Cordova App. Few months ago, iOS has stopped UIWebView & told developer to develop in WKWebView.

So I have installed Cordova WKWebView Engine, everything is perfectly but Croppie start giving error. Croppie is getting initialized but it is not getting result. It is not entering to “then” function in result.

No result is appearing in console log.

$('#save_btn').on('click',function(ev){

croppie_element.croppie('result', {
type: 'canvas',
size: { width: 200, height: 200 },
format: 'png',
circle:true,
}).then(function (canvas) {
console.log(“croppie result”)
$('#img_block').append('<img src='+canvas+'>');
});
});

**Comment by dhwalin** [comment]
Promise Error: 

CROPPIE ERR SecurityError: The operation is insecure.

Update:
Closing because it is not related to croppie.

**Comment by gmbad** [comment]
Hi @dhwalin!

I have the same problem here. In browser works fine, but on cordova result in error.

Did you manage to find a solution?

Tks
