### ISSUE TITLE
Get the image in JPG instead of PNG

### ISSUE THREAD

**Issue by alexmngn** [Foliotek/Croppie#74]
Hi there!
I noticed in your code that it always returns the image in PNG, even though I'm cropping a JPG image.

```
return canvas.toDataURL();
```

The `toDataURL` can accept a parameter to set the type, JPG or PNG. It would be awesome to integrate this feature :)

**Comment by alexmngn** [comment]
See #75

**Comment by thedustinsmith** [comment]
https://github.com/Foliotek/Croppie/releases/tag/v2.0.0

**Comment by tnlthanzeel** [comment]
how can i save the cropped image in asp mvc 5?
