### ISSUE TITLE
Image is too large on upload into croppie, set default zoom to 0

### ISSUE THREAD

**Issue by NeoRoussel** [Foliotek/Croppie#762]
Hi, I recently decided to implement croppie into my project and it's working great! There is just one issue that I have with it : on upload, images that are quite large are very zoomed in (see actual behavior below) and I would like to set their default zoom to 0 (so that the image fits the container basically, see expected behavior). I've tried stuff like el.bind { points:[...] }, el.setZoom() and el.initialZoom but none seem to work. I'm on Windows, Firefox 90.0.2 (64 bits). 

## Expected Behavior
![image](https://user-images.githubusercontent.com/45109095/128863498-a4a567e1-d01f-4c90-9349-1fac0a94d544.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/45109095/128863452-5bac2616-6fe0-487b-a7e6-7fac6c48db46.png)

My code :   

var cropElement = new Croppie(classEl('modal-crop-image'), {
      viewport: { width: cropSize, height: cropSize, type: 'square' },
      initialZoom = zoomer.min
    });
    cropElement.setZoom(0);
    cropElement.bind({
        url: imageURL,
        zoom: 0,
    });

with cropSize being the value that I get from my uploaded image to determine the viewport's size. 

Thanks for your help! :)

**Comment by NeoRoussel** [comment]
Hi again, so I've found a solution, as precised in the important notes, the problem came from the bind function being called while the modal hasn't appeared yet. If you have the same problem check it out ;)

**Comment by talha2k** [comment]
@NeoRoussel That was the issue in my case.

Code to fix it:

$("#croppieModal").on("shown.bs.modal", function (e) {
    $uploadCrop.croppie("bind");
});
