### ISSUE TITLE
Select Image instead of upload

### ISSUE THREAD

**Issue by Gaja-A** [Foliotek/Croppie#766]
Hi,

I'm using the Croppie plugin to upload images, rotate and zoom them. At the same time, I need to add sample images before uploading.

For example, I have a block to upload the image and a block where the user can select the image from the sample images. But I can't select the image using Croppie. 

1. The block where I can upload or select an image
![image]()

2. After I uploaded, it displays like this. So I want to do the same manner for selected image.
![image]()

How can I do this ?

Regards,
Gaja

**Comment by Gaja-A** [comment]
I solved it.

**Comment by zen85** [comment]
can you upload your solution please?

It sound a lot like my usecase and i was wondering how to do exactly that.

greetings
