### ISSUE TITLE
how to work with Ajax data to php

### ISSUE THREAD

**Issue by geranjian** [Foliotek/Croppie#79]
good day

this is my html

```

<script type="text/javascript">
$( document ).ready(function() {
    var $uploadCrop;

    function readFile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();          
            reader.onload = function (e) {
                $uploadCrop.croppie('bind', {
                    url: e.target.result
                });
                $('.upload-demo').addClass('ready');
            }           
            reader.readAsDataURL(input.files[0]);
        }
    }

    $uploadCrop = $('#upload-demo').croppie({
        viewport: {
            width: 200,
            height: 200,
            type: 'scuere'
        },
        boundary: {
            width: 300,
            height: 300
        }
    });

    $('#upload').on('change', function () { readFile(this); 
        $(".crop").show(); 
              
    });
    $('.upload-result').on('click', function (ev) {
        
        $uploadCrop.croppie('result', {
            type: 'canvas',
            size: 'original'
        }).then(function (resp) {
            $('#imagebase64').val(resp);
            $('#form').submit();
        });
    });
    $('.upload-result').on('click', function (ev) { 
            $uploadCrop.croppie('result', 'canvas').then(function (resp) { 
                popupResult({ 
                    src: resp 
                }); 
            }); 
        }); 
         
    function popupResult(result) { 
        var html; 
        if (result.html) { 
            html = result.html; 
        } 
        if (result.src) { 
            html = '<img src="' + result.src + '" />'; 
        } 
        $("#result").html(html); 
    } 



});
</script>
</head>
<body>
<form action="images.php" id="form" method="post">
<input type="file" id="upload" value="Choose a file">
<div id="upload-demo"></div>
<input type="hidden" id="imagebase64" name="imagebase64">
<a href="#" class="upload-result">Send</a>
</form>
<div id="result"></div> 



and this my php

<?php
    
    session_start();
    if(isset($_POST['imagebase64'])){
        $data = $_POST['imagebase64'];

        list($type, $data) = explode(';', $data);
        list(, $data)      = explode(',', $data);
        echo $data;
        $data = base64_decode($data);

        echo file_put_contents('demo/andres.png', $data);
    }
?>

as send information for ajax????

**Comment by thedustinsmith** [comment]
What seems to be the problem?  Looks like you have the same structure as #62, and it was resolved.

**Comment by geranjian** [comment]
this is my code for work ajax

index.html or php
`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>Croppie</title>
<meta name="keywords" content="CSS3" />
<meta name="description" content="HTML5、CSS3、jquery、PHP" />

<script src="http://libs.useso.com/js/jquery/2.1.0/jquery.min.js"></script>
<script src="../../croppie/js/croppie.min.js"></script>
<link rel="stylesheet" href="../../croppie/css/croppie.css">
<style>
.demo{width:360px; margin:60px auto 10px auto}

button,
a.btn {
    background-color: #189094;
    color: white;
    padding: 10px 15px;
    border-radius: 3px;
    border: 1px solid rgba(255, 255, 255, 0.5);
    font-size: 16px;
    cursor: pointer;
    text-decoration: none;
    text-shadow: none;
}
button:focus {
    outline: 0;
}

.file-btn {
    position: relative;
}
.file-btn input[type="file"] {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
}

.actions {
    padding: 5px 0;
}
.actions button {
    margin-right: 5px;
}
.crop{display:none}
#result img{
  border: solid 5px #C0C0C0;
} 
</style>
</head>

<body>
<div id="header">
   <div id="logo"><h1><a href="http://www.helloweba.com" title="返回helloweba首页">helloweba</a></h1></div>
</div>
<div id="main">

  
  <div class="demo">
    <div class="actions">
            <button class="file-btn">
                <span>Cargar</span>
                <input type="file" id="upload" value="选择图片文件" />
            </button>
            <div class="crop">
        <div id="upload-demo"></div>
        <button class="upload-result">Upload</button>
      </div>
      <div id="result"></div>
        </div>
  </div>
</div>
<script>
$(function(){
  var $uploadCrop;

    function readFile(input) {
      if (input.files && input.files[0]) {
              var reader = new FileReader();
              
              reader.onload = function (e) {
                $uploadCrop.croppie('bind', {
                  url: e.target.result
                });
                $('.upload-demo').addClass('ready');
                  // $('#blah').attr('src', e.target.result);
              }
              
              reader.readAsDataURL(input.files[0]);
          }
          else {
            alert("Sorry - you're browser doesn't support the FileReader API");
        }
    }

    $uploadCrop = $('#upload-demo').croppie({
      viewport: {
        width: 200,
        height: 300,
        type: 'squere'
      },
      boundary: {
        width: 400,
        height: 550
      }
    });

    $('#upload').on('change', function () { 
      $(".crop").show();
      readFile(this); 
    });
    $('.upload-result').on('click', function (ev) {
      $uploadCrop.croppie('result', 'canvas').then(function (resp) {
        popupResult({
          src: resp
        });
        $.ajax({
          url: 'upload.php',
          type: 'POST',
          
          data: {imagebase64: resp},
          success:function(data)
          {
            console.log(data);
          }
        });
       
        
      });
    });
    
  function popupResult(result) {
    var html;
    if (result.html) {
      html = result.html;
    }
    if (result.src) {
      html = '<img src="' + result.src + '" />';
    }
    $("#result").html(html);
  }
});
</script>


</body>
</html>`

server.php

`<?php
    session_start();
 
    if(isset($_POST['imagebase64'])){
        $data = $_POST['imagebase64'];

        list($type, $data) = explode(';', $data);
        list(, $data)      = explode(',', $data);
            
        $data = base64_decode($data);
        $d=mt_rand(4,30);
       	
         echo json_encode(file_put_contents('demo/'.$d.'.png', $data));
    }
    
?>`

thanks for your help

**Comment by thedustinsmith** [comment]
I'm sorry I'm having a hard time understanding you.  I'm guessing that your issue is resolved, so i'm going to close this one.  If it's not, comment again and I can try to help.
