### ISSUE TITLE
support ie 9

### ISSUE THREAD

**Issue by FlexLi99** [Foliotek/Croppie#81]
Hello, guys!

I need some help in the finalization of the plugin for IE 9. When I open the page in IE9 with the connected plug-in there is an error «Fail to receive the value "add" link, which is not defined or is NULL» (look at screenshot).
![0bca5f3d94](https://cloud.githubusercontent.com/assets/17352435/13195937/fdbb7c30-d7d0-11e5-92ee-24ae36e50831.jpg)

Thank you! Have a nice day!

**Comment by thedustinsmith** [comment]
If you change the line that contains `classList.add('cr-boundary')` to 

```
if (boundary.classList) {
    boundary.classList.add('cr-boundary');
}
else {
    boundary.className += ' cr-boundary';
}
```
Does that fix the issue? I don't have IE 9, otherwise I'd test it myself.

**Comment by FlexLi99** [comment]
The change corrects that mistake, but then everything went wrong. All lines with method "add" call error.  
![err](https://cloud.githubusercontent.com/assets/17352435/13280758/e4b11de4-daf0-11e5-961c-39023f6f6da1.jpg)

**Comment by thedustinsmith** [comment]
If you grab the latest from master, those utility functions should take care of your class list problems.  I wouldn't be surprised if there are other issues though.

**Comment by FlexLi99** [comment]
This commit solved all class list problems, there are no more errors in logs, and my scripts work! But, as I know, ie9 does not support filereader api, and plugin displays a message about this. Thanks for your help!
