### ISSUE TITLE
How works "update" event

### ISSUE THREAD

**Issue by croban** [Foliotek/Croppie#82]
Hi

How can I set "update" event?
With this implementation it does not work.
```
$('#image-cropper').cropit({
		allowCrossOrigin: true,
		width: cropWidth,
		height: cropWidth,
		exportZoom: minSize / cropWidth,
                update: function(c) {
                    console.log("this never happens");
                }
	});
```

**Comment by voskobovich** [comment]
Why do you use function "cropit" instead "croppie"?
Follow the documentation and everything will turn out.

**Comment by thedustinsmith** [comment]
You might be looking for https://github.com/scottcheng/cropit.

**Comment by croban** [comment]
Sorry guys... 
Totally wrong GIT Repo :(
