### ISSUE TITLE
Remove Position Dependencies

### ISSUE THREAD

**Issue by adam-rocska** [Foliotek/Croppie#83]
## Summary

Image boundaries, transformation origins, etc. are misplaced if there is an appearance animation involved (using **keyframes**, **transition**, or any other approach).
### Approach I.
1. Have the DOM Node you wish to use as the crop root node in a parent that is animated on load.
2. Have croppie do its magic on the load event of the window object
### Approach I.
1. Have the DOM Node you wish to use as the crop root node in a parent that is animated when it should appear (like a modal appearing on click)
2. Have croppie do its magic as soon as the animation is initialized.
## Expected behavior

The same as depicted on Croppie's landing page
## Actual behavior

Misplaced image, misplaced zooming, misplaced boundary.
## Solution proposal

Refactor croppie to be stateless about dimensions, coordinates, etc. Let the state to be the DOM's responsibility, that's what it's for.

**Comment by thedustinsmith** [comment]
Thanks for the detailed submission.  

I realize it's not what you want, but there is a work around for the problem you're describing: call `croppieInstance.bind()` after the animation or appearance change.

At the moment, it'st not realistic for me to spend time refactoring croppie to not care about its position.  I won't say it's not possible, but I do think it's going to be pretty difficult.

If this is something you really need, and have the interest in doing, I'd be happy to help in answering any questions.  And I'm definitely open to a PR.

**Comment by adam-rocska** [comment]
@thedustinsmith Thank you for your response. Since I'll be heavily building upon it on my personal project, I will be submitting pull requests as soon as I have the appropriate amount of effort to spend on it. 

**The suggested workaround** does work, that's how I figured out, that this was the root cause by accident.

This week I may be able to start contributing. I'd like to keep this issue open, as the changes I'll provide will mainly be related to this.

**Comment by thedustinsmith** [comment]
Sounds great!  I have no problem keeping this issue open.

I looked into it a big after you submitted the issue.  There are several places we're using `getBoundingClientRect` when we could just be using the given `width`/`height` for the viewport, boundary, and image.  

The problem comes when trying to center the image within the croppie, and also adjusting the overlay so it's always on top of your preview that you're dragging.  

Just my initial thoughts after looking into it.  Thanks for taking this one on!

**Comment by adam-rocska** [comment]
@thedustinsmith I have created a pull request for unit testing foundations. If it is okay, I will go further this week, to provide coverage to the part that has this issue, and a fix for it.

PR I'm talking about : https://github.com/Foliotek/Croppie/pull/84
