### ISSUE TITLE
Vanilla Sample fails to return result in v2.0.0

### ISSUE THREAD

**Issue by J0nKn1ght** [Foliotek/Croppie#85]
Hi,
Since the update to v2, there seems to have been some changes that cause an error when you use the `vanilla.result('canvas').then(...` syntax.  This can be seen in the Vanilla sample at http://foliotek.github.io/Croppie/.

Using the 
```
    $uploadCrop.croppie('result', {
        type: 'canvas',
        size: 'viewport'
    }).then(...
```
syntax works fine.

Thanks for a great library!

**Comment by thedustinsmith** [comment]
Woops!  Thanks for the catch.
