### ISSUE TITLE
Image rotation feature request

### ISSUE THREAD

**Issue by J0nKn1ght** [Foliotek/Croppie#86]
Hi,
Thanks for adding EXIF support in v2 - this came at exactly the right time for the project I'm working on.
I was wondering whether it would be possible to add a new method to allow you to rotate any loaded image in 90 degree increments?
There are some occasions where the EXIF data in the image isn't correct (especially from photos taken on smartphones), so it would be useful to be able to be able to perform a manual rotation of an image.

Thanks.

**Comment by thedustinsmith** [comment]
I like this idea.  The work done to get EXIF working makes this a lot easier.

Seems like there are two possibilities here - have croppie place buttons on the element and expose a parameter that lets you set a class on those elements.  For example, you could set 
`rotateButtonClass: 'fa'` 
for font awesome icons.

Or we could just expose a `rotate(deg)` method and hold the developer responsible for making buttons that do rotate croppie.

Or possibly both?

**Comment by J0nKn1ght** [comment]
Hi Dustin,

Both would be awesome.  If you could control whether the built in rotate button was rendered via an initialization option, and you also exposed the rotate method, it would allow complete control over the layout and styling.

**Comment by thedustinsmith** [comment]
There are methods to rotate the image with version 2.1.0.  I couldn't settle on an interface that I liked for adding buttons and allowing custom icons for those buttons so I didn't include it in this release.

Maybe in a future release.

**Comment by J0nKn1ght** [comment]
Thanks for the inclusion of rotation - this is a really good feature.  Unfortunately, I've run into some issues since updating to v2.1.0, so I've raised a new issue #123 for these.
