### ISSUE TITLE
Allow transparent space around img

### ISSUE THREAD

**Issue by powerbuoy** [Foliotek/Croppie#87]
Is there any way to allow the user to zoom out the image so much so that the entire image is visible, and transparent pixels are added around it? The problem with the cropper now is that if the image isn't the exact dimensions of the cropper there's no way to fit the whole image inside the crop area.

To explain further, in your first example here http://foliotek.github.io/Croppie/ what I'd like to be able to do is fit the entire image of the guy on the wall INSIDE the circle. Right now that doesn't seem to be doable.

Thanks

**Comment by thedustinsmith** [comment]
Seems like this one is being requested more often recently.

I'm thinking we can make this an optional parameter to pass into the croppie initialization.

**Comment by volshebnick** [comment]
Yeah, this is what I was also talking about. It's really needed!

**Comment by thedustinsmith** [comment]
I've added an `enforceBoundary` option to the croppie constructor.  By default it's true, but if you set it to false, you should be able to drag around and zoom freely without being restricted to the viewport.

After adding this, it seems like you really need the ability to set a minimum zoom.

**Comment by someidiot** [comment]
I'd like to see this with the ability to set the filler colour instead of just using transparent which results in ugly black bars for jpegs.

**Comment by pablocorezzola** [comment]
try 

`$("#imagen").croppie('result', { type: 'canvas',format :'jpeg', backgroundColor:'white'}).then(function(resp){
					//--- your code
})`

**Comment by aleberndt** [comment]
Try
photoCroppie.result({ type: 'base64', format: 'png', size: { width: 500 }, backgroundColor: '#FFFFFF00', circle: false })
