### ISSUE TITLE
Can't bind blob

### ISSUE THREAD

**Issue by gate3** [Foliotek/Croppie#88]
I am trying to bind a blob image created on the fly into a modal. I am calling the bind method on the click of a button. I have tried several other things without success. Here is an excerpt of my code

`$(document).ready(function(){

			var tmppath;
			var $basic = $('#demo').croppie({
			    viewport: {
			        width: 600,
			        height: 600
			    },
			    boundary: {
			        width: 700,
			        height: 700
			    },
			    exif:true
			});
			
			var r = new Resumable({
			  target:'/', 
			 // query:{upload_token:'my_token'}
			});
			r.assignBrowse(document.getElementById('upBtn1'));
			r.assignDrop(document.getElementById('upBtn1'));

			r.on('fileAdded', function(file){
				//console.log(file.file)
				  tmppath = URL.createObjectURL(file.file);
				  //console.log(tmppath)
				 // console.log($basic.croppie)
				 
				 
				 $("#image").fadeIn("slow").attr('src',tmppath);
			});

			r.on('fileSuccess', function(file,message){
				
		    });

		    
			$('#zoom_out').click(function(){
				 console.log(tmppath)
				$basic.croppie('bind',{
			    	url: tmppath,
			    	points: [77,469,280,739]
				  });

			})
			//Ensure image is selected before 
			$('#done').click(function(){
				 alert($(this).attr('data-index'));
			})
		})`

Please i would like to use this plugin. Kindly help

**Comment by thedustinsmith** [comment]
Instead of `tmppath = URL.createObjectURL(file.file);` could you try doing something similar to [demo.js](https://github.com/Foliotek/Croppie/blob/master/demo/demo.js#L103).

so your code would end up something like this:

```
r.on('fileAdded', function (file) {
    var reader = new FileReader();
    reader.onload = function (e) {
        tmppath = e.target.result;
    };
    reader.readAsDataURL(file);
});
```

I'm not very familiar with the resumable library, but I assume the file they pass you is an actual HTML5 `File` object.  If so, the above should work.

**Comment by gate3** [comment]
Thank you, let me try this.

**Comment by gate3** [comment]
Still not working, here is the error

Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

**Comment by gate3** [comment]
I console.logged the object being returned and it looks something like this

`lastModified: 1397514330446
lastModifiedDate: Mon Apr 14 2014 23:25:30 GMT+0100 (W. Central Africa Standard Time)
name: "2014-03-23 11.01.30.jpg"
size: 213554
type: "image/jpeg"
uniqueIdentifier: "213554-2014-03-23110130jpg"
webkitRelativePath: ""
__proto__: File`

**Comment by thedustinsmith** [comment]
Whoops, try `readAsDataURL(file.file)`

**Comment by gate3** [comment]
hi, i seem to have a found a solution. What i needed to do was bind to onloadend event of the file reader. My code now looks like this

`var tmppath;
			var $basic = $('#demo').croppie({
			    viewport: {
			        width: 600,
			        height: 600
			    },
			    boundary: {
			        width: 700,
			        height: 700
			    },
			    exif:true
			});
			
			var r = new Resumable({
			  target:'/', 
			 // query:{upload_token:'my_token'}
			});
			r.assignBrowse(document.getElementById('upBtn1'));
			r.assignDrop(document.getElementById('upBtn1'));

			r.on('fileAdded', function(file){
				//console.log(file.file)
				 // tmppath = URL.createObjectURL(file.file);
				   var reader = new FileReader();
				    reader.onload = function (e) {
				        tmppath = e.target.result;
				    };
				    reader.readAsDataURL(file.file);
				    reader.onloadend = function (e) {
				     // img.attr('src', reader.result);
				      //img.css('display', 'block');
				      console.log(tmppath)
				      $basic.croppie('bind',{
				    	url: tmppath,
				    	//points: [77,469,280,739]
					  });
				    }
				    
				 // 
				 
				 
				 $("#image").fadeIn("slow").attr('src',tmppath);
			});

			r.on('fileSuccess', function(file,message){
				
		    });

		    
			$('#zoom_out').click(function(){
				$basic.croppie('bind',{
			    	url: tmppath,
			    	//points: [77,469,280,739]
			    });			
			})
			//Ensure image is selected before 
			$('#done').click(function(){
				 alert($(this).attr('data-index'));
			})
		})`

**Comment by thedustinsmith** [comment]
Glad to hear it works for you!
