### ISSUE TITLE
r.js not working due to multipe define()-statements

### ISSUE THREAD

**Issue by tjveldhuizen** [Foliotek/Croppie#89]
Similar to issue https://github.com/jrburke/r.js/issues/716, when using Croppie my scripts can't get optimized due to multiple define()-statements in the code. The first one at the top, the second one is in the inclusion of Promise.

Would it be possible to find an other solution for the inclusion? Or do you have a suggestion how to optimize this? (grunt-contrib-requirejs)

**Comment by thedustinsmith** [comment]
I've never been satisfied with our Promise polyfill, not that it doesn't function, it just looks like it was compiled from coffee script and is a tad bit ugly.  I'm open to any other polyfills as long as it conforms to the standard.

**Comment by tjveldhuizen** [comment]
I don't have experience with Promise polyfills... so no suggestion, unfortunately. However, I have to manually edit the files after a bower install, so I hope somebody else knows a good solution.

**Comment by thedustinsmith** [comment]
This was released with 2.0.1
