### ISSUE TITLE
Y-position being reset when setting zoom in specific circumstances

### ISSUE THREAD

**Issue by tjveldhuizen** [Foliotek/Croppie#90]
See https://jsfiddle.net/tjveldhuizen/b3pa3eLo/

When I initialise Croppie with a non-zero y1 and y2 position, it works very well. However, when setting the zoom, those values are being reset to zero and the image height, respectively.

In the JSFiddle, this is represented by the upper-left button which is not working as expected (post-zoom in console is [8, 0, ...]), the other buttons are correct (post-zoom in console is [0, 500, ...], identical to the pre-zoom values).

**Comment by thedustinsmith** [comment]
What's happening here is croppie is trying to maintain your center point while zooming.  So when you bind your points, a zoom is implied.  Then when you're changing that zoom, croppie finds the point in the image that is centered in the viewport and zooms in/out of that point.  So the points that you bound will change.

I can see how this behavior would be undesired. One solution would be to implement something similar to #49 where you can set the zoom on binding or initialization, but then the x2 and y2 points become irrelevant.

Any other ideas?

**Comment by tjveldhuizen** [comment]
Hmm, your remark about the irrelevance of x2 and y2 makes me realise setting the zoom should not be necessary when I know those values. Don't know why I start setting the zoom, now... wil check asap what the real problem is.

**Comment by tjveldhuizen** [comment]
Indeed, it is not really necessary to be abled to initialise the zoom level together with the four points. Maybe it's convenient to add the ability to choose between initialising with x1-y1,x2-y1 or x1-y1,zoom, but it's not necessary for correct operation.
