### ISSUE TITLE
Result error with canvas result and viewport position and zoom

### ISSUE THREAD

**Issue by Franzwdk** [Foliotek/Croppie#92]
Hello,  I don't understand why when I crop a picture the cropped result doesn't correspond to viewport's area and zoom. Indeed zoom and position of the cropped area of the picture are not the good ones in result (see picture as example). I tried to modify some parameters as initial zoom and translate the viewport position but it had no effect... I think that the issue comes from getBoundingClientRect() but I'm not sure and I don't know how to fix it.  I use Django and Safari. Thanks for your wonderful work.

![issue](https://cloud.githubusercontent.com/assets/17667261/13546386/d1f782e2-e2ac-11e5-90db-53df911a5e47.png)

**Comment by thedustinsmith** [comment]
Can you share your code with us?  It would be easier to diagnose your problems that way.

**Comment by thedustinsmith** [comment]
Closing due to no contact.

**Comment by rubyshine72** [comment]
Hi! I have same case like this.

$uploadCrop_logo = $('#upload-logo').croppie({
	enableExif: true,
	viewport: {
		width: 800,
		height: 150,
		type: 'square'
	},
	boundary: {
		width: 1000,
		height: 240
	}
});

$('#upload_logo_file').on('change', function () { 
	var reader = new FileReader();
	reader.onload = function (e) {
		$uploadCrop_logo.croppie('bind', {
			url: e.target.result
		}).then(function(){	
		});
	}
	reader.readAsDataURL(this.files[0]);
});

$('#save_logo_change').on('click', function () {
	$uploadCrop_logo.croppie('result', {
		type: 'canvas',
		size: 'viewport',
	}).then(function (resp) {
		$("#save_logo_change .loading").css('display', 'inline');
		$.ajax({
			url: "save.php",
			type: "POST",
			data: {"image":resp},
			success: function (data) {
				..........
			}
		});
	});
});
