### ISSUE TITLE
Image freeze in Safari

### ISSUE THREAD

**Issue by iMac0de** [Foliotek/Croppie#96]
Hi guys,

I have a problem with croppie in Safari. In Chrome and Firefox it's work fine.

When I upload an image, the AJAX callback launch a Bootstrap3 modal and the crop of the image inside. But in Safari, I can't drag the image and the zoom slider doesn't work correctly : it zooming correctly but when it's reach the middle of the zoom slider, it unzooming.

I use Safari 9.0.3 on OX El Capitan.

Here some screenshots:

![chrome](https://cloud.githubusercontent.com/assets/3471100/13657436/21c76952-e624-11e5-93fb-5f2f0164a661.PNG)
In Chrome, the image it's correctly loaded and I can drag and zoom/unzoom.

![safari1](https://cloud.githubusercontent.com/assets/3471100/13657437/21c7def0-e624-11e5-8bc0-089f38deff20.PNG)
In Safari, the image after loading

![safari2](https://cloud.githubusercontent.com/assets/3471100/13657438/21c85204-e624-11e5-8e55-066b3367a8f9.PNG)
When I try to zoom/unzoom the picture. I can't drag.

This is the code executed by the AJAX callback:
```
    $('#crop-picture').modal('show');
    cropPicture.croppie({
        viewport: {
            width:150,
            height:150,
            type:'circle',
        },
        boundary: {
            width:250,
            height:250,
        },
        exif: true
    });
    cropPicture.croppie('bind', obj.files[0]);
```

Have you any idea where the problem is ?

Thanks.

**Comment by thedustinsmith** [comment]
I think you're having the same issue described in #72.

**Comment by iMac0de** [comment]
Yes it was the same issue. Thanks for the link, it works perfectly now! Good job for Croppie ;-)
