### ISSUE TITLE
Initial viewport is not zoomed

### ISSUE THREAD

**Issue by john-britto** [Foliotek/Croppie#98]
After binding the image the slider is set '50' but the actual image is not zoomed into that level. In order to avoid this I always want to set the zoom level to '0' initially after binding the image. I tried the following But it's not working as I expected 
"uploadCrop.croppie('setZoom',0);" 

*uploadCrop is the coppie object. Please let me know ur thoughts.

**Comment by thedustinsmith** [comment]
If you change the `_setZoomerVal()` on https://github.com/Foliotek/Croppie/blob/master/croppie.js#L332

... to look more like this ...
``` 
function _setZoomerVal(v) {
	if (this.options.enableZoom) {
		var z = this.elements.zoomer;
		z.value = Math.min(z.max, Math.max(z.min, fix(v, 4)));
	}
}
```

Does that resolve your issue?

**Comment by john-britto** [comment]
It's working but in that situation I cannot use this even if I use this
It's of no use. So for now I fixed by

uploadCrop.croppie('bind', {

    url : chosenImgSrc

   //points : [ 10, 10, 200, 200 ]

});


when I comment the "points" while binding the image by-default its zoomed
out completely.

Is there any way to zoom out completely by setting the "points" rather then
setting "uploadCrop.croppie('setZoom',0);" ?

**Comment by thedustinsmith** [comment]
If you'd like to zoom out completely by setting the points (since the points imply the zoom), you would say

`points: [0, 0, img.width, img.height]`

Of course, you'll need to get img.width and img.height on your own.  Also, this is assuming the aspect ratio of your `viewport` is the same as that of your image.  If not, there may be a portion of the image still outside of the viewport.

**Comment by john-britto** [comment]
Thanks!
I thought of this already but I think I can get the image width and height
only after binding the image right?

**Comment by thedustinsmith** [comment]
I don't think croppie exposes the image width and height.  You'd have to do that manually with something like this:
```
var i = new Image;
i.onload = funciton() {
   var w = i.width;
   var h = i.height;
}
i.src = 'image/path.png';
```

**Comment by john-britto** [comment]
Thanks I will try that.

**Comment by john-britto** [comment]
Hi,
What if I don't set the "points" ? what will be the default values? I did
try that way and it's not throwing any errors.

**Comment by thedustinsmith** [comment]
The default values without setting points tries to center the image in the viewport, with a scale that's right in between the min and the max (I think).

**Comment by john-britto** [comment]
I am doing that way it tries to center the image, indirectly that's what i
wanted.

Thanks for your response :)

**Comment by thedustinsmith** [comment]
No problem, hope it helped!

**Comment by john-britto** [comment]
Yeah ofcourse.
